### ISSUE TITLE
変数名の特定記号による、事前アップロードエラー①

### ISSUE THREAD

**Issue by m-takahashi-if** [exastro-suite/it-automation#10]
default/main.ymlに定義してある変数名やメンバー変数名が、シングルコーテーションやダブルコーテーションで囲まれていた場合、ロールの事前アップロード時にエラーになる。

例）
```
'VAR_HOGE':
  'mem1': hogehoge
  'mem2': hogehoge
```

**Comment by enoman** [comment]
変数名の特定記号による、事前アップロードエラー②  #11 
に集約します。
