### ISSUE TITLE
【管理コンソール】バージョン情報の表示について

### ISSUE THREAD

**Issue by wakkysan** [exastro-suite/it-automation#1006]
v1.7.0ではドライバとバージョン情報が表示されるが、下記点の見直しを行ったほうがユーザに優しいのではないかと思われる。
・ドライバとして、material、material2、material4の表記があるが、materialに統一したほうがいいか。
・もしくは、material(Ansible用)とかmaterial(Terraform用)とかわかるようにするか。
・そもそもドライバ毎にバージョンが変わることはないので、表示の仕方を見直すか。

**Comment by a-koizumi** [comment]
【#1006の仕様は以下となる】
①管理コンソールのバージョン確認
バージョン情報の「インストール済ドライバ」に「Base」は表示されない。
②バージョンアップ時は、バージョンアップ前の「インストール済ドライバ」のバージョンは対象外とする。
