### ISSUE TITLE
【Conductor】Conductor作業実行画面の操作ボタンが表示されない

### ISSUE THREAD

**Issue by y-yonekura** [exastro-suite/it-automation#1007]
Conductor実行にて、画面の操作ボタンが表示されない。
-全体表示
-表示リセット
-フルスクリーン

**Comment by a-koizumi** [comment]
Conductorクラス一覧⇒詳細表示「詳細」ボタン押下で
Conductorクラス編集へ遷移したときの画面も画面の操作ボタンが表示されない。
-全体表示
-表示リセット
-フルスクリーン
