### ISSUE TITLE
【メニュー作成】パラメータシートで作成し、初期化でデータシートにすると代入値自動登録用と参照用に作成されたメニューが残る

### ISSUE THREAD

**Issue by wakkysan** [exastro-suite/it-automation#1010]
タイトルの件に紐づいて、メニュー作成で作成したメニューのメニューIDを持つ必要があるかもしれません。

**Comment by sinatommy** [comment]
[#709](https://github.com/exastro-suite/it-automation/issues/709)と合わせて検討する。

**Comment by HibikiNanri** [comment]
マージ済み。
修正内容は #709 参照
