### ISSUE TITLE
機器一覧 - 機器登録にてログインパスワードの30バイト制限を拡張してほしい

### ISSUE THREAD

**Issue by yk-2** [exastro-suite/it-automation#1011]
### 内容
機器一覧画面 - 機器登録時にてログインパスワードの30バイト制限を拡張してほしい。

### 理由
AWS EC2 にて Windows Server を構築した際に、 AWS にて自動生成されるパスワードが32バイトのため、そのまま使用できず一手間加える必要があるため。

**Comment by ta-matsuo** [comment]
サイズを128バイトに変更する。

**Comment by ta-matsuo** [comment]
128バイトに拡張する。

**Comment by sutokaz** [comment]
validation, maxlengthを128、columnの型をvarchar(60)からtextへ。

**Comment by a-koizumi** [comment]
AnsibleTowerホスト一覧のパスワードも128バイトに変更する。
パスフレーズは対象外となる。
