### ISSUE TITLE
サンプルアドレスのドメインが実在している

### ISSUE THREAD

**Issue by yk-2** [exastro-suite/it-automation#1012]
### 内容
サンプルとして使用されているメールアドレスのドメインが実在するドメインとなっています。
例として使用するのであれば、 RFC で例示用として予約されている example.com 等にするべきかと思います。

### 対象ファイル
- https://github.com/exastro-suite/it-automation/blob/master/ita_install_package/ITA/ita-confs/commonconfs/app_mail_from.txt
- https://github.com/exastro-suite/it-automation/blob/master/ita_install_package/ITA/ita-confs/webconfs/admin_mail_addr.txt

### 参考
https://tools.ietf.org/html/rfc2606

**Comment by ta-matsuo** [comment]
「ユーザ管理」のadministratorのメールアドレス「sample@xxx.bbb.ccc」は削除する。
