### ISSUE TITLE
【Symphony作業確認】Movementで緊急停止してABORTになったあとに緊急停止が押せる

### ISSUE THREAD

**Issue by auguri-0412-0707-0515** [exastro-suite/it-automation#1013]
①．Symphony作業実行する
②．Movementに移動する
③．Movementで緊急停止する
④．Symphony作業確認でABORTになることを確認する
⑤．Symphony作業確認で緊急停止が押せちゃう

あるべき
⑤では、緊急停止ボタンが非活性になるべき

**Comment by yoshi-kooooh** [comment]
Conductorでは、同様の事象は起きない模様です。

**Comment by a-ikegame** [comment]
Symphony・Conductor共に、Movementに移動して緊急停止した場合
「緊急停止発令フラグ(未発令)：1」の状態となる。

■緊急停止ボタンが非活性となるタイミング
Conductor：ステータス取得のループ処理が終了したことをトリガーにボタン非活性となる。
Symphony：ステータスが「緊急停止」かつ「緊急停止発令フラグ(発令済み)：2」であることをトリガーにボタン非活性となる。（「緊急停止発令フラグ(未発令)：1」の状態ではボタンが非活性にならない。）

⇒Symphonyの仕様をConductorの仕様に統一する。
