### ISSUE TITLE
進捗状況(実行ログ)の表示改善

### ISSUE THREAD

**Issue by auguri-0412-0707-0515** [exastro-suite/it-automation#1014]
進捗状況(実行ログ)の表示を[Ansible共通]-[インターフェース情報]の進捗状態表示行数で制限するのではなく、ページ遷移によって実行ログを最初から最後まで見れるようにした。
※参考：Ansible Towerだと標準出力の内容が最初から最後まで見れる

![無題](https://user-images.githubusercontent.com/67850967/116178354-60e86f80-a750-11eb-9da7-c9802021fcbc.png)

現状は、サーバでexec.logを確認するか、ResultData_xxxxx.zipをダウンロードしないと見れないので、手間。

**Comment by yoshi-kooooh** [comment]
[ジャストアイデア]
既存のExastro ITAの作りは、
「完了ステータスになると最後に一回ログを表示させて、ログのポーリングは止まる」
だと思いますが、
「最後の1回だけはインタフェース情報に定義してるログ表示行数を無視して、全読み込みして全表示させる作りにする」
とかですかね。

以上、パっと考えた備忘です。

**Comment by a-koizumi** [comment]
【#1014の仕様は以下となる】

MariaDB [ITA_DB]> select * from B_ANSIBLE_STATUS;
+-----------+--------------------+----------+------+-------------+----------------------------+
| STATUS_ID | STATUS_NAME        | DISP_SEQ | NOTE | DISUSE_FLAG | LAST_UPDATE_TIMESTAMP      | LAST_UPDATE_USER |
+-----------+--------------------+----------+------+-------------+----------------------------+
|         1 | 未実行             |        1 | NULL | 0           | 2015-04-01 10:00:00.000000 |                1 |
|         2 | 準備中             |        2 | NULL | 0           | 2015-04-01 10:00:00.000000 |                1 |
|         3 | 実行中             |        3 | NULL | 0           | 2015-04-01 10:00:00.000000 |                1 |
|         4 | 実行中(遅延)       |        4 | NULL | 0           | 2015-04-01 10:00:00.000000 |                1 |
|         5 | 完了               |        5 | NULL | 0           | 2015-04-01 10:00:00.000000 |                1 |
|         6 | 完了(異常)         |        6 | NULL | 0           | 2015-04-01 10:00:00.000000 |                1 |
|         7 | 想定外エラー       |        7 | NULL | 0           | 2015-04-01 10:00:00.000000 |                1 |
|         8 | 緊急停止           |        8 | NULL | 0           | 2015-04-01 10:00:00.000000 |                1 |
|         9 | 未実行(予約)       |        9 | NULL | 0           | 2015-04-01 10:00:00.000000 |                1 |
|        10 | 予約取消           |       10 | NULL | 0           | 2015-04-01 10:00:00.000000 |                1 |
+-----------+--------------------+----------+------+-------------+----------------------------+
　⇒ステータスが上記STATUS_IDの5より下になった場合に全表示させる。
