### ISSUE TITLE
【Ansible-Driver】ホスト名を数字のみにすると実行時にワーニングとなる

### ISSUE THREAD

**Issue by ta-matsuo** [exastro-suite/it-automation#1020]
ホスト名を数字のみにすると実行時にワーニングが出力されて、
ステータスは「完了」となるがターゲットに対してPlaybookが実行されない。
AnsibleEngineのみ発生。AnsibleTowerは正常に実行される。

[WARNING]:  * Failed to parse /exastro/data_relay_storage/ansible_driver/legacy/ns/0000000001/in/hosts with yaml plugin:
argument of type 'int' is not iterable

**Comment by enoman** [comment]
機器一覧のホスト名に数値だけの値は登録できないようにバリデータをかける。

**Comment by enoman** [comment]
完了

**Comment by enoman** [comment]
AnsibleTowerホスト一覧のホスト名も同等のバリデータをかける。

**Comment by enoman** [comment]
完了
