### ISSUE TITLE
【収集機能】横型メニューへ異なるPREFIXで同一オペレーション・ホストにおけるデータ登録

### ISSUE THREAD

**Issue by wakkysan** [exastro-suite/it-automation#1051]

**Comment by y-yonekura** [comment]
一作業内で、対象ホストのソースファイルが複数存在し、収集項目値管理にて、
1つのメニューに対して収集させる設定がされている場合の対応を追加。

現状：「ソースファイル：収集対象メニュー」が、「N:1」の以下の場合、aaa.ymlののみ情報で登録、bbb.ymlの情報のみで更新処理を行い、収集完了後の画面上はbbb.ymlの情報のみとなる。

　対象ホスト：	HOST_A
　対象ファイル：	~/ansible_driver/legacy/ns/000000000/out/_parameters/HOST_A/
　　　　　　　　　-aaa.yml
　　　　　　　　　-bbb.yml
　対象メニュ: 	収集_横 (メニューID:0000000001)

→更新時、ソースファイル内の項目のみで更新へ変更
