### ISSUE TITLE
【Ansible-Driver】Pioneerモードの文字コード選択

### ISSUE THREAD

**Issue by sinatommy** [exastro-suite/it-automation#1052]
現状Pioneerモードでは、デフォルトの文字コードはUTF-8で実行される。
他の文字コードも選択できるようにする。

**Comment by enoman** [comment]
機器一覧にログインユーザーのLANGを設定する項目を追加

LANGの選択子は下記の3個
utf-8
euc
shift_jis
デフォルト(未選択時)はutf-8とする。
pexpectモジュールにエンコード文字を渡すことで、LANGがeuc/shift_jisでも文字化けは解消する。
しかし、一部の文字(①②等)をpexpectモジュールがUTF-8にデコードできないようで、デコード出来ない文字は??で表示。
また、一部の全角文字(－等)をexpect等のプロンプト待ちで使用した場合、LANGがUTF-8では待ち受けが正常に処理出来るが、LANGがeuc/shift_jisでは待ち受けがタイムアウトする。

**Comment by enoman** [comment]
完了

**Comment by enoman** [comment]
完了

**Comment by sinatommy** [comment]
機能追加しないこととする。
メンテナンスの問題、完全に文字変換はできないなどの理由から。
