### ISSUE TITLE
【全般】「備考」項目の改善

### ISSUE THREAD

**Issue by sinatommy** [exastro-suite/it-automation#107]
以下の「備考」項目は、入力不可かつ何も表示もされない項目となっている。
（吹き出しコメントは「自由記述欄･･･」）

Symphonyクラス一覧
Symphony作業一覧
Ansible-Legacyの作業管理
Ansible-Pioneerの作業管理
Ansible-LegacyRoleの作業管理

**Comment by h-matsuhashi** [comment]
●修正点
以下のメニューページの項目に表示・出力されるテーブルから「備考」を非表示にする。

●対象メニューページ
・Symphonyクラス一覧
・Symphony作業一覧
・Conductorクラス一覧
・Conductor作業一覧
・Ansible-Legacy作業管理
・Ansible-Pioneer作業管理
・Ansible-Legacy Role作業管理

●項目名
・フィルタ
・一覧
・一覧（Excel）
・全件ダウンロード（Excel）
・変更履歴
