### ISSUE TITLE
【管理コンソール】新規ユーザログイン時にパスワード変更画面に遷移させる

### ISSUE THREAD

**Issue by wakkysan** [exastro-suite/it-automation#1077]

**Comment by ta-matsuo** [comment]
備考欄を以下のように変更する。


パスワードの有効期間(日数)
正の数(整数のみ)：上記の通り
ゼロ以下：永久に有効（利用可能）となる

↓

パスワードの有効期間(日数)
正の数(整数のみ)：上記の通り、初回ログイン時のパスワード変更が有効となる
ゼロ以下：永久に有効（利用可能）となる
