### ISSUE TITLE
【Ansible-Driver】Pioneerの対話ファイル素材名称に()を含めると想定外エラーになる。

### ISSUE THREAD

**Issue by a-koizumi** [exastro-suite/it-automation#1078]
(1).yml
![image](https://user-images.githubusercontent.com/49502759/118596431-6c2a3a80-b7e6-11eb-9f9a-f3a3b5b36153.png)
![image](https://user-images.githubusercontent.com/49502759/118596587-882ddc00-b7e6-11eb-85a8-450115651250.png)

※v1.7.0からのバグ

**Comment by enoman** [comment]
https://github.com/exastro-suite/it-automation/issues/842
に修正に伴う不備
完了
