### ISSUE TITLE
【インストーラ】インストール時のコンフィグ初期値見直し

### ISSUE THREAD

**Issue by ta-matsuo** [exastro-suite/it-automation#1096]
現状はphp.iniのmemory_limitの初期値は512Mだが、メモリ不足がまれに発生するため初期値の見直しを行う。
 推奨環境（CPU:2Core、Memory:4GB）に合わせて他のコンフィグも見直しを行う。

**Comment by ta-matsuo** [comment]
#79 のDB性能検証も合わせて行う。

**Comment by ta-matsuo** [comment]
以下の初期値を変更する。

/etc/php.ini
memory_limit = 512M　⇒　memory_limit = 1024M

/etc/my.cnf.d/server.cnf
innodb_buffer_pool_size = 512MB　⇒　innodb_buffer_pool_size = 1024MB

**Comment by a-koizumi** [comment]
すでにMariaDBがインストールされていて設定とかが入ってると/etc/my.cnf.d/server.cnfは変わらない(innodb_buffer_pool_size = 512MB)

綺麗な新品のVM環境時に以下となる。
innodb_buffer_pool_size = 512MB　⇒　innodb_buffer_pool_size = 1024MB

**Comment by ta-matsuo** [comment]
RHEL8系でインストールされるパッケージphp-fpm用のコンフィグファイル/etc/php-fpm.d/www.confに以下の記載を追記する。
php_admin_value[memory_limit] = 1024M
