### ISSUE TITLE
【Ansible-Driver】変数名の特定記号による、事前アップロードエラー

### ISSUE THREAD

**Issue by m-takahashi-if** [exastro-suite/it-automation#11]
default/main.ymlに定義してある変数名やメンバー変数名に「-」や「:」が使用されている場合、ロールの事前アップロード時にエラーになる。

ITAのマニュアルには、変数名は「半角英数字とアンダースコア（ _ ）」であることと記載があるけど、ITAを考慮していないplaybookではそれ以外の文字が使用される場合がある。読み替え表など要検討。

⇒マニュアルには、
「コーテーションで囲わない場合は半角英数字とアンダースコア（ _ ）」
「コーテーションで囲う場合はxxxxxxx」
という記述を追加する。
それとともに、バリデーションチェック仕様を修正する。

**Comment by enoman** [comment]
バリデーションチェック仕様
親変数名
　変数名は英数字とアンダーバーのみ許容。
　シングル・ダブルコートで囲まれている変数名を許容。
　シングル・ダブルコートで囲まれている場合、代入値管理等の表示はシングル・ダブルコートを含み表示

メンバー変数
　メンバー変数名はascii文字(0x20～0x7e)で下記3文字を除き許容。
　　 [ ] . 
　シングル・ダブルコートで囲まれているメンバー変数を許容。
　シングル・ダブルコートで囲まれている場合、代入値管理等の表示はシングル・ダブルコートを含み表示

**Comment by enoman** [comment]
host_vars
'VAR_hoge2':
  'VAR_': VAR_
  'VAR-': VAR-

playbook
- debug:  var=VAR_hoge2["VAR_"]
- debug:  var=VAR_hoge2["VAR-"]

**Comment by enoman** [comment]
VAR-: VAR-

     playbook
       - command:  echo {{ "VAR_hoge-" }}
       - command:  echo {{ 'VAR_hoge-' }}
       - command:  echo {{ VAR_hoge2["VAR_"] }}
       - command:  echo {{ VAR_hoge2["VAR-" }}
      - debug:  var=VAR_hoge2["VAR_"]
      - debug:  var=VAR_hoge2["VAR-"]

        '".[]は処理都合
        \はansibleでエラーとなる

    　legacy-roleはYAMLパーサがシングル・ダブルコートを省いてしまう。
　　　代入値管理やホスト変数ファイルの変数名は、シングル・ダブルコートを省いた
　　　変数名となる。

     default_vars
      "VAR_hoge-":
      "VAR_hoge2":
        "VAR_": VAR_
        "VAR-": VAR-

     host_vars
       VAR_hoge-:
       VAR_hoge2:
         VAR_:
         VAR-:

**Comment by enoman** [comment]
バリデーションチェック仕様
　親変数名(VAR/CPF/TPF/GBL/LCA(読替前後))
　　1.英数字とアンダーバーのみの変数名
　　2.下記の6文字を除くascii文字(0x20～0x7e)の変数名
        ".[]\'　　
　　　※許容文字は、英数字と!#$%&()*+,-/:;<=>?@^_`{|}~

　　メンバー変数も同様

　　確認
　　　変数定義自体は、シングル・ダブルコートで囲まなくても良い。
　　　Playbookにで変数を使用する際に、シングル・ダブルコートで囲む必要がある。
　　　なので、変数名は英数字とアンダーバーと、".[]\'を除くascii文字(0x20～0x7e)で
　　　バリデーションチェック(正規表記)する。

     host_vars
      VAR_hoge-:
      VAR_hoge2:
        VAR_: VAR_
        VAR-: VAR-

     playbook
       - command:  echo {{ "VAR_hoge-" }}
       - command:  echo {{ 'VAR_hoge-' }}
       - command:  echo {{ VAR_hoge2["VAR_"] }}
       - command:  echo {{ VAR_hoge2["VAR-" }}
      - debug:  var=VAR_hoge2["VAR_"]
      - debug:  var=VAR_hoge2["VAR-"]

        '".[]は処理都合
        \はansibleでエラーとなる

    　legacy-roleはYAMLパーサがシングル・ダブルコートを省いてしまう。
　　　代入値管理やホスト変数ファイルの変数名は、シングル・ダブルコートを省いた
　　　変数名となる。

     default_vars
      "VAR_hoge-":
      "VAR_hoge2":
        "VAR_": VAR_
        "VAR-": VAR-

     host_vars
       VAR_hoge-:
       VAR_hoge2:
         VAR_:
         VAR-:

**Comment by enoman** [comment]
バリデーションチェック仕様
　親変数名(VAR/CPF/TPF/GBL/LCA(読替前後))
　　1.英数字とアンダーバーのみの変数名
　　2.下記の6文字を除くascii文字(0x20～0x7e)の変数名
        " . [ ] ' \
　　　※許容文字は、英数字と!#$%&()*+,-/:;<=>?@^_`{|}~

　　メンバー変数も同様

　　確認
　　　変数定義自体は、シングル・ダブルコートで囲まなくても良い。
　　　Playbookにで変数を使用する際に、シングル・ダブルコートで囲む必要がある。
　　　なので、変数名は英数字とアンダーバーと、".[]\'を除くascii文字(0x20～0x7e)で
　　　バリデーションチェック(正規表記)する。

     host_vars
      VAR_hoge-:
      VAR_hoge2:
        VAR_: VAR_
        VAR-: VAR-

     playbook
       - command:  echo {{ "VAR_hoge-" }}
       - command:  echo {{ 'VAR_hoge-' }}
       - command:  echo {{ VAR_hoge2["VAR_"] }}
       - command:  echo {{ VAR_hoge2["VAR-" }}
      - debug:  var=VAR_hoge2["VAR_"]
      - debug:  var=VAR_hoge2["VAR-"]

        '".[]は処理都合
        \はansibleでエラーとなる

    　legacy-roleはYAMLパーサがシングル・ダブルコートを省いてしまう。
　　　代入値管理やホスト変数ファイルの変数名は、シングル・ダブルコートを省いた
　　　変数名となる。

     default_vars
      "VAR_hoge-":
      "VAR_hoge2":
        "VAR_": VAR_
        "VAR-": VAR-

     host_vars
       VAR_hoge-:
       VAR_hoge2:
         VAR_:
         VAR-:

**Comment by enoman** [comment]
バリデーションチェック仕様
　親変数名(VAR/CPF/TPF/GBL/LCA(読替前後))
　　1.英数字とアンダーバーのみの変数名
　　2.下記の6文字を除くascii文字(0x20～0x7e)の変数名
        " . [ ] ' \
　　　※許容文字は、英数字と!#$%&()*+,-/:;<=>?@^_`{|}~

　　メンバー変数も同様

　　確認
　　　変数定義自体は、シングル・ダブルコートで囲まなくても良い。
　　　Playbookにで変数を使用する際に、シングル・ダブルコートで囲む必要がある。
　　　なので、変数名は英数字とアンダーバーと、".[]\'を除くascii文字(0x20～0x7e)で
　　　バリデーションチェック(正規表記)する。

     host_vars
      VAR_hoge-:
      VAR_hoge2:
        VAR_: VAR_
        VAR-: VAR-

     playbook
       - command:  echo {{ "VAR_hoge-" }}
       - command:  echo {{ 'VAR_hoge-' }}
       - command:  echo {{ VAR_hoge2["VAR_"] }}
       - command:  echo {{ VAR_hoge2["VAR-" }}
      - debug:  var=VAR_hoge2["VAR_"]
      - debug:  var=VAR_hoge2["VAR-"]

        '".[]は処理都合
        \はansibleでエラーとなる

    　legacy-roleはYAMLパーサがシングル・ダブルコートを省いてしまう。
　　　代入値管理やホスト変数ファイルの変数名は、シングル・ダブルコートを省いた
　　　変数名となる。

     default_vars
      "VAR_hoge-":
      "VAR_hoge2":
        "VAR_": VAR_
        "VAR-": VAR-

     host_vars
       VAR_hoge-:
       VAR_hoge2:
         VAR_:
         VAR-:

**Comment by enoman** [comment]
●●●●●●●●●●
●変数の命名書式
●●●●●●●●●●
　親変数名(VAR/LCA(読替前後))
　　1.英数字とアンダーバーのみの変数名
　　2.下記の6文字を除くascii文字(0x20～0x7e)の変数名
        " . [ ] ' \
　　　※許容文字は、英数字と!#$%&()*+,-/:;<=>?@^_`{|}~
　　　変数定義自体は、シングル・ダブルコートで囲まなくても良い。
　　　Playbookで変数を使用する際に、シングル・ダブルコートで囲む必要がある。
　　なので、変数名は英数字とアンダーバーと、" . [ ] ' \を除くascii文字(0x20～0x7e)で
　　バリデーションチェック(正規表記)する。

　メンバー変数も同様
　　但し親変数名は英数字とアンダーバーのみの変数名

●●●●●●●●●●
●Playbookの記述
●●●●●●●●●●

　　例
　　 host_vars
　　   VAR_hoge1: hoge
　　   VAR_hoge-: hoge
　　   VAR_hoge2:
　　     -var1: hoge
　　     -var2: hoge
　　   
     playbook
       #英数字とアンダーバーのみの変数名
       - command:  echo {{ VAR_hoge }}
       #6文字を除くascii文字(0x20～0x7e)の変数名
       - command:  echo {{ "VAR_hoge-" }}
       - command:  echo {{ 'VAR_hoge-' }}
       - command:  echo {{ VAR_hoge- }}  <=Ansibleでエラーとなる。
       #6文字を除くascii文字(0x20～0x7e)の多段変数
       - command:  echo {{ VAR_hoge2["-var1"] }}
       - command:  echo {{ VAR_hoge2["-var1"] }}

●●●●●●●●●●
●LegacyRoleの変数定義(default_vars/ita_readme) 
●●●●●●●●●●

　　VAR_hoge-: hoge
　　VAR_hoge2:
　　　-var1: hoge
　　　-var2: hoge

　　上記変数をdefault_vars/ita_readmeに定義する場合
　　※変数名には、シングル・ダブルコートで囲まなくても良い。

　　   VAR_hoge-: hoge
　　   'VAR_hoge-': hoge
　　   "VAR_hoge-": hoge

　　   VAR_hoge2:
　　     -var1: hoge
　　     -var2: hoge
　　     
　　   VAR_hoge2:
　　     '-var1': hoge
　　     '-var2': hoge
　　     
　　   VAR_hoge2:
　　     "-var1": hoge
　　     "-var2": hoge

　　YAMLパーサがシングル・ダブルコートを省いてしまうので、
　　代入値管理やホスト変数ファイルの変数名は、シングル・ダブルコートを省いた
　　変数名となる。


●●●●●●●●●●
●Legacy/Pioneer変数刈取
●●●●●●●●●●

　　playbookからの変数刈取は以下の書式とします。
　　{{ VAR_英数字とアンダーバー }}
　　{{ 'VAR_6文字を除くascii文字(0x20～0x7e)' }}
　　{{ "VAR_6文字を除くascii文字(0x20～0x7e)" }}

　　playbook
　　　#英数字とアンダーバーのみの変数名
　　　- command:  echo {{ VAR_hoge }}
　　　#6文字を除くascii文字(0x20～0x7e)の変数名
　　　- command:  echo {{ "VAR_hoge-" }}
　　　- command:  echo {{ 'VAR_hoge-' }}
　　　- command:  echo {{ VAR_hoge- }}  <=刈取対象から外れる

　　代入値管理やホスト変数ファイルの変数名は、シングル・ダブルコートを省いた
　　変数名となる。

**Comment by enoman** [comment]
●●●●●●●●●●
●変数の命名書式
●●●●●●●●●●
　ITA独自変数(VAR/TPF/CPF/GBL/LCA(読替変数(読替後))
　　親変数名
　　　英数字とアンダーバーのみの変数名
　　メンバー変数名(Legacy-Role)
　　　1.英数字とアンダーバーのみの変数名
　　　2.下記の6文字を除くascii文字(0x20～0x7e)の変数名
　　　　" . [ ] ' \
　　　　※許容文字は、英数字と!#$%&()*+,-/:;<=>?@^_`{|}~
　　　　変数定義自体は、シングル・ダブルコートで囲まなくても良い。
　　　　Playbookで変数を使用する際に、シングル・ダブルコートで囲む必要がある。
　　　　なので、変数名は、" . [ ] ' \を除くascii文字(0x20～0x7e)で
　　　　バリデーションチェック(正規表記)する。

　LCA読替変数(読替前)
　　親変数名／メンバー変数名
　　　1.英数字とアンダーバーのみの変数名
　　　2.下記の6文字を除くascii文字(0x20～0x7e)の変数名
           　" . [ ] ' \
　　　　※許容文字は、英数字と!#$%&()*+,-/:;<=>?@^_`{|}~
　　　　変数定義自体は、シングル・ダブルコートで囲まなくても良い。
　　　　Playbookで変数を使用する際に、シングル・ダブルコートで囲む必要がある。
　　　　なので、変数名は、" . [ ] ' \を除くascii文字(0x20～0x7e)で
　　　　バリデーションチェック(正規表記)する。

　　読替表
　　修　修
　　正　正
　　前　後　　　読替後　読替前
　　×　×　　　　LCA-a:  hoge-1
　　×　●　　　　LCA_a:  hoge-1
　　●　●　　　　LCA_a:  hoge_1

　　default／ITAreadme
　　修　修
　　正　正
　　前　後
　　●　●　　　　hoge_1:  aaaaa
　　
　　×　●　　　　hoge-2:
　　●　●　　　　  var_1: aaaaa
　　×　●　　　　  var-2: aaaaa
　　
　　×　●　　　　hoge-3:  aaaaa
　　                  
　　×　●　　　　hoge-4:       
　　×　●　　　　  var-1: aaaaa
　　×　●　　　　  var-2: aaaaa
　　　                  
　　●　●　　　　VAR_hoge_5:   
　　×　●　　　　  var-1: aaaaa
　　×　●　　　　  var-2: aaaaa

　　YAMLパーサがシングル・ダブルコートを省いてしまうので、
　　代入値管理やホスト変数ファイルの変数の表示は、シングル・ダブルコート
　　を省いた変数名となる。

**Comment by enoman** [comment]
●●●●●●●●●●
●変数の命名書式
●●●●●●●●●●
　ITA独自変数(VAR/TPF/CPF/GBL/LCA(読替変数(読替後))
　　親変数名
　　　英数字とアンダーバーのみの変数名
　　メンバー変数名(Legacy-Role)
　　　1.英数字とアンダーバーのみの変数名
　　　2.下記の6文字を除くascii文字(0x20～0x7e)の変数名
　　　　" . [ ] ' \
　　　　※許容文字は、英数字と!#$%&()*+,-/:;<=>?@^_`{|}~
　　　　変数定義自体は、シングル・ダブルコートで囲まなくても良い。
　　　　Playbookで変数を使用する際に、シングル・ダブルコートで囲む必要がある。
　　　　なので、変数名は、" . [ ] ' \を除くascii文字(0x20～0x7e)で
　　　　バリデーションチェック(正規表記)する。

　LCA読替変数(読替前)
　　親変数名／メンバー変数名
　　　1.英数字とアンダーバーのみの変数名
　　　2.下記の6文字を除くascii文字(0x20～0x7e)の変数名
           　" . [ ] ' \
　　　　※許容文字は、英数字と!#$%&()*+,-/:;<=>?@^_`{|}~
　　　　変数定義自体は、シングル・ダブルコートで囲まなくても良い。
　　　　Playbookで変数を使用する際に、シングル・ダブルコートで囲む必要がある。
　　　　なので、変数名は、" . [ ] ' \を除くascii文字(0x20～0x7e)で
　　　　バリデーションチェック(正規表記)する。

　　読替表
　　修　修
　　正　正
　　前　後　　　読替後　読替前
　　×　×　　　　LCA-a:  hoge-1
　　×　●　　　　LCA_a:  hoge-1
　　●　●　　　　LCA_a:  hoge_1

　　default／ITAreadme
　　修　修
　　正　正
　　前　後
　　●　●　　　　hoge_1:  aaaaa
　　
　　×　●　　　　hoge-2:
　　●　●　　　　  var_1: aaaaa
　　×　●　　　　  var-2: aaaaa
　　
　　×　●　　　　hoge-3:  aaaaa
　　                  
　　×　●　　　　hoge-4:       
　　×　●　　　　  var-1: aaaaa
　　×　●　　　　  var-2: aaaaa
　　　                  
　　●　●　　　　VAR_hoge_5:   
　　×　●　　　　  var-1: aaaaa
　　×　●　　　　  var-2: aaaaa

　　YAMLパーサがシングル・ダブルコートを省いてしまうので、
　　代入値管理やホスト変数ファイルの変数の表示は、シングル・ダブルコート
　　を省いた変数名となる。

**Comment by enoman** [comment]
●●●●●●●●●●
 ●変数の命名書式
●●●●●●●●●●
　ITA独自変数(VAR/TPF/CPF/GBL/LCA(読替変数(読替後))
　　親変数名
　　　英数字とアンダーバーのみの変数名
　　メンバー変数(連想配列)(Legacy-Role)
　　　1.英数字とアンダーバーのみの変数名
　　　2.下記の7文字を除くascii文字(0x20～0x7e)の変数名
　　　　" . [ ] ' \ :
　　　　※許容文字は、英数字と!#$%&()*+,-/;<=>?@^_`{|}~
　　　　変数定義自体は、シングル・ダブルコートで囲まなくても良い。
　　　　Playbookで変数を使用する際に、シングル・ダブルコートで囲む
　　　　hoge_1:
　　　　  hoge-1: val
　　　　  hoge-2: val
　　　　  
　　　　- command: echo {{ hoge_1['hoge-1'] }}
　　　　- command: echo {{ hoge_1['hoge-2'] }}
　　　　
　　　　変数名は、" . [ ] ' \ :を除くascii文字(0x20～0x7e)で
　　　　バリデーションチェック(正規表記)する。

　LCA読替変数(読替前)
　　親変数名
　　　1.英数字とアンダーバーのみの変数名
　　メンバー変数(連想配列)(Legacy-Role)
　　　1.英数字とアンダーバーのみの変数名
　　　2.下記の7文字を除くascii文字(0x20～0x7e)の変数名
　　　　" . [ ] ' \ :
　　　　※許容文字は、英数字と!#$%&()*+,-/;<=>?@^_`{|}~
　　　　変数定義自体は、シングル・ダブルコートで囲まなくても良い。
　　　　Playbookで変数を使用する際に、シングル・ダブルコートで囲む。
　　　　変数名は、" . [ ] ' \ :を除くascii文字(0x20～0x7e)で
　　　　バリデーションチェック(正規表記)する。

　　読替表
　　修　修
　　正　正
　　前　後　　　　読替後　読替前
　　×　×　　　　LCA-a: hoge_1
　　×　×　　　　LCA_a: hoge-1
　　●　●　　　　LCA_a: hoge_1

　　default／ITAreadme
　　修　修
　　正　正
　　前　後
　　●　●　　　　hoge_1: aaaaa

　　×　×　　　　hoge-2: aaaaa
　　
　　●　●　　　　hoge_3:
　　●　●　　　　 var_1: aaaaa
　　×　●　　　　 var-2: aaaaa
　　×　●　　　　 'var-3': aaaaa
　　×　●　　　　 "var-4": aaaaa

　　YAMLパーサがシングル・ダブルコートを省いてしまうので、
　　代入値管理やホスト変数ファイルの変数の表示は、シングル・ダブルコート
　　を省いた変数名となる。

**Comment by enoman** [comment]
完了

**Comment by enoman** [comment]
本件、別途、要相談したいことがあります。

**Comment by enoman** [comment]
本件、別途、要相談したいことがあります。
