### ISSUE TITLE
【管理コンソール】メニューグループ名称とメニュー名称のサイズ変更

### ISSUE THREAD

**Issue by ta-matsuo** [exastro-suite/it-automation#111]
メニューグループ名称とメニュー名称のサイズが現状64バイトだが、見た目等を考慮して変更を検討する。

**Comment by sinatommy** [comment]
64バイト→256バイト

**Comment by ta-matsuo** [comment]
以下の項目のサイズを64バイトから256バイトに変更する。
・「管理コンソール」－「メニューグループ管理」－「メニューグループ名称」
・「管理コンソール」－「メニュー管理」－「メニュー名称」
・「メニュー作成」－「メニュー作成情報」－「メニュー名」

**Comment by naoki-kondo** [comment]
メニュー名の変更、払い出し完了

**Comment by Satoshi-asano** [comment]
払戻完了
