### ISSUE TITLE
【エクスポート/インポート】廃止レコードに紐づいていたアップロードファイルがエクスポートされる

### ISSUE THREAD

**Issue by a-youhei** [exastro-suite/it-automation#1156]
エクスポート時に廃止情報の項目で「廃止を除く」を選択しても、廃止レコードに紐づいていたアップロードファイルがエクスポートされてしまう。

下記のディレクトリがそのまま移行されているようなので、メニューに関わらずアップロードしたファイルがすべて対象になっていると思われます。
/(ITAインストールディレクトリ)/ita-root/uploadfiles

●具体的には下記作業にて発生した事象
①移行元サーバで「Ansible-LegacyRole」→「ロールパッケージ管理」で不要なレコードを削除
②エクスポート時に廃止情報を「廃止を除く」を選択
③②でエクスポートした内容を移行先サーバにインポート
③廃止レコードは削除されているが、廃止レコードに紐づいていたアップロードファイルはインポートされる

●今回の作業での問題点
開発環境から本番環境にデータ移行する際に不要なデータがエクスポートされてしまう。

**Comment by ayaka-shinomiya** [comment]
以下の条件に当てはまる場合に事象が発生
・モード：環境移行且つ廃止情報：廃止を除く場合
