### ISSUE TITLE
【全般】登録をつぶしてるメニュー（インターフェス情報系）範囲外の値でフィルター検索のメッセージが違っている。

### ISSUE THREAD

**Issue by a-koizumi** [exastro-suite/it-automation#1184]
登録画面ないのに以下メッセージとなります。
例）　
Ansible共通インターフェース情報の状態監視周期(単位ミリ秒)Fromに
2147483646
表示フィルタ押下
「レコードはありません。新規登録は下記より可能です。」

対象メニュー
Ansible共通：インターフェース情報
Ansible共通：収集インターフェース情報
Symphony：Symphonyインターフェース情報
Conductor：Conductorインターフェース情報
Terraform：インターフェース情報
CI/CD for IaC：インターフェース情報

**Comment by a-ikegame** [comment]
対象画面（追加）
・Conductor＞Conductorクラス一覧
・Symphony＞Symphonyクラス一覧
・管理コンソール＞シーケンス管理
・基本コンソール＞Movement一覧
・Ansible-Pioneer＞作業管理
・Ansible-LegacyRole＞作業管理
・Terraform＞作業管理
・Ansible共通＞Ansible Towerホスト一覧

**Comment by a-koizumi** [comment]
上記に記載不備があったため対応メニュー改めて記載します。

【対応メニュー】
管理コンソール：シーケンス管理
Symphony：Symphonyインターフェース情報
Symphony：Symphonyクラス一覧
Conductor：Conductorインターフェース情報
Conductor：Conductorクラス一覧
Ansible共通：インターフェース情報
Ansible共通：収集インターフェース情報
Ansible-Legacy：作業管理
Ansible-Pioneer：作業管理
Ansible-LegacyRole：変数ネスト管理
Ansible-LegacyRole：作業管理
Terraform：インターフェース情報
Terraform：作業管理
CI/CD for IaC：インターフェース情報
