### ISSUE TITLE
【Symphony】Symphony定期作業実行のSonarQube指摘修正

### ISSUE THREAD

**Issue by ta-matsuo** [exastro-suite/it-automation#1190]
ita-root/backyards/ita_base/ky_std_synchronize-regularly.php

![image](https://user-images.githubusercontent.com/49501825/121979278-d40f7900-cdc4-11eb-8a3c-737e92f54b73.png)

![image](https://user-images.githubusercontent.com/49501825/121979304-dffb3b00-cdc4-11eb-8f4f-b9b07657b50c.png)

![image](https://user-images.githubusercontent.com/49501825/121979333-eab5d000-cdc4-11eb-97db-4a5db6c98ad0.png)

**Comment by HibikiNanri** [comment]
マージ済み。
