### ISSUE TITLE
【Conductor】Conductor定期作業実行のSonarQube指摘修正

### ISSUE THREAD

**Issue by ta-matsuo** [exastro-suite/it-automation#1191]
ita-root/backyards/ita_base/ky_std_synchronize-regularly2.php

![image](https://user-images.githubusercontent.com/49501825/121979436-26e93080-cdc5-11eb-9f7f-41054083435d.png)

![image](https://user-images.githubusercontent.com/49501825/121979458-31a3c580-cdc5-11eb-9911-86eb2649988d.png)

![image](https://user-images.githubusercontent.com/49501825/121979484-3c5e5a80-cdc5-11eb-8a6d-3960d8c376d2.png)

**Comment by HibikiNanri** [comment]
マージ済み。
