### ISSUE TITLE
【Symphony】Symphony作業一覧からのInput/Resultデータ取得機能追加

### ISSUE THREAD

**Issue by mtakahashiif** [exastro-suite/it-automation#12]
Symphony作業一覧から実行したMovementのInputdataとResultdataを取得できるようにする。

**Comment by sinatommy** [comment]
［対象］
Ansible-driver
Terraform-Driver

**Comment by enoman** [comment]
Input/ResultデータはMovementの作業実行と同様でInputとResultを割れる。
Input/Resultデータを作成するタイミングやダウンロード方法をどうするか
 案①完了したら固めたものをダウンロードできる状態にしておく。（デメリット：データ容量が増える）
 案②ボタンを押したら作成する。（デメリットRestAPIで取得できない）
=> 案②とし、RestAPIで取得できるようにしながら、データの二重使用をさけるようにする。

固める際のディレクトリ構成やファイル名は

inデータ
zipファイル名
InputData__Symphony_SymphonyインスタンスID(10桁).zip

ディレクトリ構成
Symphony内通番(10桁)/InputData_作業番号(10桁).zip
InputData_作業番号(10桁).zip:各Movement(ansible作業実行)で作成している zipファイル名

outデータ
zipファイル名
ResultData_Symphony_SymphonyインスタンスID(10桁).zip
ディレクトリ構成
Symphony内通番(10桁)/ResultData_作業番号(10桁).zip 
ResultData_作業番号(10桁).zip:各Movement(ansible作業実行)で作成している zipファイル名

<<例>>
Symphonyクラス  ID:1
Movementが2個あった場合
1.legacy         作業番号100
2.Legacy-Role　　作業番号200

InputData_Symphony_0000000001.zip
0000000001/InputData_0000000100.zip
0000000002/InputData_0000000200.zip

ResultData_Symphony_0000000001.zip
0000000001/ResultData_0000000100.zip
0000000002/ResultData_0000000200.zip

**Comment by Satoshi-asano** [comment]
DL処理後、作成したZIPファイルを削除
