### ISSUE TITLE
【全般】変更履歴のダウンロードファイル内の非表示列と非表示行の削除

### ISSUE THREAD

**Issue by sutokaz** [exastro-suite/it-automation#1205]
A-C,N列と3-7行を非表示にしているのだが、これらを出力結果から除きたい

雛形
it-automation/ita_install_package/ITA/ita-contents/ita-root/libs/messages/en_US_UTF-8_dumpTemplate.xlsx
it-automation/ita_install_package/ITA/ita-contents/ita-root/libs/messages/ja_JP_UTF-8_dumpTemplate.xlsx

scsvの方も対応範囲

**Comment by sinatommy** [comment]
関連issue
[【全般】変更履歴をExcelでダウンロードできるようにする #482](https://github.com/exastro-suite/it-automation/issues/482)

**Comment by a-koizumi** [comment]
上記記載の【現状】
「A-C,N列と3-7行を非表示にしているのだが、これらを出力結果から除きたい」
の記載内容に間違いがある。

★訂正版は以下となる。
「A-C,O列と3-7行を非表示にしているのだが、これらを出力結果から除きたい」
