### ISSUE TITLE
【メニュー作成】ファイル埋込変数名とテンプレート埋込変数名をプルダウン選択対象とする

### ISSUE THREAD

**Issue by wakkysan** [exastro-suite/it-automation#123]
以下案①②のどちらかで実現

案①
・ファイル管理、テンプレート管理に新規VIEWを追加
・ファイル埋込変数名とテンプレート埋込変数名に値を入れるとVIEWには'{{ CPF_xxx }}'、'{{ TPF_xxx }}'の形式でリスト化される。
・メニュー作成 -> メニュー作成項目情報 ->入力方式 でプルダウン選択を指定した場合、デフォルトで「Ansible共通:ファイル管理:ファイル埋込変数名」と「Ansible共通:ファイル管理:テンプレート埋込変数名」を選択できるようにする。
・それらを選択してメニュー作成を行うと作成したメニューの指定したカラムでは'{{ CPF_xxx }}'や'{{ TPF_xxx }}'で選択できる。
・代入値自動登録設定の対象とする。

案②
・メニュー作成 -> メニュー作成項目情報 ->入力方式 でプルダウン選択を指定した場合、デフォルトで「Ansible共通:ファイル管理:ファイル埋込変数名」と「Ansible共通:ファイル管理:テンプレート埋込変数名」を選択できるようにする。
・それらを選択してメニュー作成を行うと作成したメニューの指定したカラムではCPF_xxxやTPF_xxxで選択できる。
・代入値自動登録設定の対象とする。
・代入地自動登録設定に「変数化」というカラムを新設し、Null or 有効でプルダウン選択できる。
・有効の場合、そのパラメータは変数として代入値管理に送られる。
　つまり、バックヤードで変数として紐づく値を探す対象となる。

背景
SIテンプレートでファイル埋込変数名に'{{ }}'を付けてプルダウン選択させたいカラムがある。
つまり、具体値にファイル埋込変数を指定したい。
こういう使い方は過去でも何回かあった。
というわけで、メニュー作成機能に取り込みたい。

**Comment by ta-matsuo** [comment]
以下の案で実現する。
案③
【メニュー作成機能】
・ITAインストール時に、「メニュー項目作成情報」メニューの  「プルダウン選択」-「メニューグループ：メニュー：項目」に、ファイル管理とテンプレート管理の項目を選択可能にする。
　ただし、Ansibleドライバがインストールされていない場合は選択できないように表示させない。

【Ansibleドライバ】
・「代入値自動登録設定」で選択されたメニュー項目がファイル管理またはテンプレート管理のプルダウン項目の場合、値を「{{ 」と「 }}」で囲んで「代入値管理」に値を移す。
　判断は、プルダウン項目の元データがファイル管理またはテンプレート管理のテーブル名、カラム名であるかどうかで判断する。

**Comment by ta-matsuo** [comment]
【メニュー作成機能】の修正・払戻完了。
