### ISSUE TITLE
【ホストグループ】ホストグループ用メニューに登録したデータが、ホスト用メニューに展開されない

### ISSUE THREAD

**Issue by kazuya-domon** [exastro-suite/it-automation#1231]
# 現象
ホストグループ用メニューに登録したデータが、ホスト用メニューのほうに展開されないといったような動作が見られます。
ホストグループ用メニューを利用している場合、下記のような動作になるのではないでしょうか？

- 登録されているのが「ホスト」の場合、そのままホスト用メニューへ展開
- 登録されているのが「ホストグループ」の場合、ホストグループをホスト単位に分割してホスト用メニューへ展開

# 環境

OS：Red Hat Enterprise Linux 7
AP: Exastro IT Automation Version 1.4.0

# 実施手順

1. 機器一覧に登録
2. オペレーションの登録
3. ホストグループ用メニューへデータ登録
4. ホスト用メニュー確認

※ホストグループ管理は未設定

# 結果

ホスト用メニューに何も展開されていない。

# その他

ソースの中に10000件で処理を分岐している箇所が見受けられますが、その件数をオーバーした場合の挙動ではないかと思います。
ホストの登録件数に依らない処理となるべきではないでしょうか？

【該当ソース】
/exastro/ita-root/backyards/hostgroup/ky_hostgroup_split.php
/exastro/ita-root/libs/backyardlibs/hostgroup/ky_hostgroup_functions.php

**Comment by ta-matsuo** [comment]
ホストグループ用のパラメータシートは、ホストグループとホストの両方が選択できるようにしております。
ホストグループのIDを+10000してホストの情報とJOINして表示させているため、
ホスト（機器一覧メニュー）のIDが10000を超えたデータについては
ホストグループと判断されてうまくホスト用パラメータシートにデータが展開されないという事象となっておりました。

v1.8.0にて、加算する値を10000000に変更する修正をいたします。
【修正対象】
・VIEW
G_UQ_HOST_LIST
・ソース
ita_install_package/ITA/ita-contents/ita-root/backyards/hostgroup/ky_hostgroup_split.php
ita_install_package/ITA/ita-contents/ita-root/libs/backyardlibs/hostgroup/ky_hostgroup_functions.php
