### ISSUE TITLE
【メニュー作成】プルダウン選択で参照項目を選んだ際に項目番号が大きいとうまくloadtableに反映されない

### ISSUE THREAD

**Issue by kazuya-domon** [exastro-suite/it-automation#1249]
# 現象
メニュー作成でとある項目をプルダウン選択にしたときに、参照項目を指定したが、
(設定エラー)ID変換失敗(num)となった。

# 環境
OS：CentOS 7
AP: Exastro IT Automation Version 1.7.1

# 手順
1. シーケンス番号を600000に変更
2. メニュー作成
3. データ登録

# その他
シーケンス番号を600000に変更したので、それが悪いのかもしれない。
loadtableのIDColumnの該当箇所がKY_AUTO_COL_6000で切れていた。

**Comment by sinatommy** [comment]
v1.7.2にて修正済み。
[【メニュー作成】メニュー項目作成情報のIDが10000以上の項目が「参照項目」で正しく参照できない #1100](https://github.com/exastro-suite/it-automation/issues/1100)
