### ISSUE TITLE
【メニュー作成】リンクから紐づいている子メニューに遷移

### ISSUE THREAD

**Issue by a-koizumi** [exastro-suite/it-automation#127]
※Aメニューが親でBメニューが子供
(別タブでジャンプするとともにBメニューではAメニューの情報を使ってデフォルト絞込みをする)

**Comment by naoki-kondo** [comment]
メニュー作成時に設定した項目がリンクとなり、そのリンクを押下すると子メニューにドリルダウンする。別タブでジャンプする。子メニューは遷移元の親メニューの情報を元に絞り込みをする。

**Comment by ta-matsuo** [comment]
#950 に統合してクローズ。
