### ISSUE TITLE
マスク用カラムクラス作成

### ISSUE THREAD

**Issue by m-takahashi-if** [exastro-suite/it-automation#13]
マスクFunctionを作成。
また、更新時に空白ではなく、***で見せたい要件があるので、それをSIで追加できる仕組みでお願いしたい。

**Comment by ta-matsuo** [comment]
・Web上の表示は********とする。
・登録・更新時は入力すると・で表示されるようにする。
・DBには暗号もハッシュもせずにそのままの値で登録する。
・代入値自動登録の対象とする。

**Comment by ta-matsuo** [comment]
払戻完了。
