### ISSUE TITLE
【Ansible共通】グローバル変数での値なしを許容してほしい。

### ISSUE THREAD

**Issue by kazuya-domon** [exastro-suite/it-automation#1300]
■現状
Ansibleにて、グローバル変数に値があれば処理をするなどの分岐をしたい場合、現状だと値なしを指定したい場合、削除するしかないが、その場合グローバル変数が定義されていないとして、想定外エラーとなってしまう。
そのため半角スペースを入れるなどしているが、少しわかりにくい。

■希望
グローバル変数に値なしを許容するようにしてほしい

**Comment by enoman** [comment]
完了
