### ISSUE TITLE
【Ansible-Driver】Playbookからフィルタを利用した変数を読み込めるようにして欲しい

### ISSUE THREAD

**Issue by takum-yamada** [exastro-suite/it-automation#1301]
Ansible-LegacyのPlaybook素材から変数を刈り取る際、
フィルタを利用していると変数が変数名一覧に登録されない。
例) {{ VAR_some_list | unique }}

Playbookの幅を広げるため、これを読み込めるようにして欲しい。

**Comment by takum-yamada** [comment]
Ansible-LegacyのPlaybook素材から変数を刈り取る際、
フィルタを利用していると変数が変数名一覧に登録されない。
例) {{ VAR_some_list | unique }}

Playbookの幅を広げるため、これを読み込めるようにして欲しい。

**Comment by enoman** [comment]
Ansible-LegacyのPlaybook素材からフィルタを利用の変数(VAR_/GBL_TPF_/CPF_)を刈り取り可能にする。
Legacy
Playbookの記述
{{ VAR_xxx | xxxx }}     〇
{{ GBL_xxx | xxxx }}     〇
{{ TPF_xxx | xxxx }}     〇
{{ CPF_xxx | xxxx }}     〇

また、代入値管理具体値/グローバル変数の具体値での変数(TPF_/CPF)定義はこれまで通りとする。
{ TPF_xxx | xxxx }}     ×
{{ CPF_xxx | xxxx }}     ×

**Comment by enoman** [comment]
完了
