### ISSUE TITLE
【Terraform / Ansible】代入値自動登録が可能なパラメタシートの共通化

### ISSUE THREAD

**Issue by j-kumamoto** [exastro-suite/it-automation#1305]
Terraform用パラメタシート（ホストなし）は、Ansibleへの代入値自動登録不可のため、
共有のパラメータが存在してもパラメータシートを2つ作成する必要がある（逆も同じ）

Terraform←→Ansible間で代入値の連携が可能な共有のパラメタシートを作成して欲しい。

**Comment by sinatommy** [comment]
[【メニュー作成】ホストなしパラメータシートの値をホストありパラメータシートで引用できる機能 #211](https://github.com/exastro-suite/it-automation/issues/211)
と同件のためこちらはCLOSE
