### ISSUE TITLE
First time login issue "Login ID or Password is incorrect" .

### ISSUE THREAD

**Issue by Gaurav-sen1** [exastro-suite/it-automation#1306]
Hello,
I hope everyone is doing well.

I am new to Exastro, i am deploying it using the latest one package 1.7.2.
All the steps have been followed and able to open the Login Screen.
As the **"IT Automation online installation Manual"**, below credentials need to be used for the login

・Login ID ： administrator
・Initial password ： password

by entering it , "Login ID or Password is incorrect" error is shown. 
[ita_answers.txt](https://github.com/exastro-suite/it-automation/files/6764045/ita_answers.txt)

Kindly see the attached ita_answers.txt file and help me to get rid this issue.

Thanks and Regards
Gaurav

**Comment by j-kumamoto** [comment]
@Gaurav-sen1 

>・Login ID ： administrator
>・Initial password ： password

Hello.
The User ID and the Initial Password you got from the manual are correct and should work, 
so please try and log in again.

>Kindly see the attached ita_answers.txt file and help me to get rid this issue.

There are no problems with the Answer file (ita_answers.txt) as far as I can see.
Please note that the password input in this file is the MariaDB User password and not the Initial ITA Login Password.
In other words, the password written in the answer file is most likely not the reason why you are having issues logging in.
