### ISSUE TITLE
【Terraform】Terraformのメニューにおいてdestroyコマンド相当を実行できるようにしたい

### ISSUE THREAD

**Issue by sudodaisuke-jp** [exastro-suite/it-automation#1313]
Terraformのメニューにおいて、Organizationと、Workspaceの削除は可能だが、
Terraformにて作成したリモートオブジェクトの削除(destroyコマンド相当)をTerraform連携に追加して欲しい。
リソース削除にTerraformコマンドの実行や
TFCのページへのアクセスが発生するためITAで削除までできると便利だと思う。

**Comment by ayaka-shinomiya** [comment]
[仕様]
・Workspaces管理に[destroy]ボタン（仮名）を追加する。
