### ISSUE TITLE
【ホストグループ】ホスト紐付管理からホストグループ名を廃止しても代入値自動登録設定に不要な変数名がプルダウン表示される

### ISSUE THREAD

**Issue by a-koizumi** [exastro-suite/it-automation#133]
①ホストグループに紐づいたメニュー作成を行ない
そのあと、ホスト紐付管理からホストグループ名を廃止する。
代入値自動登録設定に不要な変数名がプルダウンに表示されます。

②「ホスト紐付管理」のデータを削除する。
「ホストグループ変数化」からは消えません。

**Comment by ta-matsuo** [comment]
払戻完了。
