### ISSUE TITLE
【RestAPI】FILTERの検索条件で任意入力項目でも完全一致を検索するオプションが欲しい

### ISSUE THREAD

**Issue by dai-kagino** [exastro-suite/it-automation#1333]
プルダウン項目については”LIST”で実現可能だが、任意入力項目では"NORMAL"（LIKE検索）しか無いように思われる

**Comment by ta-matsuo** [comment]
任意入力項目でもLIST検索は可能です。
例えば、「管理コンソール」-「システム設定」メニューの「識別ID」がIP_FILTERのデータをLIST検索する場合、
{"3":{"LIST":["IP_FILTER"]}}
と指定すれば検索可能です。

**Comment by dai-kagino** [comment]
なるほど、それだと "LIST" を使えば、完全一致検索みたいなこともできそうですね。
試してみたいと思います。
ありがとうございました。
