### ISSUE TITLE
【Ansible-driver】【DSC-driver】自動登録設定画面で登録方式：value型を指定した場合、 key変数もvalue変数も登録できる

### ISSUE THREAD

**Issue by a-koizumi** [exastro-suite/it-automation#134]
自動登録設定画面で登録方式：value型を指定した場合、
key変数もvalue変数も登録できてしまう。
（key型を指定した場合もkey変数もvalue変数も登録できる。）
※AnsibleLegacy、Ansible-Pioneer、AnsibleLegacyRole、DSC

**Comment by enoman** [comment]
完了
