### ISSUE TITLE
【メニュー作成】GUIによるメニュー作成機能

### ISSUE THREAD

**Issue by ta-matsuo** [exastro-suite/it-automation#135]

**Comment by naoki-kondo** [comment]
概要
メニュー作成に関する項目の登録・更新をGUI上での操作で完結するようにする。

仕様
 *新規登録の処理プロセスは既存と同じ(流用はしない。新規作成)
 *登録後は各メニューにされた状態にする。実行ステータスは未実行とする
 *「メニュー作成情報」に登録されている各レコードに更新ボタンを追加。押下するとGUIメニューに飛ぶ。
 *更新時はデータの主キーでDBを参照して同じIDがあれば更新する
