### ISSUE TITLE
【管理コンソール】パスワード有効期限が近づいた場合の通知機能

### ISSUE THREAD

**Issue by ojima-nobuya** [exastro-suite/it-automation#1350]
【要望】
パスワードの有効期限が近づいた際に、変更を促す通知機能を具備して頂きたい。

【実現したい機能案】
①ログオン時にポップアップ機能でパスワード変更を促すようにする。
　仕様案としましては、「OK」or「パスワード変更に進む」を選択できるようにしておき、
　「パスワード変更に進む」を選択すると、パスワード変更画面に移動する。
　
②「管理コンソール」⇒「ユーザ管理」にて登録したメールアドレスに対して
　パスワード変更を促すメールを送付する。

**Comment by ta-matsuo** [comment]
パスワード有効期限が切れてもログインできなくなるわけではなく、パスワード変更画面に遷移するだけなので本対応は実施しない。
