### ISSUE TITLE
【REST-API】Conductor作業実行までの一連の処理の簡易化

### ISSUE THREAD

**Issue by wakkysan** [exastro-suite/it-automation#1354]
現状、外部からパラメータを与えてConductor作業実行までの一連の処理をRESTで実行するには、以下のような処理を処理毎にRESTを送る機能を作る必要がある。そこを専用のI/Fを設けることで簡易化できないか。
要は、対象のメニューやそこに登録する情報、利用するConductor情報等必要な情報をおくれば、実行結果が得られるI/Fだと外部連携が楽になる。
・オペレーション新規払い出し
・パラメータシートへデータ登録
・代入値管理、作業対象ホストにデータ登録されているか確認
・Conductor作業実行
・実行ステータス取得
・実行結果(InputData.zip、ResultData.zip)の取得

**Comment by sinatommy** [comment]
「knowledges」リポジトリにて管理。
[【REST-API】Conductor作業実行までの一連の処理の簡易化 #2](https://github.com/exastro-suite/knowledges/issues/2)
