### ISSUE TITLE
【インストーラ】YAML解析のライブラリ変更

### ISSUE THREAD

**Issue by ta-matsuo** [exastro-suite/it-automation#136]
YAML解析のライブラリをSpycからyaml拡張ライブラリに変更する。
Spycは不要になるため、インストールから削除する。

①以下のコマンドでライブラリをインストールする。
　　yum  install libyaml
　　yum  install libyaml-devel
　　yum  install php-devel
　　pecl channel-update pecl.php.net
　　pecl install YAML

②php.iniに以下を追記する。
extension=yaml.so

**Comment by h-matsuhashi** [comment]
修正作業自体は完了。
現在、ライセンス部分で確認中。
