### ISSUE TITLE
【CI/CD for IaC】GitのクローンをSSHで実施できるようにする

### ISSUE THREAD

**Issue by ta-matsuo** [exastro-suite/it-automation#1367]

**Comment by enoman** [comment]
![image](https://user-images.githubusercontent.com/49501380/137234143-eea7a743-627a-4c47-9d22-22e9c6501a65.png)

**Comment by enoman** [comment]
リモートリポジトリメニューにssh接続時パラメータ「core.sshCommand」に対応する項目追加

**Comment by enoman** [comment]
完了
