### ISSUE TITLE
【メニュー作成】マルチカラムの代入値自動登録連携

### ISSUE THREAD

**Issue by ta-matsuo** [exastro-suite/it-automation#138]
マルチカラム（文字列(複数行)）を代入値自動登録設定の対象にする。
メニュー作成機能に以下の修正を行う。

①文字列(複数行)の場合にも、紐付対象メニューカラム管理（B_CMDB_MENU_COLUMN）にレコードを登録する。

②紐付対象メニューカラム管理（B_CMDB_MENU_COLUMN）にカラム（COL_CLASS）が追加になっているので、以下の通りに値を設定する。
・文字列(単一行)・・・TextColumn
・文字列(複数行)・・・MultiTextColumn
・整数・・・NumColumn
・小数・・・NumColumn
・プルダウン選択－文字列(単一行)・・・TextColumn
・プルダウン選択－文字列(複数行)・・・MultiTextColumn
・プルダウン選択－整数・・・NumColumn
・プルダウン選択－小数・・・NumColumn

**Comment by t-yaocheng** [comment]
払戻しました。
