### ISSUE TITLE
「代入値自動登録設定」「Movement詳細」等のドライバを横断した一覧表示機能

### ISSUE THREAD

**Issue by UemuraMasumi** [exastro-suite/it-automation#139]
【質問内容】
ExastroITAには、Ansible 以外に利用できるドライバが色々あると思いますが、それらのドライバを横断的に「このメニューはこのDriverにデータを渡してる」みたいなことが確認できるGUIはあるでしょうか？

【回答】
Ansibleだけなら、3モードぶんの代入値自動登録設定をマージして表示は実現の可能性あり。
いろいろなリレーションを、もっとGUI上から表現したい。
例えば、MovementとPlaybookの紐付って、Movement詳細でやっているのですが、それぞれから絞り込みかけれるようなGUIにしたい。

(※)「いかにして疎を保ちながら、実現するか」は考慮の必要あり。

**Comment by ta-matsuo** [comment]
各ドライバーでメニューの項目数などが異なるため、ひとつのメニューで表示することはできない。
クローズ。
