### ISSUE TITLE
Pioneer実行結果ファイルのターゲットホスト名ディレクトリ追加

### ISSUE THREAD

**Issue by m-takahashi-if** [exastro-suite/it-automation#14]
Pioneerのstateモジュールを利用してコマンドの実行結果をResultData.zipのuser_files内に持って帰ってくることができる。
その際、Legacyと同じようにuser_files配下にターゲットホスト名のディレクトリを設けたい。
例えば、"exec_list:"の前に以下のようにコマンドを記載できるlocalactionカテゴリを設けるのはどうか。

```
localaction:
  command: mkdir  -p 755 {{ __workflowdir__ }}/{{ __loginhostname__ }}
```

→ローカルアクションできればいい。

**Comment by sinatommy** [comment]
以下の構文にしたいと思います。
構文
- localaction:  mkdir /tmp/hoge
  ignore_errors: yes/no
                 結果が異常でも次に進む場合に「yes」を指定
                「no」の場合は、異常の場合に対話ファイルを異常終了
                 省略時は「no」
