### ISSUE TITLE
【Ansible-Driver】「OS種別マスタ」メニューのメニューグループ変更

### ISSUE THREAD

**Issue by ta-matsuo** [exastro-suite/it-automation#142]
「基本コンソール」メニューグループにある「OS種別マスタ」メニューを、「Ansible-Pioneer」メニューグループに移動する。
 「対話種別リスト」メニューと「対話ファイル素材集」メニューの間に移動する。

**Comment by enoman** [comment]
完了

**Comment by enoman** [comment]
完了
