### ISSUE TITLE
【エクスポート/インポート】実行する度に不要なログが表示される

### ISSUE THREAD

**Issue by a-koizumi** [exastro-suite/it-automation#1421]
【エクスポート/インポート】

・メニューエクスポート
・メニューインポート
・Excel一括エクスポート
・Excel一括インポート

上記操作をする度に都度
「webaplogs」に以下内容が表示されている。
出さないように対応する。

  "ERROR:UNEXPECTED, DETAIL:REFERER(https://exastro-xx-automation.io/menus/systems/2100000211/03_data_export.php?no=2100000211) NG END."

**Comment by ayaka-shinomiya** [comment]
[対応]
エラーログが出なくなりました。

**Comment by ayaka-shinomiya** [comment]
メインメニューにアクセスするたびに/var/log/httpd/exastro-it-automation-error_logにエラーメッセージが表示される事象を修正
