### ISSUE TITLE
【管理コンソール】とあるユーザでログインすると不要なログがwebaplogsに出力される場合がある

### ISSUE THREAD

**Issue by a-koizumi** [exastro-suite/it-automation#1432]
以下のログが～/ita-root/logs/webaplogs/webap_YYYYMMDDlogに出力される。

"2021/07/29 17:13:52" "10.180.81.204" "" "" "" "" "" "" "10.180.81.204" "POST" "exastro-xxx-automation.io"
"/common/common_auth.php" "grp=2100000002&no=" "" "RESULT:SUCCESS"
"2021/07/29 17:13:54" "10.180.81.204" "" "" "" "" "" "" "10.180.81.204" "GET" "exastro-xxx-automation.io"
"/common/common_auth.php" "login&grp=2100000002&no=" "" "RESULT:SUCCESS"
"2021/07/29 17:13:56" "10.180.81.204" "" "" "" "" "" "" "10.180.81.204" "GET" "exastro-xxx-automation.io"
"/common/common_sso_auth.php" "oauth2&providerId=1&grp=2100000002&no=" "" "RESULT:SUCCESS"
"2021/07/29 17:14:01" "10.180.81.204" "" "" "" "" "" "" "10.180.81.204" "GET" "exastro-xxx-automation.io" "/common/common_sso_auth.php" "oauth2&callback&state=9f7bebfe93f6237350fc03275cbfcfd29051d764d5618021d74b2c7c7534ca4c&code=mjlEy2xf" "" "WARNING: COULD NOT GET PROVIDER_USER_NAME [username]xxxxxxxx_xxxxxxx@xxxxx.co.jp,[FILE]/exastro/ita-root/libs/webcommonlibs/web_functions_for_sso_auth.php,[FUNCTION]autoRegistUser,[LINE]145"
"2021/07/29 17:14:01" "10.180.81.204" "" "" "" "" "" "" "10.180.81.204" "GET" "exastro-xxx-automation.io"
"/common/common_sso_auth.php" "oauth2&callback&state=9f7bebfe93f6237350fc03275cbfcfd29051d764d5618021d74b2c7c7534ca4c&code=mjlEy2xf" ""
"RESULT:SUCCESS"
"2021/07/29 17:14:02" "10.180.81.204" "" "" "" "" "" "" "10.180.81.204" "GET" "exastro-xxx-automation.io"
"/default/mainmenu/01_browse.php" "grp=2100000002" "xxxxxxxx_xxxxxxx@xxxxx.co.jp" "RESULT:SUCCESS"
"2021/07/29 17:14:04" "10.180.81.204" "" "" "" "" "" "" "10.180.81.204" "POST" "exastro-xxx-automation.io" "/common/common_auth.php" "grp=2100000002&no=" "" "RESULT:SUCCESS"
"2021/07/29 17:14:09" "10.180.81.204" "" "" "" "" "" "" "10.180.81.204" "GET" "exastro-xxx-automation.io" "/common/common_auth.php" "login&grp=2100000002&no=" "" "RESULT:SUCCESS"
"2021/07/29 17:14:12" "10.180.81.204" "" "" "" "" "" "" "10.180.81.204" "GET" "exastro-xxx-automation.io" "/common/common_sso_auth.php" "oauth2&providerId=2&grp=2100000002&no=" "" "RESULT:SUCCESS"

**Comment by a-koizumi** [comment]
上記Logにワーニングが出る起因は
SSOの初回ログイン時となる。

**Comment by sinatommy** [comment]
確認したところ問題ないためCLOSE
