### ISSUE TITLE
【Ansible-Driver】Pionner 対話ファイルの文字コード判定

### ISSUE THREAD

**Issue by enoman** [exastro-suite/it-automation#144]
UTF-8以外の文字コードを含む対話ファイルを登録し実行すると想定外エラーではなく実行時にエラーとなる。
対話ファイル登録時に文字コードを判定。UTF-8以外の文字コードが使用されている場合、登録時にエラーにする。

**Comment by enoman** [comment]
完了

**Comment by a-koizumi** [comment]
確認事項
================================================================

プレイブック

Legacyで変数定義のあるplaybook(UTF8BOMあり
　⇒ステータス：完了

Legacyで変数定義のあるplaybook(全角ありのUTF8以外のコード)
　⇒ステータス：完了(異常)
エラー内容：
ERROR! Syntax Error while loading YAML.

================================================================

ロールパッケージファイル
   

Roleでdefault_UTF8BOMあり
　⇒「更新」ボタン押下時、バリデーションエラーです。「変数の記述が不正です。(ロールパッケージ名: ロール:test1 file:main.yml line:1)(2101)」



Roleでdefault_全角ありのUTF8以外
　⇒ステータス：完了(異常)　「ERROR! Syntax Error while loading YAML.」



Roleでtasks_UTF8BOMあり
　⇒ステータス：完了

 

tasks_全角ありのUTF8以外
　⇒ステータス：完了(異常)　「ERROR! Syntax Error while loading YAML.」

================================================================

対話ファイル

UTF-8BOMのチェック付き
　⇒想定外エラー

エラー内容： 

対話ファイルの構文が不正です。(host:10.197.19.208 対話ファイル:0000000002-UTF-8(BOM付き.yml line:1)
対話ファイルのconfパラメータが正しく記述がされていません。(host:10.197.19.208 対話ファイル:0000000002-UTF-8(BOM付き.yml)



UTF-8以外の文字コード
 ⇒「事前アップロード」ボタンを押下時エラー

================================================================

その他


テンプレート管理でテンプレート素材(UTF8_BOM付き)
　⇒ステータス：完了（Legacy）
　⇒ステータス：完了（LegacyRole）

 

テンプレート管理でテンプレート素材(全角ありのUTF8以外のコード)
　⇒ステータス：完了（Legacy）
　⇒ステータス：完了（LegacyRole）

**Comment by enoman** [comment]
「ERROR! Syntax Error while loading YAML.」
の原因について、ansibleサポートにLANG等に依存するか確認したところ
以下の回答をもらいました。
UTF-8以外でのマルチバイト文字の取り扱いについては、Ansibleの開発コミュニティでの十分なテストが行われていない状況です。お客様が他のコードを確認して問題なければお客様の判断でご利用いただければと思いますが、問題発生時にはアップストリーム側への報告と対応を待つ必要がございます。
このような文字コードのハンドリングに関する調査や修正は、Ansibleのエンジン部分だけでなく、その下位でライブラリとして利用しているJinja側での対応が必要となる可能性もございます。調査や修正に非常に時間がかかるケースが多い点を考慮して、、playbook は UTF-8 で記述していただくことを強くお勧めいたします。

「対話ファイルの構文が不正です。」
の原因は使用しているYAMLパーサーでUTF-8以外の文字コードがあるとエラーになり、その場合のエラーメッセージです。

上記のことから、
Legacy/Pioneer/Role/テンプレート管理(変数定義)の事前アップロード時に以下チェックを入れます。
UTF-8以外の文字コードの使用チェック
BOM付ファイルのチェック

**Comment by enoman** [comment]
以下の様に変更します。
Legacy:
プレイブック素材集でファイルアップロード時に、アップロードファイルの文字コードがUTF-8(BOMなし)かAscii以外の場合はエラーとします。
Role:
ロールパッケージ管理でロールパッケージアップロード時、ロールパッケージ内の下記ファイルについて文字コードがUTF-8(BOMなし)かAscii以外の場合はエラーとします。
読替表
ITAReadme
tasks/配下のファイル
defaults/配下のファイル
handlers/配下のファイル
meta/配下のファイル
vars/配下のファイル

**Comment by enoman** [comment]
以下の様に変更します。
Legacy:
プレイブック素材集でファイルアップロード時に、アップロードファイルの文字コードがUTF-8(BOMなし)かAscii以外の場合はエラーとします。
Role:
ロールパッケージ管理でロールパッケージアップロード時、ロールパッケージ内の下記ファイルについて文字コードがUTF-8(BOMなし)かAscii以外の場合はエラーとします。
読替表
ITAReadme
tasks/配下のファイル
defaults/配下のファイル
handlers/配下のファイル
meta/配下のファイル
vars/配下のファイル

**Comment by enoman** [comment]
完了
