### ISSUE TITLE
【全般】ログイン後画面の制御

### ISSUE THREAD

**Issue by sinatommy** [exastro-suite/it-automation#146]
ログイン後の画面がユーザに関係なく最終アクセス画面になるので、閲覧権限のないユーザの場合エラーになってしまう。

**Comment by ayaka-shinomiya** [comment]
アクセスしたページの閲覧権限を持っていない場合、現在の白いエラー画面ではなく別のページにリダイレクトさせる。
リダイレクト先にはユーザの保持するアクセス権限のメニューグループのパネルのみが存在するメインメニューっぽいページにする。（あくまでURLはメインメニューとは別）

**Comment by ayaka-shinomiya** [comment]
表示できるメニューグループのないユーザに関しては現状の仕様のまま

**Comment by ayaka-shinomiya** [comment]
[変更点]
・メインメニューのような別URLではなく、ダッシュボードにリダイレクトする

**Comment by ayaka-shinomiya** [comment]
grp以降の値はなしとする
