### ISSUE TITLE
【エクスポート/インポート】Excel一括インポートのログが止まる場合がある

### ISSUE THREAD

**Issue by a-koizumi** [exastro-suite/it-automation#1461]
【事象】
①全てのメニューでExcel一括エクスポートする。
②①でエクスポートしたデータをExcel一括インポートする。
　⇒Excel一括エクスポート・インポート管理の「結果」ResultData_xx.logを確認する。
　　管理コンソールと基本コンソールのログしか出力されない。
　　（※単品でエクスポートしたものをインポート時はOKです。全てのメニューのときのみの事象です）

**Comment by ayaka-shinomiya** [comment]
[修正点]
【Excel一括エクスポート】
・同名ファイルの出力を防ぐため、ファイル名がずれる処理を入れる。

【Excel一括インポート】
・別ディレクトリ・同名ファイルが存在する場合、該当ファイル全てエラーにする
・一括読込途中、エラーがあった場合にログの出力が停止される問題を修正
・実行中の履歴が二回出力される問題を修正
・ステータスが完了になるタイミングが早すぎる問題を修正
・ログのURLの登録を実行中に行わないように修正
