### ISSUE TITLE
【代入値自動登録設定】エクスポートを実行すると代入値自動登録全般のパラメータシートの項目がID変換失敗で表示される

### ISSUE THREAD

**Issue by sudodaisuke-jp** [exastro-suite/it-automation#1464]
「代入値自動登録設定」のパラメータシート(From)の項目に、
プルダウン選択で登録した機器一覧のホスト名が登録している状態でエクスポートを実行し、
再度代入値自動登録設定を確認してみるとID変換失敗に変わってしまう。
また該当の項目を更新しようとすると機器一覧のホスト名が選択できない。
代入値自動登録全般で発生している。

【再現手順例】
①メニュー作成より下記のメニューを作成する。
　◆項目
　　・プルダウン選択
　　・基本コンソール：機器一覧：ホスト名
　◆作成対象
　　・パラメータシート(オペレーションあり)　　
②「Terraform」-「代入値自動登録設定」より先ほど作成したメニュー項目を登録する。
③「エクスポート/インポート」-「メニューエクスポート」より下記指定でエクスポートする。
　モード：時刻指定　2021/04/01　00:00:00
　廃止情報：廃止を除く
　すべてのメニュー
④「Terraform」-「代入値自動登録設定」を確認する

**Comment by HibikiNanri** [comment]
■原因
メニューエクスポートなどを実行すると、バックヤード処理「ky_cmdbmenuanalysis-workflow」が実行され、
代入値自動登録で使う値を管理するメニュー（[基本コンソール]>[紐付対象メニューカラム管理]）のデータを際チェックします。
このバックヤード処理で、loadTable上でLinkIDColumnを使っている項目が代入値自動登録の対象となるようになっていませんでした。

#950 
上記issueの対応にて、メニュー作成で「プルダウン選択」の項目をIDColumnからLinkIDColumnを使うように修正をしています。
このため、バックヤード処理「ky_cmdbmenuanalysis-workflow」が実行されると代入値自動登録で利用できない項目となってしまう状態でした。

■修正
LinkIDColumnもIDColumnと同様の処理がされるように修正します。

**Comment by ta-matsuo** [comment]
メニューエクスポート時にはA_PROC_LOADED_LISTで管理しているバックヤード処理を実行しないようにする。
メニューインポート時には今まで通り実行する。

**Comment by HibikiNanri** [comment]
ky_cmdbmenuanalysis-workflowで参照元のクラスを取得するの処理について、
参照テーブルが「D_MENU_LINK」、参照カラムが「MENU_PULLDOWN」の場合に、例外処理として「TextColumn」を返す処理を追加。
本来はloadTableからクラスの情報を取得するが、MENU_PULLDOWNカラムはloadTable側で利用がないため、情報を取得できない。

メニュー作成の「プルダウン選択」で「管理コンソール:メニュー管理:メニュー名称」を選択した場合が上記に該当。
