### ISSUE TITLE
【メニュー作成】縦型作成時に繰り返すカラムを自動適用としてほしい

### ISSUE THREAD

**Issue by wakkysan** [exastro-suite/it-automation#147]
縦型で作成するカラムに関しては、所定のカラムを繰り返し登録する必要がある。
例えば、「項目」「値」「デフォルト値」という３つを表示させ、繰り返し数が3の場合、
メニュー項目作成情報に、「項目」「値」「デフォルト値」「項目2」「値2」「デフォルト値2」「項目3」「値3」「デフォルト値3」と入力するため、手間がかかる。

なので、以下のように変更するのはいかがか。
メニュー作成時にメニュー(縦)作成情報の繰り返し数から自動的に末尾に番号を付与した形でメニュー項目作成情報にデータ登録する仕組みをメニュー作成機能に差し込む。

**Comment by sinatommy** [comment]
【メニュー作成】GUIによるメニュー作成機能 #135
にて対応
