### ISSUE TITLE
【メニュー作成】メッセージ見直し

### ISSUE THREAD

**Issue by wakkysan** [exastro-suite/it-automation#148]
縦型の項目数に対してマッピングした項目の繰り返しが不一致の場合、
以下のメッセージが出力されるが、もう少し伝わる表現に変更できないか。

縦メニュー作成情報の設定による繰り返し項目で、最大バイト数が一致しません。

**Comment by wakkysan** [comment]
メニュー(縦)作成情報と項目数/繰り返し数がメニュー項目作成情報と不整合です。

へ変更してください。

**Comment by t-yaocheng** [comment]
払戻しました。
