### ISSUE TITLE
【インストーラ】AnsibleDriverインストール時のNetcatコマンド追加 (sshプロキシ対応)

### ISSUE THREAD

**Issue by j-kumamoto** [exastro-suite/it-automation#150]
プロキシ環境下のITAからAWS上などの対外サーバにプロキシサーバ経由でSSH接続しAnsible Playbook実行する際のSSHコマンドオプションに「nc（netcat）」コマンドが必要。
「yum install -y nc」

インストーラーにてAnsibleDriverをインストールする際に、ncコマンドを追加したい

【参考】ncコマンド使用例
●プロキシ経由のSSH接続時にITA機器一覧のansible接続オプションに以下を追加

-o ProxyCommand='nc --proxy [プロキシサーバドメイン名:ポート番号] %h %p' -o 'StrictHostKeyChecking=no'

**Comment by h-matsuhashi** [comment]
払戻完了。
マニュアル修正の必要あり。
