### ISSUE TITLE
【インストーラ】Apache vhost設定値変更

### ISSUE THREAD

**Issue by j-kumamoto** [exastro-suite/it-automation#151]
Apache vhost設定値を変更する

**Comment by j-kumamoto** [comment]
調査・見直し後にインストーラへの組み込み依頼を行う

**Comment by j-kumamoto** [comment]
以下の修正を適用する。

(1) <VirtualHost *:443 >に「ServerAlias  *」の追加
 HTTPSでIP指定で接続可能をデフォルトとする

<VirtualHost *:443 >
    ServerName   exastro-it-automation
★  ServerAlias  *　　　　←追加
    DocumentRoot /exastro/ita-root/webroot


(2) <VirtualHost *:443 >の「SSLProtocol」「SSLCipherSuite 」の削除
　「/etc/httpd/conf.d/ssl.conf」のデフォルト値が有効になっており、
　vhostファイルの指定値は継承されていないため削除する。

(3)Apache2.4以上バージョン指定の削除
　<VirtualHost *:443 ><VirtualHost *:80 >の両方で以下を削除。
　
　    <IfVersion >= 2.4>
        <Location / >
            Require all granted
        </Location>
    </IfVersion>
↓↓
    <Location / >
         Require all granted
    </Location>

**Comment by j-kumamoto** [comment]
@h-matsuhashi に修正内容と資材を提供済。

**Comment by h-matsuhashi** [comment]
払戻完了。
ドキュメント修正あり
＜インストールマニュアル(オンライン/オフライン/HA構成)：HTTPSでのURL接続確認＞
