### ISSUE TITLE
【CI/CD for IaC】 GitHubのパスワード認証廃止について

### ISSUE THREAD

**Issue by y-masaya3210** [exastro-suite/it-automation#1511]
GitHubで2021年8月13日以降パスワード認証が廃止されました。
そのためリモートリポジトリの登録でVisibilityタイプをprivateにした際、Gitアカウント情報のパスワードへ自身で作成した個人アクセストークンの入力が必須となりました。

個人アクセストークン作成方法↓
https://docs.github.com/ja/github/authenticating-to-github/keeping-your-account-and-data-secure/creating-a-personal-access-token

●対応案
①項目名か説明に、アクセストークンも対応していることを明記する
②ドキュメントにアクセストークン対応の説明を追加
③FAQにアクセストークンの補足を掲載

**Comment by enoman** [comment]
Gitアカウント情報のパスワードのポップの内容を下記内容に変更し、利用手順マニュアルにも同等の追記をします。
=================ポップの内容======================
Gitのcloneコマンドを実行した際に求められるパスワードを入力してください。
VisibilityタイプでPrivateを選択した場合、パスワードの入力は必須です。
[最大長] 128バイト";
尚、GitHubでは2021年8月13日でパスワード認証が廃止されます。
https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/
パスワード認証が廃止されているGitHubを利用している場合、Gitアカウント情報のパスワードには、自身で個人アクセストークンを作成し入力して下さい。
個人アクセストークン作成方法
https://docs.github.com/ja/github/authenticating-to-github/keeping-your-account-and-data-secure/creating-a-personal-access-token
================================================

**Comment by enoman** [comment]
完了
