### ISSUE TITLE
【インストーラ】PHPセッションID保存先の修正

### ISSUE THREAD

**Issue by sinatommy** [exastro-suite/it-automation#152]
RHEL8/CentOS8のphpのセッションID作成ディレクトリの設定が、絶対パスになっていて、ITAインストールディレクトリを「/」以外にした場合エラーになる。

ita_install_package/ext_files_for_CentOS8.x/etc_php-fpm.d/www.conf
　php_value[session.save_path]    = /exastro/ita_sessions

**Comment by h-matsuhashi** [comment]
払戻完了
