### ISSUE TITLE
【Ansible-Driver】Movement実行時のプロセス確認周期変更

### ISSUE THREAD

**Issue by ta-matsuo** [exastro-suite/it-automation#1541]
Movement実行時のプロセス確認周期を以下のように変更する。
現状　：確認回数3回、確認周期5マイクロ秒
変更後：確認回数3回、確認周期1回目50000マイクロ秒（=50ミリ秒）、2回目100000マイクロ秒（=100ミリ秒）

**Comment by enoman** [comment]
完了
