### ISSUE TITLE
【ITAコンテナ化／インストーラ】sudo / crontabコマンドが必須

### ISSUE THREAD

**Issue by j-kumamoto** [exastro-suite/it-automation#157]
コンテナ用のcentos7イメージにsudoコマンドがインストールされておらず、sudoコマンドを使ったインストーラ作業  (hosts変更)や、playbook実行がエラーとなる。

コンテナイメージ上で、現状のITAとインストーラを動作させるためにはsudoが必須であるので、BASEのインストールパッケージにsudoの追加が必要
インストーラはroot権限で実行することが前提となっているので、シェルスクリプトにおいてsudoコマンドを使っている場合は削除する。
関連issue: #158 

【追記_20200617】
上記と同様にcrontabsがインストールされていないため、以下の実行プログラムのcrontab登録に失敗する。
現バージョンにおいて必須コマンドであるため、BASEのインストールパッケージに「crontabs」を追加する。

01 00 * * * su - -c /xxx/ita-root/backyards/common/ky_execinstance_dataautoclean-workflow.sh'
02 00 * * * su - -c /xxx/ita-root/backyards/common/ky_file_autoclean-workflow.sh'

**Comment by j-kumamoto** [comment]
@h-matsuhashi 
本issueに以下の問題の対応も追加しました。
【追記_20200617】
上記と同様にcrontabsがインストールされていないため、以下の実行プログラムのcrontab登録に失敗する。現バージョンにおいて必須コマンドであるため、BASEのインストールパッケージに「crontabs」を追加する。

01 00 * * * su - -c /（ITAインストール先ディレクトリ）/ita-root/backyards/common/ky_execinstance_dataautoclean-workflow.sh'02 00 * * * su - -c /（ITAインストール先ディレクトリ）/ita-root/backyards/common/ky_file_autoclean-workflow.sh'

**Comment by h-matsuhashi** [comment]
払戻完了。
ドキュメントの修正が必要。
