### ISSUE TITLE
【Terraform-driver】InputData.zipにTerraform Variablesを取得してほしい

### ISSUE THREAD

**Issue by wakkysan** [exastro-suite/it-automation#1581]

**Comment by HibikiNanri** [comment]
InputData_00000000XX.zip
の中の「variables」フォルダ配下に「variables.json」というファイルを格納します。

Terraformに登録した変数について、
・key
・value
・HCL
・Sensitive
のそれぞれの値を格納します。
※Sensitive設定がON(true)の場合、valueにはnullが入ります。

Terraform側に登録されている変数と、取得するjsonのイメージは以下の通りです。
![tfe_variable](https://user-images.githubusercontent.com/51319083/140455605-4810221f-ddbd-44d2-9c50-a42e79062962.png)
![json](https://user-images.githubusercontent.com/51319083/140455616-77de24fc-21e2-407e-b121-7a99191b761d.png)

**Comment by HibikiNanri** [comment]
マージ済み。
要ドキュメント修正。
