### ISSUE TITLE
【Ansible-Driver】Ansible Automation Controllerの動作確認

### ISSUE THREAD

**Issue by ta-matsuo** [exastro-suite/it-automation#1582]

**Comment by enoman** [comment]
Ansible Automation Controller4.0に対応に伴う課題
NFSへのアクセスがサポート対象外となった。
virtualenvがなくなり実行環境に置き換わった。
Isolatedノード機能が削除された。

**Comment by ta-matsuo** [comment]
【インストーラの修正】
ansible_driverがyesの場合、以下の処理を行う
・gitをインストールする。
・以下のディレクトリを作成して777の権限を付ける。
　～/ita-root/uploadfiles/2100040702
　～/ita-root/uploadfiles/2100040702/ANS_GIT_SSH_KEY_FILE
　～/ita-root/uploadfiles/2100040702/ANS_GIT_SSH_KEY_FILE/0000000001
　～/ita-root/uploadfiles/2100040702/ANS_GIT_SSH_KEY_FILE/0000000001/old
　～/ita-root/uploadfiles/2100040702/ANS_GIT_SSH_KEY_FILE/0000000001/old/0000000001
・awxユーザを作成する。
・awxユーザの公開鍵（rsa_awx_key.pub）と秘密鍵（rsa_awx_key）を作成して/home/awx/.sshに配置。
　秘密鍵を以下のディレクトリにも配置する。
　/ita-root/uploadfiles/2100040702/ANS_GIT_SSH_KEY_FILE/0000000001
　/ita-root/uploadfiles/2100040702/ANS_GIT_SSH_KEY_FILE/0000000001/old/0000000001
・公開鍵の内容を/home/awx/.ssh/authorized_keysに追記。
