### ISSUE TITLE
【ITAコンテナ化／インストーラ】コンテナ用スクリプトの対応

### ISSUE THREAD

**Issue by j-kumamoto** [exastro-suite/it-automation#159]
DockerfileからITAインストーラを起動し、オールインワン構成のコンテナイメージを作成すると、
「systemctl」コマンドが利用できないため、MariaDBなどの各サービスが起動できずインストールがエラーとなってしまう。

コンテナ実装（Dockerfile）用に「systemctl」コマンドを利用しないコンテナ用のシェルの実装を希望。「systemctl」コマンド仕様を確認する。

●改修案
アンサーファイル：ita_answers.txtにdockerインストールオプションを追加し、
必要に応じてコンテナインストール用に分岐して実行する。

●想定の修正対象（～/ita_install_package/install_scripts）
ita_answers.txt
bin/install.sh
bin/ita_builder_core.sh
bin/register-services_RHEL.sh
bin/uninstall.sh

**Comment by j-kumamoto** [comment]
「systemctl」のgrep結果

bin/install.sh:                RES=`systemctl | grep "$service" | grep 'running'`
bin/install.sh:    systemctl restart httpd 2>> "$LOG_FILE" | tee -a "$LOG_FILE"
bin/install.sh:    systemctl status httpd 2>&1 >> "$LOG_FILE"
bin/ita_builder_core.sh:    systemctl stop firewalld >> "$ITA_BUILDER_LOG_FILE" 2>&1
bin/ita_builder_core.sh:    systemctl disable firewalld >> "$ITA_BUILDER_LOG_FILE" 2>&1
bin/ita_builder_core.sh:            systemctl enable mariadb >> "$ITA_BUILDER_LOG_FILE" 2>&1
bin/ita_builder_core.sh:            systemctl start mariadb >> "$ITA_BUILDER_LOG_FILE" 2>&1
bin/ita_builder_core.sh:                systemctl restart mariadb >> "$ITA_BUILDER_LOG_FILE" 2>&1
bin/ita_builder_core.sh:            systemctl enable mariadb >> "$ITA_BUILDER_LOG_FILE" 2>&1
bin/ita_builder_core.sh:            systemctl start mariadb >> "$ITA_BUILDER_LOG_FILE" 2>&1
bin/ita_builder_core.sh:            systemctl restart mariadb >> "$ITA_BUILDER_LOG_FILE" 2>&1
bin/ita_builder_core.sh:            systemctl enable mariadb >> "$ITA_BUILDER_LOG_FILE" 2>&1
bin/ita_builder_core.sh:            systemctl start mariadb >> "$ITA_BUILDER_LOG_FILE" 2>&1
bin/ita_builder_core.sh:                systemctl restart mariadb >> "$ITA_BUILDER_LOG_FILE" 2>&1
bin/ita_builder_core.sh:            systemctl enable mariadb >> "$ITA_BUILDER_LOG_FILE" 2>&1
bin/ita_builder_core.sh:            systemctl start mariadb >> "$ITA_BUILDER_LOG_FILE" 2>&1
bin/ita_builder_core.sh:            systemctl restart mariadb >> "$ITA_BUILDER_LOG_FILE" 2>&1
bin/ita_builder_core.sh:    systemctl enable httpd >> "$ITA_BUILDER_LOG_FILE" 2>&1
bin/register-services_RHEL.sh:systemctl daemon-reload
bin/register-services_RHEL.sh:        systemctl enable `basename ${line}`.service
bin/register-services_RHEL.sh:        systemctl start `basename ${line}`.service
bin/uninstall.sh:systemctl stop httpd.service 2>> "$LOG_FILE"
bin/uninstall.sh:APACHE_ACTIVE=`systemctl status httpd | grep "dead"`
bin/uninstall.sh:            systemctl stop "$FILE_NAME"; 2>> "$LOG_FILE"
bin/uninstall.sh:            BACKYARD_ACTIVE=`systemctl status "$FILE_NAME" | grep "running"`
bin/uninstall.sh:            systemctl disable "$FILE_NAME"; 2>> "$LOG_FILE"
bin/uninstall.sh:            STARTUP_SET=`systemctl is-enabled "$FILE_NAME"`
bin/uninstall.sh:    systemctl daemon-reload 2>> "$LOG_FILE"

**Comment by sinatommy** [comment]
対応なし
