### ISSUE TITLE
メインメニュー表示バグ

### ISSUE THREAD

**Issue by m-takahashi-if** [exastro-suite/it-automation#16]
メインメニュー表示時に、画面左のメインメニューが他のメニューの強調色と違う。

**Comment by m-takahashi-if** [comment]
2019/12/20 加藤
web_parts_for_browse_01.phpの修正が必要だと思います。
●メインメニュー画面表示時にメニューのメインメニューにclass "menu-on"を付ける。 
●id "MENU00" が重複している。

**Comment by ta-matsuo** [comment]
v1.3.0でリリース済み。
