### ISSUE TITLE
【ITAコンテナ化】ITAの複数コンテナ同居におけるセッションCookie重複問題

### ISSUE THREAD

**Issue by j-kumamoto** [exastro-suite/it-automation#160]
ITAコンテナの複数起動・同時アクセスにおいてセッションの問題が発生する。

●問題の事象
1つのDockerサーバ上に、複数のITAコンテナを構築・起動した場合、
ポート番号を分けて各ITAに同時アクセスすることができるが、
片方のITAにログインすると、もう一方のITAからはログアウトさせられる。

現象としては、ドメイン名とセッションcookie名が重複しているので、
ブラウザが対応できなく、別のITAに最後に受けたcookieでアクセスしてしまう。
⇒　不正なセッションcookieを受けたITAは強制ログアウトを促す。

●解決案
①セッションcookie名を「ITA_SESSION」と固定にせず、重複しないIDを自動払い出ししcookie名に付加する。
②Webコンソールの管理メニュー等からセッションcookieの変更が可能な仕様にする
③ ユーザでhostsを変更する（複数ポートごとに同じIPのドメイン名を追加等）
上記のような改修の検討を希望。

【20200618追記】
⇒　ユーザの変更が不要な上記①の改修の方向で進める。

●修正対象
～/ita-root/libs/webcommonlibs/web_auth_config.phpの246行目
を以下のように修正し、動作確認する。

$objAuth->setSessionName('ITA_SESSION');
↓↓↓
$objAuth->setSessionName('ITA_SESSION_'.bin2hex($_SERVER['HTTP_HOST']));

**Comment by j-kumamoto** [comment]
固有のIDを付加する案の件、Docker内のコンテナにおいて、ポート番号は重複しますが、Docker内で自動で払い出すホスト名とIPアドレスは重複しないので、そのどちらか、または両方を使ってハッシュかけて使うなどの案も検討の余地あり。

**Comment by j-kumamoto** [comment]
ユーザの変更が不要な改修案①の方向で進める。

●修正対象
～/ita-root/libs/webcommonlibs/web_auth_config.phpの246行目
を以下のように修正し、動作確認を行う。

$objAuth->setSessionName('ITA_SESSION');
↓↓↓
$objAuth->setSessionName('ITA_SESSION_'.bin2hex($_SERVER['HTTP_HOST']));

**Comment by Saito-Masaru** [comment]
>$objAuth->setSessionName('ITA_SESSION_'.bin2hex($_SERVER['HTTP_HOST']));
この修正を払戻しました。

**Comment by Saito-Masaru** [comment]
> `$objAuth->setSessionName('ITA_SESSION_'.bin2hex($_SERVER['HTTP_HOST']));`
この修正ですが、下記のように再修正しました。
`$objAuth->setSessionName('ITA_SESSION_'.md5($_SERVER['HTTP_HOST']));`
ホスト名が非常に長い場合にセッションが正常に引き継げなくなる可能性があるので固定長のmd5に変更します。  
なお、この修正は既に払戻済みです。
