### ISSUE TITLE
【インストーラ】/etc/sudoers 設定方法の改善

### ISSUE THREAD

**Issue by j-kumamoto** [exastro-suite/it-automation#161]
インストール時のsudo設定について、インストーラーでの/etc/sudoersを上書きするのは問題がある。

上記方法を廃止し、部分的な追記か、sudoを/etc/sudoers.d/fileで許可する設定など、ユーザ環境への影響を最小にするような設定方法を検討をすべき。

**Comment by j-kumamoto** [comment]
参考URL
sudoを/etc/sudoers.d/fileで許可する設定
https://qiita.com/kkoito/items/f5242991c43b719ef2db

**Comment by j-kumamoto** [comment]
sudo初期設定について

●通常CentOS7/8の初期設定（共通）
CentOS7（CentOS-7-x86_64-GenericCloud-1810）
CentOS8（CentOS-8-GenericCloud-8.1.1911-20200113.3.x86_64)
----------------------------------------------------------------
①sudo インストール：済
②/etc/sudoers ディレクトリ：有り
③/etc/sudoers.d/ ディレクトリ：有り
④/etc/sudoers.d/ インクルード設定：なし（コメント）
（#includedir /etc/sudoers.d）

●通常CentOS7/8の初期設定（共通）
----------------------------------------------------------------
①sudo インストール：なし
②/etc/sudoers ディレクトリ：なし
③/etc/sudoers.d/ ディレクトリ：なし
④/etc/sudoers.d/ インクルード設定：なし
↓
※sudoインストール後の初期設定
①sudo インストール：済
②/etc/sudoers ディレクトリ：有り
③/etc/sudoers.d/ ディレクトリ：有り
④/etc/sudoers.d/ インクルード設定：なし（コメント）
（#includedir /etc/sudoers.d）

**Comment by h-matsuhashi** [comment]
sudoersファイルの一番下にある（#includedir /etc/sudoers.d）はコメントじゃないようです。
ちょうどその上のコメントに「この#はコメントじゃないよ  原文:(the # here does not mean a comment)」と書いてありました。
ですので、/etc/sudoers.d/に設定ファイルを置けば、/etc/sudoersを触らずにいけそうです。

**Comment by h-matsuhashi** [comment]
参考URL
/etc/sudoersの#includedirの#はコメントアウトじゃない
https://qiita.com/mikeda/items/ddd4c59d6cadeb94ff01

**Comment by h-matsuhashi** [comment]
以下の方法で対応する。
①sudo権限を与えるユーザーの追加
/etc/sudoers.d/配下に設定ファイルを作成し、以下の内容を記載する。
daemon       ALL=(ALL) NOPASSWD:ALL
apache       ALL=(ALL) NOPASSWD:ALL
②Defaults requirettyへの対応
ITAをインストールする環境の/etc/sudoersの中に"Defaults requiretty”があれば、それをコメントアウトする。
（※コメントアウト前にsudoersのバックアップを作成）

**Comment by h-matsuhashi** [comment]
払戻完了。
