### ISSUE TITLE
【メニュー作成】縦メニュー利用カラムグループを多重入れ子で作成し再表示したときに末端の項目が外に出てしまう

### ISSUE THREAD

**Issue by Satoshi-asano** [exastro-suite/it-automation#1628]
以下のように、縦メニューを利用してカラムグループを多重入れ子で項目を登録メニューを作成し、再度メニュー編集画面に移ったときに、入れ子の末端項目がグループの外に出て表示されてしまいます。

【メニュー作成画面】
![image](https://user-images.githubusercontent.com/65987963/139014489-a19a01dd-03d9-42b3-9f31-4174f2f82644.png)

【作成後編集画面】
![image](https://user-images.githubusercontent.com/65987963/139015022-f3853512-4212-4836-aea5-ebbe0588fe29.png)

**Comment by HibikiNanri** [comment]
マージ済み。
