### ISSUE TITLE
【管理コンソール】【システム設定】認証継続期間（最長）のデフォルト値の見直し

### ISSUE THREAD

**Issue by j-kumamoto** [exastro-suite/it-automation#1647]
「管理コンソール」－「システム設定」の認証継続期間：最長（秒）[ID : AUTH_SES_EXPIRY] のデフォルト値（10800）について、ユーザが操作中にも関わらず意図しないタイミングでセッション切れることもあり、ユーザビリティの観点から、デフォルト値（初期値）を見直したい。

●見直し案：10800 秒 (3時間)   >>  **86400 秒 (24時間)**  

【参考】
またユーザ認証の利便性やセキュリティの観点から、ログインからの認証継続時間をデフォルト値から個別に設定変更したいユーザには、本パラメータや、合わせて同メニューの「認証継続期間：未操作（秒）[ID : AUTH_IDLE_EXPIRY] 」を更新から変更することを推奨する。

 例）
 ・操作中にセッション切断しないようにしたい  AUTH_SES_EXPIRY：0 [秒]
 ・ログインから最大2時間でセッションを終了する  AUTH_SES_EXPIRY : 9600 [秒]
 ・ログイン中、未操作時は30分でセッションを終了する  AUTH_IDLE_EXPIRY : 1800 [秒]

**Comment by ta-matsuo** [comment]
以下の仕様を備考に記載する。

認証継続期間：未操作（秒）
～～～～～～～
未操作時に認証(セッション)を継続する期間（秒）
正の数(整数のみ)：上記の通り
(ただしphp.iniの「session.gc_maxlifetime」で指定の値より小さい値)
ゼロ：無効
負の数、整数値以外：3600
～～～～～～～


認証継続期間：最長（秒）
～～～～～～～
認証(セッション)を継続する最長期間（秒）
正の数(整数のみ)：上記の通り
(ただしphp.iniの「session.gc_maxlifetime」で指定の値より小さい値)
ゼロ：無効
負の数、整数値以外：86400
～～～～～～～
