### ISSUE TITLE
ITAコンテナでExcel一括エクスポートを実行し、ダウンロードした日本語のファイル名が文字化けする。

### ISSUE THREAD

**Issue by y-kikuchi2** [exastro-suite/it-automation#1676]
コンテナのベースOSにデフォルトで入っている英語の言語パッケージの状態がおかしい。
英語の言語パッケージを再インストールした所、改善した。

①localeコマンド実行で、「locale: Cannot set xxxxx to default locale: No such file or directory」
が表示された。
[root@43a05a60fb44 /]# locale
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

②langpacks-enのインストールを実行すると既に入っているメッセージが表示されるが
言語設定を実施時にインストールされていないメッセージが表示された。

+ dnf -y --enablerepo=appstream install langpacks-en
Last metadata expiration check: 0:00:04 ago on Thu Nov  4 08:08:43 2021.
Package langpacks-en-1.0-12.el8.noarch is already installed.
Dependencies resolved.
Nothing to do.
Complete!
+ localectl set-locale LANG=en_US.UTF-8
Failed to issue method call: Locale en_US.UTF-8 not installed, refusing.
make: *** [Makefile:60: build] Error 1[](url)

![日本語文字化け](https://user-images.githubusercontent.com/87297836/140707360-28800010-fcbc-4759-af4e-b4ce9e7b7cf0.png)

**Comment by sinatommy** [comment]
it-automation-containerへ移動。
