### ISSUE TITLE
【RestAPI】SymphonyをRestAPI経由で登録するとアクセス許可ロールに「ID変換失敗」というエラーが付く

### ISSUE THREAD

**Issue by dai-kagino** [exastro-suite/it-automation#1695]
RestAPI 経由で Symphony の登録を行った後、WebGUI から Symphony クラス一覧から登録した Symphony を確認すると、以下のようにアクセス許可ロールにID変換失敗というエラーが付与された状態となっている。

**Comment by dai-kagino** [comment]
![image](https://user-images.githubusercontent.com/57690977/141672905-127727c9-b21a-4745-b65e-3a0eecc9ad41.png)

**Comment by dai-kagino** [comment]
登録時のパラメータは以下の通り

<pre>
[{'0': '登録',
  '2': '',
  '3': 'test_symphony',
  '4': '',
  '7': '',
  '9': [{'0': '5', '1': '9000044', '2': '', '3': '', '4': ''}]}]
</pre>

MovementID 9000044 は実際に存在するMovement
RestAPIには、システム管理者（ID:1）経由で接続

RestAPI経由でのSymphony登録は正常に終了し、Symphony実行も問題なく可能
実害は無いが、画面上不自然に見えるため念のため登録させていただきました

なお、SymphonyID:1 の test Symphony は、Web上から登録したSymphony
（こちらは、アクセス権にエラー出力無し

念のため、FILTERした結果を参考に、
  '5': None,
  '5': 'システム管理者',
など設定して登録を行ってみたが、登録自体がエラーになり失敗することを確認

**Comment by y-yonekura** [comment]
アクセス権の項目追加に伴い、以下の変更。
・アクセス権の項目追加、キー「5」。（値は、ロール名をカンマ区切りで入力）
・Movement項目のキーを「9」->「10」へ変更。

```
[{'0': '登録',
  '2': '',
  '3': 'test_symphony',
  '4': '',
  '5': '',
  '7': '',
  '10': [{'0': '5', '1': '9000044', '2': '', '3': '', '4': ''}]}]
```

**Comment by dai-kagino** [comment]
ありがとうございます、試してみます
