### ISSUE TITLE
Movement一覧のオプションパラメータ指定方法がAnsibleTowerとAnsibleで不一致

### ISSUE THREAD

**Issue by m-takahashi-if** [exastro-suite/it-automation#17]
Movement一覧のオプションパラメータ
[AnsibleTower]
「-e VAR_05： 500」「：」指定で設定だが、
[Ansible]
「-e VAR_05： 500」「：」で設定するとエラーとなる。
「-e VAR_05=500」「=」指定で設定するとOK

  ⇒[AnsibleTower]と[Ansible]指定の仕方が不一致（マニュアルにも記載なし。）

マニュアルの記載→ver1.3
検討・対応→ver1.4

**Comment by m-takahashi-if** [comment]
Ansibleの場合、設定値を無加工でansible-playbookのパラメータとして渡す処理にしているので、パラメータエラーはansibleで検出します。
Towerの場合、設定値をTowerのオブジェクトに展開するのて、パラメータチェックをITAが行っています。
なので、エラー検出をITAが行うか、ansibleが行うかの差異が出ています。

**Comment by m-takahashi-if** [comment]
マニュアルに記載する（1.3）
対応は1.4にて検討

**Comment by sinatommy** [comment]
対応内容を確認する。
①現状のまま。ansibleの場合はansibleでチェックさせる。
②Towerと同じようにansibleの場合もパラメータをITAでチェックする。
　=>この場合、Towerで設定可能なパラメータをansibleでもチェック？
　　それとも、ansible-playbookに設定可能な全てのパラメータをITAでチェック？
③その他

**Comment by sinatommy** [comment]
①現状のまま
を採用。
