### ISSUE TITLE
【REST-API】RestAPIでSymphony作成に失敗（Ver1.9 開発中物件）

### ISSUE THREAD

**Issue by dai-kagino** [exastro-suite/it-automation#1714]
11/23時点の最新Revisionを使用してRestAPI経由でSymphony作成を行おうとしたところエラーとなりました。
RequestパラメータおよびHTTP Status、Responseデータは以下のようになります。

```
[{'0': '登録',
  '2': '',
  '3': 'RHEL8_収集',
  '4': '',
  '7': '',
  '9': [{'0': '5', '1': '9000044', '2': '', '3': '', '4': ''}]}]
```

```
HTTP Status: [500]
```

```
<br />
<b>Notice</b>:  Undefined offset: 10 in <b>/exastro/ita-root/libs/webindividuallibs/systems/2100000306/82_symphony_register.php</b> on line <b>141</b><br />
{"Error":"Unexpcted Error","Exception":"Generic error","StackTrace":"none"}
```

修正箇所はエラー発生行とは別になりますが、以下コミット以降でエラー発生しているように思われます。
（一つ前のコミットである ac4ec09459a3e094c2951f5d4e0729e239801d7f では問題発生しませんでした。）
https://github.com/exastro-suite/it-automation/commit/7f992bd4355218fda892bdf6ce1b749c4ccad8e0

あくまで開発中リビジョンでの確認ですので修正予定の既知問題の可能性はありますが、念のためご報告させていただきます。

**Comment by ta-matsuo** [comment]
#1695 にてEDIT時のパラメータの並びをFILTERの並びと合わせるように変更されております。
Movementを指定するキーは9から10に変更されておりますのでキーを10で実施をお願いします。
詳細は#1695 のコメントを参照願います。

**Comment by dai-kagino** [comment]
ありがとうございました。
確認させていただきます。
