### ISSUE TITLE
【メニュー作成】メニュー項目作成でパスワードカラムを作成

### ISSUE THREAD

**Issue by kouhei-suzuki** [exastro-suite/it-automation#176]
メニュー項目作成で登録した値をマスクできるパスワード向けカラムを追加。
パスワードカラムに必要な機能について整理して追加する

〇整理する機能例
・レコードの暗号化
・不可逆性
・目アイコン（入力時の一時表示ボタン）

**Comment by naoki-kondo** [comment]
〇整理する機能例
・レコードの暗号化
⇒backyard側で暗号化と復号実施
・不可逆性
⇒更新はどうする？出来ないようにする？
・目アイコン（入力時の一時表示ボタン）
・メニュー定義/作成でも作成可能とする？
・DBにPW用のカラムを追加
・半角英数・記号での入力
⇒全角はバリデチェック
