### ISSUE TITLE
【全般】ログアウトしたユーザのログインIDのログ出力

### ISSUE THREAD

**Issue by n-genki** [exastro-suite/it-automation#1769]
ブラウザでログアウトボタンをクリックしてログアウトした際にユーザ名をログに出力したい。

現状、ログイン時には「Webap機能の操作・処理結果ログファイル」にログインIDが出力されるが、ログアウト時は出力されないため。

**Comment by ta-matsuo** [comment]
「ログアウト」ボタン押下時にWebログに
LOGOUT[ユーザ名]
を出力するようにする。

**Comment by a-koizumi** [comment]
以下のように対応済みとなります。
「"2022/03/10 06:57:48"   "10.180.81.204" ""      ""      ""      ""      ""      ""      "10.180.81.204" "POST"  "xxxxxxx-xxx-xxxxxxxxxx"     "/common/common_auth.php"       "grp=2100090001"        "administrator" "LOGOUT"
"2022/03/10 06:57:48"   "10.180.81.204" ""      ""      ""      ""      ""      ""      "10.180.81.204" "POST"  "xxxxxxx-xxx-xxxxxxxxxx"     "/common/common_auth.php"       "grp=2100090001"        "administrator" "RESULT:SUCCESS"」
