### ISSUE TITLE
【収集機能】Repeat型の収集データの要素数が減ると、前回のデータがゴミとして残ってしまう

### ISSUE THREAD

**Issue by dai-kagino** [exastro-suite/it-automation#1770]
### 事象

リスト型の収集データについて、収集項目値管理、代入値自動登録を行って収集を行う際に、リストの要素数が減少すると、前回データとの差分要素が以下のようにゴミとして残ってしまう。
(1) 参照元となる収集対象データ："a","b","c"
(2) 登録先となる収集結果：["a", "b", "c"]
(3) 参照元となる収集対象データを変更：："a","e"
(4) 登録先となる収集結果：["a", "e", "c"]  （"c" がゴミとして残ってしまう。）

少なくとも、収集項目値管理、代入値自動登録で登録先として紐付けを行ったデータ要素については、参照元のデータが存在しない場合はデータの削除を行うようにしてほしい。

**Comment by dai-kagino** [comment]
### データ

* [収集項目値管理、代入値自動登録設定](https://github.com/exastro-suite/it-automation/files/7831829/1_.zip)
* [一度目の収集対象データおよび結果](https://github.com/exastro-suite/it-automation/files/7831830/2_.zip)
* [二度目の収集対象データおよび結果](https://github.com/exastro-suite/it-automation/files/7831831/3_.zip)
* [施行後エクスポート](https://github.com/exastro-suite/it-automation/files/7831832/ita_exportdata_20220108071554.zip)

**Comment by dai-kagino** [comment]
### 詳細

(1) 登録OSロール(WIN_EventLog)は、VAR_filtering_condition 変数により収集データのフィルタリングができる
(2) 一度目の収集時には「{LogPath: Security.evtx}」でフィルタすると、結果として4件のデータがヒット
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 14">
<link id=Main-File rel=Main-File
href="file:///C:\Users\Kagino\AppData\Local\Temp\msohtmlclip1\01\clip.htm">
<link rel=File-List
href="file:///C:\Users\Kagino\AppData\Local\Temp\msohtmlclip1\01\clip_filelist.xml">

<style>

</style>
</head>

<body link=blue vlink=purple>



VAR_WIN_EventLog.9500288:[0].Log | 'Security'
-- | --
VAR_WIN_EventLog.9500372:[1].Log | 'Microsoft-Windows-SmbClient/Security'
VAR_WIN_EventLog.9500379:[2].Log | 'Microsoft-Windows-SMBServer/Security'
VAR_WIN_EventLog.9500386:[3].Log | 'Microsoft-Windows-Windows Firewall With Advanced   Security/ConnectionSecurity'



</body>

</html>

(2) 二度目の収集では「{LogPath: Application.evtx}」でフィルタすると、結果として1件のデータがヒット
(3) 期待値は以下の結果となること
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 14">
<link id=Main-File rel=Main-File
href="file:///C:\Users\Kagino\AppData\Local\Temp\msohtmlclip1\01\clip.htm">
<link rel=File-List
href="file:///C:\Users\Kagino\AppData\Local\Temp\msohtmlclip1\01\clip_filelist.xml">

<style>

</style>
</head>

<body link=blue vlink=purple>



VAR_WIN_EventLog.9500288:[0].Log | 'Application'
-- | --




</body>

</html>

(4) しかし、実際には前回収集時のゴミが削除されずに残ってしまい、以下のようになる（２～４番目は前回のゴミ）
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 14">
<link id=Main-File rel=Main-File
href="file:///C:\Users\Kagino\AppData\Local\Temp\msohtmlclip1\01\clip.htm">
<link rel=File-List
href="file:///C:\Users\Kagino\AppData\Local\Temp\msohtmlclip1\01\clip_filelist.xml">

<style>

</style>
</head>

<body link=blue vlink=purple>



VAR_WIN_EventLog.9500288:[0].Log | 'Application'
-- | --
VAR_WIN_EventLog.9500372:[1].Log | 'Microsoft-Windows-SmbClient/Security'
VAR_WIN_EventLog.9500379:[2].Log | 'Microsoft-Windows-SMBServer/Security'
VAR_WIN_EventLog.9500386:[3].Log | 'Microsoft-Windows-Windows Firewall With Advanced   Security/ConnectionSecurity'



</body>

</html>

**Comment by dai-kagino** [comment]
ITA内処理のため、データ収集時の処理によりITA内のデータ削除を行うことは非常に困難。

少なくとも、収集項目値管理、代入値自動登録で登録先として紐付けを行ったメンバ変数については、収集開始時に一旦すべて削除（もしくは内容のクリア）を行ってほしい。

**Comment by dai-kagino** [comment]
添付の kym はリリース版の Ver1.9.0 で作成。

**Comment by ta-matsuo** [comment]
収集機能は、以下の理由により値が無いレコードを廃止する処理は実装しない方針としております。

【廃止処理を入れていない理由】
複数の収集対象ファイルを1メニューに対して登録するケースを考えると、1ファイルごとの処理で廃止処理を入れてしまうと最後の収集ファイルの状態で廃止が行われてしまうため。

オペレーションは実行単位で付与することを推奨しているため、毎回同じオペレーションを使用すると本事象が発生してしまいます。
回避方法としては、以下が考えられます。
①収集のたびにオペレーションを変えて頂ければ別のデータとして登録する。
②または、収集前にWebやRestAPIで該当データの廃止をする。
③収集ファイルに、NULLor空文字としてJSONに登録しておく。

**Comment by dai-kagino** [comment]
Operationの量産やWeb上での廃止操作など運用回避しか方法が無く、あらかじめ作りこんだテンプレートでの対応は難しい旨了解です。
ありがとうございました。
