### ISSUE TITLE
【メニュー作成】プルダウン選択で「YES/No」、「True/False」、「*/（ブランク）」を選べるようにする

### ISSUE THREAD

**Issue by kouhei-suzuki** [exastro-suite/it-automation#178]
メニュー項目作成でチェックボックスカラムを追加する。
本項目のチェック有無によりフラグ（True／False）の値が自動でDBに登録される。

#126  に類似の issue があるので整理が必要

**Comment by ta-matsuo** [comment]
チェックボックスは対応しない。代わりに以下をプルダウン選択に追加する。
・「YES/No」マスタ
・「True/False」マスタ
・「*/（ブランク）」マスタ

**Comment by Satoshi-asano** [comment]
・二択フラグ（Yes/No・True/False）と一択フラグ（＊）でマスタを分ける

**Comment by Satoshi-asano** [comment]
マージ済
ドキュメント修正あり
