### ISSUE TITLE
【インストーラ】MariaDBのパスワードに記号を含めるとエラーになる

### ISSUE THREAD

**Issue by ta-matsuo** [exastro-suite/it-automation#179]

**Comment by h-matsuhashi** [comment]
ita_answers.txtのdb_root_password:とdb_password:に特定の記号を含めるとエラーが発生し、ITAのインストールに失敗する。
失敗する記号：$ / & ( ) ; < > 等

対策
・ita_builder_core.shでセッティングファイルを読み込む際、変数の値になるテキストを、’ ’で囲む処理を加える。
・ita_builder_core.shとinstall.shに記号を\でエスケープする処理を加える。

**Comment by h-matsuhashi** [comment]
対策できた記号
!#%&()*+,-./;<=>?@[]_{|}~^`"
対策できない記号
' \

**Comment by h-matsuhashi** [comment]
MariaDBのパスワードに全ての記号が使えるのを確認済

**Comment by h-matsuhashi** [comment]
記号をパスワードに設定する対応は完了。

＜現状の問題点＞
・db_password:にバックスラッシュがあると、環境(OS等)や状況(バックスラッシュの文字数、db_root_password:にある記号)によっては、ITAがDBにアクセスできなくなり、ITAにログインできなくなる(「システムエラー」のページが表示される)
※MariaDBが正常に稼働、設定したユーザーのID・パスワードでMariaDBにログインできる状況で発生。
・db_password:にシングルクォーテーションが奇数個入っていると、エクスポート/インポートで、作業後のステータスが「完了(異常)」と出る。

**Comment by Saito-Masaru** [comment]
確認した記号一覧
> `~^'"!|\\#$%@&:;\_=-+*/<>()[]{}

確認したパスワード

|                  |                                                          |
|:-----------------|:---------------------------------------------------------|
| db_root_password | root(タブ)`~^'"!\|\#$%@&:;\\_=-+*/<>()[]{}\r\n\t\f\g$root |
| db_password      | ita(タブ)`~^'"!\|\#$%@&:;\\_=-+*/<>()[]{}\r\n\t\f\g$ita   |

問題のある記号一覧

|                      | ita_bullder_core | ita_installer |                                                                                          |
|:--------------------:|:----------------:|:-------------:|:-----------------------------------------------------------------------------------------|
| '(シングルクォート)  | 〇               | 〇            | shell変数代入に問題あり、SQLでエスケープが必要                                           |
| \\(バックスラッシュ) | 〇               | 〇            | read lineで消える、SQLでエスケープが必要、対話処理でのエスケープが必要                   |
| "(ダブルクォート)    | 〇               |               | 対話処理でエスケープが必要                                                               |
| $                    | 〇               |               | 対話処理でエスケープが必要                                                               |
| [                    | 〇               |               | 対話処理でエスケープが必要                                                               |
| /                    |                  | 〇            | shellの置換処理(sed)で問題あり                                                           |
| &                    |                  | 〇            | shellの置換処理(sed)で問題あり                                                           |
| :(コロン)            |                  | 〇            | answers.txtの区切り文字の処理に問題あり                                                  |
| \r,\nなど            |                  | 〇            | web用のconfigファイルの暗号化ロジックで処理する際に展開していた(\t⇒タブ,\n⇒改行のように) |


'&'のsedの挙動について

```
#!/bin/sh
str='abc&xyz'
TMP="string is '#TARGET#'."
echo "#template=>$TMP"
echo ""
echo "#str=>$str"
tmp="$(echo "$TMP" | sed "s/#TARGET#/$str/g")"
echo "#applied template=>$tmp"
echo ""
str="$(echo "$str" | sed 's/&/\\&/g')"
echo "#str(escaped)=>$str"
tmp="$(echo "$TMP" | sed "s/#TARGET#/$str/g")"
echo "#applied template=>$tmp"
```

実行結果

```
#template=>string is '#TARGET#'.

#str=>abc&xyz
#applied template=>string is 'abc#TARGET#xyz'.

#str(escaped)=>abc\&xyz
#applied template=>string is 'abc&xyz'.
```

**Comment by h-matsuhashi** [comment]
MariaDBの設定項目（db_root_password、db_name、db_username、db_password）に全角文字が使えることが判明。
全角文字は文字コードによって誤作動を引き起こすことがあるため、設定ファイルの入力値をチェックして全角文字を弾く仕組みを追加する。

＜仕様＞
設定ファイル（ita_builder_setting.txt、ita_answers.txt）を読み込む際、読み込んだ行に全角文字（半角以外の文字）が含まれていないかをチェックし、全角文字が含まれていたらインストーラーを停止する。
その際、エラーメッセージと全角文字が含まれている行（チェック時に引っかかった行）を表示する。

＜半角文字一覧＞
 !"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~
※先頭は半角スペース

**Comment by h-matsuhashi** [comment]
修正完了。
マニュアルの修正必要あり。
