### ISSUE TITLE
SSO認証 PearのAuthを外す

### ISSUE THREAD

**Issue by m-takahashi-if** [exastro-suite/it-automation#18]
まずは仕様の調査から開始する。
⇒ITAのロール管理などとどう連携できるか
今の認証は残す。
今のAD認証をどうするか。
PearのAuthも外せたら外す

**Comment by sinatommy** [comment]
Oauthで実装する。

**Comment by sinatommy** [comment]
PearのAuth外しをv1.4にて対応。
SSO認証はv1.5にて対応する。
