### ISSUE TITLE
【管理コンソール】シーケンスを調整するメニューを追加する

### ISSUE THREAD

**Issue by sinatommy** [exastro-suite/it-automation#180]

**Comment by Saito-Masaru** [comment]
# 機能
A_SEQUENCEテーブルの管理をする

# 概要
* 現状のレコードの更新のみをする  
* 新規登録・廃止は行わない  
* MENUに紐づいているレコードのみ表示/変更可能  

# 画面の変更
* 登録/全件ダウンロード/変更履歴 タブ削除(非表示)
* 一覧から 廃止ボタン/最終更新日時/最終更新者 を非表示
* MENU名、MENU_GROUPを一覧と更新フォームを表示(変更不可)

# テーブルの変更
* MENU_IDカラム追加
* SORT_ORDER(並び順指定)カラム追加
* DISUSE_FLAGは追加しない
* LAST_UPDATE_USERは追加しない
* LAST_UPDATE_TIMESTAMPは追加する(多重更新防止の為)
* PRIMARY KEY(PK)はNAMEのまま変更しない
* 履歴テーブルは使用しない

# 実装メモ
上記をtableControlAgent classを継承して実装する。

**Comment by Saito-Masaru** [comment]
* この機能で`A_SEQUENCE`には新規レコードは追加しない  
* LAST_UPDATE_USERカラムは最終更新日時を確認するSQLでjoin条件になっているので使用する  
* DISUSE_FLAGは本体テーブルでは使用しないがviewでは"0"の固定値で使用する  
* 表示順序のカラムは`DISP_SEQ`とする(A_MENU_LISTに合わせた)
* 更新フォームで入力可能なのは下記の2項目で、シーケンス名、MENU_ID、MENU_GROUP_IDは更新不可
    * 設定値(int)
    * 表示順序(int)
* 更新フォームで更新不可項目は既存FORM(selectBox)から表示文字列を取り出し、formは非表示にしてその表示文字列を単純に表示する
    * 実装はjavascript
* 設定値、表示順序はNumColumnを使用

**Comment by Saito-Masaru** [comment]
このメニュー追加時に以下のレコードを削除またはmodelの変更を行った。
| シーケンス名                                    |           |
|:----------------------------------------|:-------|
| F_CREATE_MST_MENU_INFO_RIC        |  削除 |
| F_CREATE_MST_MENU_INFO_JSQ       |  削除 |    
| F_CREATE_MST_ITEM_INFO_RIC          |  削除 |
| F_CREATE_MST_ITEM_INFO_JSQ         |  削除 |
| F_MST_MENU_TABLE_LINK_RIC          |  削除 |
| F_MST_MENU_TABLE_LINK_JSQ         |  削除 |
| F_MST_TABLE_ITEM_LIST_RIC             |  削除 |
| F_MST_TABLE_ITEM_LIST_JSQ            |  削除 |
| F_CREATE_MST_MENU_STATUS_RIC  |  削除 |
| F_CREATE_MST_MENU_STATUS_JSQ |  削除 |
| C_COBBLER_PROFILE_RIC                  | model-a ⇒ model-d |
| C_COBBLER_PROFILE_JSQ                 | model-a ⇒ model-d |
| B_COBBLER_IF_INFO_RIC                  | model-c ⇒ model-d |
| B_COBBLER_IF_INFO_JSQ                  | model-c ⇒ model-d |
