### ISSUE TITLE
【機器一覧】ansible_become_pass 登録の方法について

### ISSUE THREAD

**Issue by dai-kagino** [exastro-suite/it-automation#1806]
現在、機器一覧のログイン情報にはAnsibleで一般ユーザにssh接続した後でsudoを実行する際のパスワードを指定する方法が無いように見える
機器一覧の追加オプションに
```
ansible_become_pass: <sudoパスワード>
```
を登録すれば対応は可能だが、パスワード文字列が隠されないで見えてしまうことになります。

機器一覧のパスワード入力欄に隣接する形で「入力したパスワードをsudoパスワードとして使用する」というようなチェックボックスを付け、チェックされたら入力されたパスワードを以下のように登録してくれるとありがたいのですが・・・。

* チェック時
```
ansible_password: <入力したパスワード文字列>
ansible_become_pass: <入力したパスワード文字列>
```

* 非チェック時
```
ansible_password: <入力したパスワード文字列>
```

**Comment by ta-matsuo** [comment]
機器一覧の追加オプションの値は変数化することが可能です。
変数化することにより、「代入値自動登録設定」メニューや「代入値管理」メニューでパスワード化した具体値と紐づけることで秘匿化することが可能です。
設定方法は以下マニュアルの「表 5.1-1 登録画面項目一覧（機器一覧）」の「インベントリファイル　追加オプション」を参照ください。

https://exastro-suite.github.io/it-automation-docs/asset/Documents_ja/Exastro-ITA_%E5%88%A9%E7%94%A8%E6%89%8B%E9%A0%86%E3%83%9E%E3%83%8B%E3%83%A5%E3%82%A2%E3%83%AB_Ansible-driver.pdf

**Comment by dai-kagino** [comment]
ありがとうございました！
