### ISSUE TITLE
【インストーラ】インストールスクリプトの構成変更

### ISSUE THREAD

**Issue by ta-matsuo** [exastro-suite/it-automation#181]
インストールスクリプトの構成を利用者がわかりやすいように変更する。
・ita_answers.txtとita_builder_setting.txtの統合。
・ita_answers.txtでライブラリのインストール有無を指定できるようにする。
・実行するスクリプトを分かりやすくする。ita_install_package/install_scripts配下には実行するスクリプトのみを配置して、その他のスクリプトはbinに格納する。

**Comment by h-matsuhashi** [comment]
確認事項
＜ita_answers.txtとita_builder_setting.txtの統合＞
・ita_answers.txtとita_builder_setting.txtのどちらに統合するか。
・似た内容の質問事項への対処
　ーita_builder_setting.txt（ITAをインストールするOSそのものを入力する）
　　# Select Operation System. ("CentOS7","CentOS8","RHEL7","RHEL8","RHEL7_AWS","RHEL8_AWS")
　　# e.g) linux_os:RHEL8
　　linux_os:
　ーita_answers.txt（ITAインストールするOSがRHEL7系/RHEL8系のどちらかを入力する）
　　# Select Operation System. ("RHEL7" or "RHEL8")
　　# e.g) ita_os:RHEL8
　　ita_os:RHEL7

＜ライブラリのインストール有無を指定＞
・指定範囲をどこまでにするか。
　－ドライバごと（ITA本体、ansible、Material）
　－ライブラリ概要ごと（ITA共通、Mariadb、php、ansible）
　※イメージ：インストールマニュアルの環境構築時にインストールされるライブラリの一覧の表の括り

＜スクリプトの整理＞
・現状、ita_install_package/install_scripts配下には、何かしらで実行するスクリプトしかないので、特にbinに移すスクリプトはない？
　ー現状のスクリプト
　　ita_builder_offline.sh
　　ita_builder_online.sh
　　ita_gather_library.sh
　　ita_installer.sh
　　ita_version_up.sh

**Comment by h-matsuhashi** [comment]
確認結果
＜ita_answers.txtとita_builder_setting.txtの統合＞
・設定ファイルは、ita_answer.txtに統合。
・# Select Operation System.関連は、linux_os:に統合。
（ita_osの変数周りを修正）
＜ライブラリのインストール有無を指定＞
・ITAに必要なライブラリをインストールするorしない の項目を追加。
（「する」にした場合は全てのライブラリをインストール）
＜スクリプトの整理＞
起動時に叩くシェル1つのみを置いて、それ以外はbinの中へ移動。
モードの切り替えはita_answer.txtで対応。

**Comment by h-matsuhashi** [comment]
対応内容
＜ita_answers.txtとita_builder_setting.txtの統合＞
・ita_builder_setting.txtにある、OS種別判定の項目(linux_os)とRHELのサブスク関係の項目(redhat_user_name、redhat_user_password、pool_id)をita_answers.txtに統合。
　※ita_builder_setting.txtは廃止
・2つあったOS種別判定の項目(linux_os、ita_os)をlinux_osに統合。
・ita_builder_core.shでita_answers.txtのみ読み込むように変更。

＜ライブラリのインストール有無を指定＞
・ita_answers.txtに、ITAの動作に必要なライブラリをインストールするかどうかの項目を追加。
　install_library:　(初期値:yes)
・install_libraryが「no」の時、以下の動作を省略するように変更。
　－ yum-utils と createrepoのインストール(RHEL7系のみ)
　－リポジトリの追加
　－オフラインインストール時のRPMインストール(RHEL8系のみ)
　－各種ライブラリのインストール(ITA共通、MariaDB、Apach、php関連、git、Ansible関連)
　　※インストール以外の設定作業については通常通り行う(Apach常駐化、MariaDB初期設定等)
・install_libraryが「no」の時、MariaDB初期設定前のチェックでMariaDBがインストールされていない場合は、異常終了させる仕組みを追加。
・install_libraryが「no」の時、ita_builder_core.shの処理の終わりに、全てのライブラリが揃っているかチェックする仕組みを追加。（揃っていなかったら異常終了させる）

＜スクリプトの整理＞
・ita_install_package/install_scripts配下には、ita_installer.shのみを置き、他のシェルはita_install_package/install_scripts/bin/へ移動。
・インストールのモードはita_answers.txtのinstall_mode:に入っている値によって分岐させる。
（ita_builder_offline.sh、ita_builder_online.sh、ita_gather_library.shは廃止）
※インストールモード一覧
　ー Install_Online：オンラインインストール
　－ Install_Offline：オフラインインストール
　－ Gather_Library：ライブラリ収集（オフラインインストール前に行う）
　－ Install_ITA：ITA本体のみインストール（環境構築(ita_builder_core.sh)をしない）
　－ Versionup：ITAバージョンアップ
　－ Uninstall：ITAアンインストール

**Comment by h-matsuhashi** [comment]
改修案
案１、7つのモードを指定させる
 
案２、モード：Online、Offline、Gather、VersionUP、Uninstall
　　　ライブラリ有無：Yes/no

※案２の場合、ライブラリ有無はGather、Uninstallでは指定不要。
　Online-noとOffline-noは一緒の挙動（ITAのみのインストール）になる

現状、案1で進行中。

**Comment by h-matsuhashi** [comment]
マージ済。
ドキュメント（インストールマニュアル系）修正の必要あり。
