### ISSUE TITLE
【Ansible共通】実行ユーザーを変更して鍵認証のホストに対してansibleを実行するエラーなる

### ISSUE THREAD

**Issue by sudodaisuke-jp** [exastro-suite/it-automation#1835]
Ansible共通-インターフェイス情報-Ansible Engine インターフェース-実行ユーザーにsudo設定したユーザを設定し
鍵認証のホストに対してAnsibleの実行するとPermission deniedのエラーになりsshで接続できていない。
実施時のログを確認するとコピーされた鍵ファイルのオーナーとグループがrootなっており「実行ユーザー」に設定した
ユーザーで鍵ファイルにアクセスするとPermission deniedになるため実行ユーザーと鍵ファイルのオーナーとグループの不一致で鍵ファイルにアクセスできなくSSHが失敗していると思われる。

**Comment by enoman** [comment]
実行ユーザーが設定されている場合、鍵ファイルのオーナーを実行ユーザーに設定するように変更

**Comment by enoman** [comment]
完了
