### ISSUE TITLE
【収集機能】ファイルアップロードで登録したファイルを廃止したい場合、何を収集データとして登録すれば良いか不明

### ISSUE THREAD

**Issue by dai-kagino** [exastro-suite/it-automation#1845]
掲題の通り、パラメータシートに「ファイルアップロード」で作成した項目に登録されたファイルについて、その後ターゲット環境で削除した場合、パラメータシート側でも削除させるためにはどのような収集項目値を返却すれば可能かわからない。

現状、undefined（存在しないデータ）については null の値を返却する仕様としているが、収集時にエラーとなっているようで収集データの自動登録が行われない。

「ファイルアップロード」の項目値に収集データとしてnullを指定した場合には登録ファイルを廃止（事前にファイル登録していなければ無視）する仕様としてほしい。

**Comment by y-yonekura** [comment]
ファイルを削除する場合、YAMLファイルの上の削除対象の項目を"" ,'' を指定することで削除されます。
例：
> VAR_NAME_1: ""
> VAR_NAME_1: ’’’

以下、ファイル削除時の収集ログの表示例となります。
[2]の、実行結果がnullとなりますが、RESTAPIの実行は成功しています。
実行結果が、nullとなる件は、v1.10にて対応済となります。

> 2022-03-17 14:48:38 REST DATA ( ホスト名: ita-sample01 メニューID: 0000000016 オペレーションNO: 1 )
> Array
> (
>     [0] => http://XXX.XXX.XXX.XXX/default/menu/07_rest_api_ver1.php?no=0000000016
>     [1] => [{"0":"更新","2":"1","3":"ita-sample01","9":"2020\/01\/20 00:00_1:OP_NULL","10":"","11":"","12":"","15":"T_20220317144750483465"}]
>     [2] => null
> )

**Comment by dai-kagino** [comment]
空文字列を指定することで、登録済ファイルが削除される旨理解いたしました。
ありがとうございました。
