### ISSUE TITLE
【メニュー全般】隠しメニューに対するロール・メニュー紐付管理の紐付に「メンテナンス可」と「閲覧のみ」がばらばらに設定されている

### ISSUE THREAD

**Issue by enoman** [exastro-suite/it-automation#1850]
隠しメニューに対するロール・メニュー紐付管理の紐付に「メンテナンス可」と「閲覧のみ」がばらばらに設定されている。
また、メンテナンス可に変更した場合、登録・更新ずできてしまうので、
幾つかのバックヤード処理では、レコードの最終更新者でレコード更新の有無を判定はており、隠しメニューのレコードをWebから更新してしまうと、期待するレコードが生成されない場合がある。

**Comment by sinatommy** [comment]
マニュアルに記載する。
