### ISSUE TITLE
【RestAPI】RestAPIでのメニューグループ登録時にアイコンが登録できない

### ISSUE THREAD

**Issue by dai-kagino** [exastro-suite/it-automation#1861]
掲題の通り、RestAPI経由でメニューグループを登録しアイコンを紐づけようとしたところ、メニューグループは正常に登録されましたが、指定したアイコンが紐づかない事象が発生いたしました。

添付のPYファイルで確認したところ、UPLOADFILE で Base64 エンコードされた PNG ファイルは指定できているようですがそれでもアイコンが紐づけされないように見えております。

当方の指定方法に問題があるのか、切り分けられておらず申し訳ありませんがご連絡まで。

**Comment by dai-kagino** [comment]
[test.zip](https://github.com/exastro-suite/it-automation/files/8322384/test.zip)
テストに使用したPythonファイル、およびアイコン用画像ファイルを添付させていただきます。

**Comment by dai-kagino** [comment]
![capture](https://user-images.githubusercontent.com/57690977/159442893-3f9bf0eb-2192-491c-ab3a-127e22af9dd7.png)
[capture.txt](https://github.com/exastro-suite/it-automation/files/8322676/capture.txt)
当方で確認を行った際のデバッグ出力、および登録結果のキャプチャになります。

**Comment by ta-matsuo** [comment]
「メニューグループ管理」メニューの「パネル用画像」がRESTAPIから登録・更新できない作りになっていました。
v1.10.0で修正します。
