### ISSUE TITLE
ITAをバージョンアップした際、disableに設定していたサービスを起動しないようにする。

### ISSUE THREAD

**Issue by d-miyata** [exastro-suite/it-automation#1883]
現在、ITAをバージョンアップした際に、ITAの全サービスを起動させる仕組みになっている。
バージョンアップした際、disableに設定していたサービスを停止したいとき、コマンド入力やOS再起動などの手動で停止させるのではなく、デフォルトで停止させたい。

**Comment by sinatommy** [comment]
ドキュメントに記載する。
