### ISSUE TITLE
【Conductor】クラス編集RestAPI対応

### ISSUE THREAD

**Issue by y-yonekura** [exastro-suite/it-automation#189]

**Comment by TakashiKitamori** [comment]
- RestAPIで扱う値は画面操作で送っているリクエスト値に倣う（保存ボタンでダウンロードされるJsonと同じ）。
- 座標の操作は不可。RestAPIから登録する場合に追加されるNodeの座標はStartを基準に下へ固定間隔で並べる。
- 24日打ち合わせの結果、画面操作と共通のエラー処理を最優先。ソースやテスト項目を参照し、画面操作の制約（Startは初期配置の1つのみ等）で実現されているもの含めエラー条件を整理し、再度打ち合わせで確認する。
