### ISSUE TITLE
【全般】Excelファイル名の見直し

### ISSUE THREAD

**Issue by y-kikuchi2** [exastro-suite/it-automation#1892]
対象
Excel一括エクスポート、各メニューのExcelダウンロード系

内容
ファイル名の表記ゆれ、ITAメニュー名からファイル名が
連想し難いものがあるので全体的に整えたい。

例1
・ファイル名をメニュー名と同じにしたい。
現在の状態
ファイル名　　　　　　　　　ITAのメニュー名
ITA管理対象システム一覧　  →  機器一覧
オペレーション一覧情報       →  オペレーション一覧
Movement　　　                   →　Movement一覧

例2
・ファイル名の括弧が全角と半角が混在しているので、半角で統一したい。
Ansible(Legacy)Movement_20220412162916.xlsx
Ansible（Legacy）Movement-Playbook紐付_20220412162919.xlsx

例3
・ファイル名のTerraformとメニュー名の間がアンダースコアがある場合とない場合があるので統一したい。
Terraform_Policy管理_20220412162959.xlsx
Terraform作業管理_20220412163009.xls
![例1](https://user-images.githubusercontent.com/87297836/163075236-4b292518-24ef-4d08-a5f6-98a007a0cb3d.png)
![例2](https://user-images.githubusercontent.com/87297836/163075277-45d20ca7-0b65-4fc0-9fbe-6f30c1b50c51.png)
![例3](https://user-images.githubusercontent.com/87297836/163075300-fd6e35a5-c2db-4aad-adbe-6b4f79a9ac05.png)
x

**Comment by a-koizumi** [comment]
★以下追加で対応★

【2100020000_Ansible共通】
Ansible(共通)インターフェース情報_yyyymmddhhmmss.xlsx
Ansible(共通)Ansible Tower(AAC)ホスト一覧_yyyymmddhhmmss.xlsx
Ansible(共通)グローバル変数管理_yyyymmddhhmmss.xlsx
Ansible(共通)ファイル管理_yyyymmddhhmmss.xlsx
Ansible(共通)テンプレート管理_yyyymmddhhmmss.xlsx
Ansible(共通)収集インターフェース情報_yyyymmddhhmmss.xlsx
Ansible(共通)収集項目値管理_yyyymmddhhmmss.xlsx
Ansible(共通)AnsibleCommonVarsUsedList_yyyymmddhhmmss.xlsx

【2100020002_Ansible-Pioneer】
Ansible(共通)OS種別マスタ情報_yyyymmddhhmmss.xlsx

**Comment by a-koizumi** [comment]
★以下追加で対応2★

【2100000002_管理コンソール】
IPアドレスフィルタ管理_yyyymmddhhmmss.xlsx

【2100011601_メニュー作成】
メニュー(縦)作成情報_yyyymmddhhmmss.xlsx

【2100020001_Ansible-Legacy】
Ansible(Legacy)Movement一覧_yyyymmddhhmmss.xlsx
Ansible(Legacy)変数名一覧_yyyymmddhhmmss.xlsx
Ansible(Legacy)Movement-Playbook紐付_yyyymmddhhmmss.xlsx

【2100020002_Ansible-Pioneer】
Ansible(Pioneer)Movement一覧_yyyymmddhhmmss.xlsx
Ansible(Pioneer)対話ファイル素材集_yyyymmddhhmmss.xlsx
Ansible(Pioneer)変数名一覧_yyyymmddhhmmss.xlsx
Ansible(Pioneer)Movement変数紐付管理_yyyymmddhhmmss.xlsx

【2100020003_Ansible-LegacyRole】
Ansible(Legacy Role)Movement一覧_yyyymmddhhmmss.xlsx
Ansible(Legacy Role)変数名一覧_yyyymmddhhmmss.xlsx
Ansible(Legacy Role)メンバー変数管理_yyyymmddhhmmss.xlsx
Ansible(Legacy Role)多段変数配列組合せ管理_yyyymmddhhmmss.xlsx

【2100030001_Cobbler】
Cobblerプロファイルリスト_yyyymmddhhmmss.xlsx

【2100080001_Terraform】
Terraform_Movement一覧_yyyymmddhhmmss.xlsx
Terraform_Policies管理_yyyymmddhhmmss.xlsx
Terraform_PolicySets管理_yyyymmddhhmmss.xlsx

【2100100001_Symphony】
Movementインスタンス一覧_yyyymmddhhmmss.xlsx
Symphonyインタンス一覧_yyyymmddhhmmss.xlsx
Symphonyクラス一覧_yyyymmddhhmmss.xlsx
Symphony作業一覧_yyyymmddhhmmss.xlsx

【2100090001_Conductor】
Conductor作業一覧_yyyymmddhhmmss.xlsx
Conductorクラス一覧_yyyymmddhhmmss.xlsx

**Comment by a-koizumi** [comment]
★英語版は以下で対応★

【2100000002_Management Console】

Role_menu link list_yyyymmddhhmmss.xlsx ⇒ Role・Menu link list_yyyymmddhhmmss.xlsx
Role_user link list_yyyymmddhhmmss.xlsx ⇒ Role・user link list_yyyymmddhhmmss.xlsx
File deletion management_yyyymmddhhmmss.xlsx ⇒ File delete list_yyyymmddhhmmss.xlsx
Operation deletion management_yyyymmddhhmmss.xlsx ⇒ Operation delete list_yyyymmddhhmmss.xlsx

【2100011701_HostGroup management】

HostGroup list_yyyymmddhhmmss.xlsx ⇒ HostGroup managemaent_yyyymmddhhmmss.xlsx

【2100020000_Ansible Common】

Ansible Interface information_yyyymmddhhmmss.xlsx ⇒ Ansible Common Interface information_yyyymmddhhmmss.xlsx
AnsibleTower(AAC)hostlist_yyyymmddhhmmss.xlsx ⇒ Ansible Common (AAC)hostlist_yyyymmddhhmmss.xlsx
Ansible global variable list_yyyymmddhhmmss.xlsx ⇒ Ansible Common Global variable list_yyyymmddhhmmss.xlsx
Ansible file list_yyyymmddhhmmss.xlsx ⇒ Ansible Common File list_yyyymmddhhmmss.xlsx
Ansible template list_yyyymmddhhmmss.xlsx ⇒ Ansible Common template list_yyyymmddhhmmss.xlsx
Collected item value list_yyyymmddhhmmss.xlsx ⇒  Ansible Common Collected item value list_yyyymmddhhmmss.xlsx
Collection interface information_yyyymmddhhmmss.xlsx ⇒  Ansible Common Collection interface information_yyyymmddhhmmss.xlsx
AnsibleCommonVarsUsedList_yyyymmddhhmmss.xlsx ⇒  Ansible Common Common variable use list_yyyymmddhhmmss.xlsx

【2100020001_Ansible-Legacy】

Movement playbook link_yyyymmddhhmmss.xlsx ⇒ Legacy Movement playbook link_yyyymmddhhmmss.xlsx
Legacy var name list_yyyymmddhhmmss.xlsx ⇒ Legacy Variable name list_yyyymmddhhmmss.xlsx
Legacy Substitut val-auto-reg_yyyymmddhhmmss.xlsx ⇒ Legacy Substitution val auto-reg setting_yyyymmddhhmmss.xlsx
Legacy Operation tracking list_yyyymmddhhmmss.xlsx ⇒ Legacy Excution list_yyyymmddhhmmss.xlsx

【2100020002_Ansible-Pioneer】

Movement dialogue type link_yyyymmddhhmmss.xlsx ⇒ Pioneer Movement dialogue type link_yyyymmddhhmmss.xlsx
Pioneer dialog type list_yyyymmddhhmmss.xlsx ⇒ Pioneer Dialog type list_yyyymmddhhmmss.xlsx
Pioneer Dialog file files_yyyymmddhhmmss.xlsx ⇒ Pioneer Dialog files_yyyymmddhhmmss.xlsx
Pioneer var name list_yyyymmddhhmmss.xlsx ⇒ Pioneer Variablename list_yyyymmddhhmmss.xlsx
Pioneer Substitut val-auto-reg_yyyymmddhhmmss.xlsx ⇒ Pioneer Substitution val auto-reg setting_yyyymmddhhmmss.xlsx
Pioneer target host_yyyymmddhhmmss.xlsx ⇒ Pioneer Target host_yyyymmddhhmmss.xlsx
Pioneer Operation tracking list_yyyymmddhhmmss.xlsx ⇒ Pioneer Excution list_yyyymmddhhmmss.xlsx

OS type master information_yyyymmddhhmmss.xlsx ⇒ Ansible Common OS type master information_yyyymmddhhmmss.xlsx

【2100020003_Ansible-LegacyRole】

Movement role link_yyyymmddhhmmss.xlsx ⇒ Role Movement role link_yyyymmddhhmmss.xlsx
Role role name list_yyyymmddhhmmss.xlsx ⇒ Role Role name list_yyyymmddhhmmss.xlsx
Role variable name list_yyyymmddhhmmss.xlsx ⇒ Role Variable name list_yyyymmddhhmmss.xlsx
Nested variable list_yyyymmddhhmmss.xlsx ⇒ Role Nested Role variable list_yyyymmddhhmmss.xlsx
Role Movement var association_yyyymmddhhmmss.xlsx ⇒ Role Movement variable association list_yyyymmddhhmmss.xlsx 
Role target host_yyyymmddhhmmss.xlsx ⇒ Role Target host_yyyymmddhhmmss.xlsx
Role Var specific value list_yyyymmddhhmmss.xlsx ⇒ Role Variable specific value list_yyyymmddhhmmss.xlsx
Role Nested var member list_yyyymmddhhmmss.xlsx ⇒ Role Nested variable member list_yyyymmddhhmmss.xlsx
Role nested var array comb list_yyyymmddhhmmss.xlsx ⇒ Role Nested variable array combination list_yyyymmddhhmmss.xlsx 
Role Operation tracking list_yyyymmddhhmmss.xlsx ⇒ Role Excution list_yyyymmddhhmmss.xlsx

【2100030001_Cobbler】

Cobbler interface information_yyyymmddhhmmss.xlsx ⇒ Cobbler Interface information_yyyymmddhhmmss.xlsx 
Cobbler profile list_yyyymmddhhmmss.xlsx ⇒ Cobbler Profile list_yyyymmddhhmmss.xlsx

【2100080001_Terraform】

Terraform_Organizations_yyyymmddhhmmss.xlsx ⇒ Terraform_Organizations list_yyyymmddhhmmss.xlsx
Terraform_Workspaces_yyyymmddhhmmss.xlsx ⇒ Terraform_Workspaces list_yyyymmddhhmmss.xlsx 
Terraform_Movement_yyyymmddhhmmss.xlsx ⇒ Terraform_Movement list_yyyymmddhhmmss.xlsx
Terraform_Policy_yyyymmddhhmmss.xlsx ⇒ Terraform_Policies list_yyyymmddhhmmss.xlsx
Terraform_PolicySets_yyyymmddhhmmss.xlsx ⇒ Terraform_Policy Sets list_yyyymmddhhmmss.xlsx 
Terraform_PolicySet-Policy_yyyymmddhhmmss.xlsx ⇒ Terraform_PolicySet-Policy link list_yyyymmddhhmmss.xlsx
Terraform_PolicySet-Workspace_yyyymmddhhmmss.xlsx ⇒ Terraform_PolicySet-Workspace link list_yyyymmddhhmmss.xlsx
Terraform_Nested_variable_list_yyyymmddhhmmss.xlsx ⇒ Terraform_Nested variable list_yyyymmddhhmmss.xlsx
Terraform_operation tracking list_yyyymmddhhmmss.xlsx ⇒ Terraform_Excution list_yyyymmddhhmmss.xlsx
Terraform_Substitut val-auto-reg_yyyymmddhhmmss.xlsx ⇒ Terraform_Substitution val auto-reg setting_yyyymmddhhmmss.xlsx
Terraform_Module_variable_link_yyyymmddhhmmss.xlsx ⇒ Terraform_Module variable association list_yyyymmddhhmmss.xlsx
Terraform_Movement_variable_link_yyyymmddhhmmss.xlsx ⇒ Terraform_Movement variable association list_yyyymmddhhmmss.xlsx

【2100090001_Conductor】

Conductor class information_yyyymmddhhmmss.xlsx ⇒ Conductor class list_yyyymmddhhmmss.xlsx
Conductor instance information_yyyymmddhhmmss.xlsx ⇒ Conductor list_yyyymmddhhmmss.xlsx
Conductor regular work execution information_yyyymmddhhmmss.xlsx ⇒ Conductor regularly execution_yyyymmddhhmmss.xlsx

【2100100001_Symphony】

Symphony class information_yyyymmddhhmmss.xlsx ⇒ Symphony class List_yyyymmddhhmmss.xlsx
Symphony instance information_yyyymmddhhmmss.xlsx ⇒ Symphony execution list_yyyymmddhhmmss.xlsx
Symphony Movement list_yyyymmddhhmmss.xlsx ⇒ movement associated with Symphony list_yyyymmddhhmmss.xlsx
Symphony regular work execution information_yyyymmddhhmmss.xlsx ⇒ Symphony regularly execution_yyyymmddhhmmss.xlsx


【2100000003_Basic Console】
【2100011601_Create Menu】
【2100110001_Compare】
【2100120001_CI_CD for IaC】
