### ISSUE TITLE
メニュー作成機能の拡充

### ISSUE THREAD

**Issue by m-takahashi-if** [exastro-suite/it-automation#19]
・ボタンカラムをつけて他のメニューに飛ぶ
・プルダウン選択したら、マスタに付随した情報も引っ張れるようにする
・カラムの種類を選べるようにする（数値、日付など）

**Comment by sinatommy** [comment]
担当者study中

**Comment by naoki-kondo** [comment]
# 1.4v対応実装機能(予定)

* メニュー作成後の設定カラムの最大値/最小値の設定(テキスト・数値・日付)
* メニュー作成後の設定カラムに小数の桁数を設定
* 設定した小数カラムに整数の桁数を設定
* カレンダーカラム、整数カラム、少数カラム、タイムカラムの中からカラムの種類を選べるようにする
>プルダウン選択したら、マスタに付随した情報も引っ張れるようにする

上記は1.5v以降に実装予定

**Comment by sinatommy** [comment]
タスクをそれぞれのissueに別立てしたので、本件はcloseします。
