### ISSUE TITLE
【構築資材管理】資材紐付管理にTerraformドライバを追加

### ISSUE THREAD

**Issue by ta-matsuo** [exastro-suite/it-automation#190]

**Comment by HibikiNanri** [comment]
関連ドキュメント：
・Exastro-ITA_利用手順マニュアル_構築資材管理機能
・環境構築ガイド_構築資材管理機能編（←修正不要）

**Comment by HibikiNanri** [comment]
・\ita_install_package\install_scripts\bin\install.sh
・\ita_install_package\install_scripts\ita_version_up.sh
上記2ファイルは別途コミット予定

**Comment by HibikiNanri** [comment]
マージ完了。
