### ISSUE TITLE
【ホストグループ】親と子のオペレーションが異なる場合でも、親のホストグループで定義したパラメータを子のホストグループに継承させたい

### ISSUE THREAD

**Issue by shigeki-m** [exastro-suite/it-automation#1900]
入力用メニューグループで、ホストグループに設定したパラメータをオペレーションに関係なく、子のホストグループおよびホストに継承させたい。
オペレーションの実行対象は、ホスト紐付管理メニューで設定したオペレーションとホスト名で管理したい。

**Comment by shigeki-m** [comment]
例えばハードウエアのモデルによって一律に決まる設定値等をホストグループを使用して適用したいが、オペレーションの単位を特定のホストの集合（ある拠点の全NW機器、等）とした場合、オペレーションごとに同じパラメータを定義する必要があり、一元的に管理できない。

**Comment by shigeki-m** [comment]
Ansible-Legacyの作業対象ホストにおいて、オペレーションとMovementとホストを関連付けづけることで、パラメータシートでオペレーションの指定を行わなくても、対象ホストに関連するパラメータシートを変数に代入できるようにしてほしい。

**Comment by ta-matsuo** [comment]
> 入力用メニューグループで、ホストグループに設定したパラメータをオペレーションに関係なく、子のホストグループおよびホストに継承させたい。
> オペレーションの実行対象は、ホスト紐付管理メニューで設定したオペレーションとホスト名で管理したい。

> 例えばハードウエアのモデルによって一律に決まる設定値等をホストグループを使用して適用したいが、オペレーションの単位を特定のホストの集合（ある拠点の全NW機器、等）とした場合、オペレーションごとに同じパラメータを定義する必要があり、一元的に管理できない。

ホスト紐付管理メニューのオペレーションを空にすると、すべてのオペレーションに継承させることが可能です。

**Comment by ta-matsuo** [comment]
> Ansible-Legacyの作業対象ホストにおいて、オペレーションとMovementとホストを関連付けづけることで、パラメータシートでオペレーションの指定を行わなくても、対象ホストに関連するパラメータシートを変数に代入できるようにしてほしい。

ITAの仕様としては、代入値自動登録＋パラメータシートにデータを登録することにより、作業対象ホストと代入値管理には自動的にデータが登録される作りになっています。
ご記載の案は、代入値自動登録＋パラメータシート（オペレーション無し）＋作業対象ホストにデータを登録することにより代入値管理にデータが代入されるということでよろしいでしょうか。
その場合、作業対象ホストに登録する分、作業の操作が増えるため採用は難しいです。

**Comment by shigeki-m** [comment]
> ホスト紐付管理メニューのオペレーションを空にすると、すべてのオペレーションに継承させることが可能です。
ホスト紐付管理メニューのオペレーションを空にしても、パラメータシート（「入力用」メニューグループ）で親ホストグループと子ホストグループ/ホストで、同じオペレーションにしなければ、親ホストグループから子ホストグループへパラメータを継承できませんでした。

**Comment by shigeki-m** [comment]
> ITAの仕様としては、代入値自動登録＋パラメータシートにデータを登録することにより、作業対象ホストと代入値管理には自動的にデータが登録される作りになっています。
ご記載の案は、代入値自動登録＋パラメータシート（オペレーション無し）＋作業対象ホストにデータを登録することにより代入値管理にデータが代入されるということでよろしいでしょうか。

要望はご認識の通りです。

>その場合、作業対象ホストに登録する分、作業の操作が増えるため採用は難しいです。

パラメータシート（「入力用」メニューグループ）の「オペレーション」を使用して作業対象を決定する方が簡単な場合と、作業対象ホストとMovementを指定して必要なパラメータをパラメータシート（オペレーションなし）から集めてくる方が簡単な場合、のどちらの状況もあるかと思います。
作業対象を簡単に切り替えたい場合やオペレーションによって作業対象の組み合わせを変えたい場合、等は後者の方が容易になるので要望を上げさせて頂きました。※作業対象を変更するために、パラメータシート（「入力用」メニューグループ）の「オペレーション」を変更していく作業は、パラメータが多い場合大変であり、また、オペレーションごとに同じ値のパラメータシートを作るのも管理が複雑化してしまうため。

**Comment by ta-matsuo** [comment]
> ホスト紐付管理メニューのオペレーションを空にしても、パラメータシート（「入力用」メニューグループ）の親ホストグループと子ホストグループ/ホストで、同じオペレーションにしなければ、親ホストグループから子ホストグループへパラメータを継承できませんでした。

ホスト紐付管理メニューのオペレーションは、親子の紐付をどのオペレーションに適用させるかを定義しているのであって、同一オペレーション内でホストグループの値を継承するという仕様には影響しません。
オペレーションに関わらず同じ値を使用したいということであれば、「Ansible共通」-「グローバル変数管理」を使用してください。

**Comment by shigeki-m** [comment]
>オペレーションに関わらず同じ値を使用したいということであれば、「Ansible共通」-「グローバル変数管理」を使用してください。

同じホストグループでれば、オペレーションに関わらず同じパラメータを使用し、
異なるホストグループでは異なるパラメータを設定したいので、「グローバル変数管理」とはマッチしません。

すいません。オペレーションの使い方について、
ExastroITAの設計思想と考え方が合わないのかもしれませんね。
