### ISSUE TITLE
【全般】独自フォーマット編集Excelにscsvのデータファイルをマクロで取り込む際に、失敗するケースがある

### ISSUE THREAD

**Issue by ojima-nobuya** [exastro-suite/it-automation#1934]
独自フォーマット編集Excelにscsvのデータファイルをマクロで取り込む際に
メニュー項目名が以下のようになっている場合、
scsvの中の項目名と編集用Excelマクロの項目名が不一致と判断され
読み込み失敗のエラー「Columns of SafeCSV file does not accord with columns worksheet.[2]」が出力される。

・項目名の先頭にシングルコーテーションが含まれている
・項目名に数値として扱われるものが入っている(※以下例を参照)

(例)
整数：1、2、3
少数：1.23

**Comment by a-koizumi** [comment]
上記事象履歴も起きるので対応する。
