### ISSUE TITLE
v1.10.1 の Tag 名が変わっているため、インストールマニュアル記載の手順でエラーとなる

### ISSUE THREAD

**Issue by dai-kagino** [exastro-suite/it-automation#1987]
タグ名が以下のように変わっているようです。
（v1.10.1_tag のように、タグ名末尾に '_tag' 付与されている）

| Version | Tag Name |
| -------- | ----------- |
| 1.9.1 | v1.9.1 |
| 1.10.0 | v1.10.0 |
| 1.10.1 | v1.10.1_tag |

この結果 tar.gz ファイル格納パス、および解凍した際のフォルダ名が以下のように変わっており、インストールマニュアル通りの指定ではエラーとなります。

tar.gz ファイル格納パス
　https://github.com/exastro-suite/it-automation/releases/download/v1.10.1_tag/exastro-it-automation-1.10.1.tar.gz
解凍時フォルダ名
　it-automation-1.10.1_tag/

大きな問題ではありませんが、念のためご指摘まで

**Comment by ta-matsuo** [comment]
GitHubの仕様が変わったらしく、ブランチ名と同じタグ名がつけられなくなりました。
そのため、今回からリリース時のタグ名を「（バージョン）_tag」という名前にしております。
v1.10.1以降は資材のダウンロードのURLが変更になることを以下のマニュアルに記載済みです。

https://exastro-suite.github.io/it-automation-docs/asset/Learn_ja/ITA-online-install_ja.pdf
14ページ

**Comment by dai-kagino** [comment]
ご教示いただきありがとうございます。

ちなみにですが、以下についてもタグ名の影響を受けているように思われます。
（これも大した問題ではなく申し訳ありません。）
Page14
■ディレクトリ移動
　⚫ 環境構築を設定を行うアンサーファイルとシェルのあるディレクトリに移動します。
　　　# cd it-automation-x.x.x/ita_install_package/install_scripts

v1.10.1 以降は
　　　# cd it-automation-x.x.x_tag/ita_install_package/install_scripts

**Comment by ta-matsuo** [comment]
ご指摘の箇所も修正が必要だったため、マニュアルを修正いたしました。

**Comment by dai-kagino** [comment]
ありがとうございます、お騒がせいたしました。
