### ISSUE TITLE
【ロールベースアクセス制御】データレコードのアクセス権にロールを割り当てる際に、ログインユーザが紐づけられていないロールも指定できるようにしてほしい。

### ISSUE THREAD

**Issue by shigeki-m** [exastro-suite/it-automation#1989]
例えば、特権ロール？（特権アカウントのようなもの）を作って、特権ロールにはすべてのデータレコードへのアクセスを許可したい場合、現状はログインユーザが特権ロールに紐づいていないと特権ロールを指定することができないと思われるため。

**Comment by sinatommy** [comment]
今後のITAのロードマップとして、OrganizationやWorkspaceの概念を取り入れていく方針となっております。そのため、Workspace毎でのアクセス制御になっていきますので、データレコード単位のアクセス制御は無くなる方向です。
