### ISSUE TITLE
【Conductor】Symphonyの呼出を追加

### ISSUE THREAD

**Issue by ta-matsuo** [exastro-suite/it-automation#199]
ConductorからSymphonyを呼び出せるようにする。

**Comment by y-yonekura** [comment]
■画面（表示）
・Symphony callの追加（≒Conductor call）
	-Functionに「Symphony call」の追加
	-Symphony callの入力、選択項目追加

■画面（処理）
・Symphony callのクラス登録処理
・Symphony callのインスタンス登録処理
・描画関連パラメータ取得

■バックヤード
・Symphonycallの動作処理追加（実行、緊急停止）
