### ISSUE TITLE
機器一覧の登録・更新処理に時間を要する。

### ISSUE THREAD

**Issue by d-miyata** [exastro-suite/it-automation#1996]
機器一覧に約16000件登録している状況において、1件の新規登録・更新処理(Rest)に時間を要するので改善してほしい。

【登録処理】
![image](https://user-images.githubusercontent.com/98794628/197944807-25a7538b-04bf-4dcc-a53c-084cd8e5b542.png)

【更新処理】
![image](https://user-images.githubusercontent.com/98794628/197944874-a63fb3df-02bc-4973-869d-be2091d2baad.png)

**Comment by d-miyata** [comment]
【更新処理】
◆修正したソース
/exastro/ita-root/libs/webcommonlibs/table_control_agent/07_TableIUbyFIle.php
1208行目と1209行目の間に下記の3行を追加

$aryObjColumn = $objTableTmp->getColumns();
$objRIColumn = $aryObjColumn[$objTableTmp->getRowIdentifyColumnID()];
$objRIColumn->setSearchType("in");

◆修正内容
RestAPIの更新では、項目のキーが無い場合でも更新できるようにしていたが、キーが無い場合はそのレコードを取得して穴埋めしている。
そのレコードの取得が既存の関数dumpDataFromTableを使って検索しているが、何も指定しないと検索キーで与えたプライマリキー以上のデータで検索されるという作りになっていた。
検索を以上ではなく一致で検索するようにソースを修正。


【登録処理】
◆修正したソース
/exastro/ita-root/libs/webcommonlibs/table_control_agent/07_TableIUbyFIle.php
1201行目を下記のように修正

修正前
if(isset($inputArray[$strPrimaryKeyName]))
↓
修正後
if(isset($inputArray[$strPrimaryKeyName]) && $inputArray['ROW_EDIT_BY_FILE'] != $g['objMTS']->getSomeMessage("ITAWDCH-STD-12202"))

◆修正内容
RestAPIで登録の際、下記のようにcontentパラメータにてSYSTEM_ID(項番)の値を空として実行すると、
更新処理と同様に登録処理でもレコードを検索する関数dumpDataFromTableが実行され、処理に時間を要していた。

{
  "0" : "登録" ,
  "1" : "" ,
  "2" : "" ,  ←SYSTEM_IDを空で指定
・・・（中略）・・・

登録処理ではレコードの取得処理が実行されないようにソースを修正。

**Comment by t-uekawa-n** [comment]
https://github.com/exastro-suite/it-automation-dev/pull/1
