### ISSUE TITLE
【メニュー作成】パラメータシートに対する参照RestAPIについて、 bodyのFILTER検索にLISTを指定した際に、完全一致条件となるはずの文字が 一部無視された形で完全一致検索される

### ISSUE THREAD

**Issue by y-masaya3210** [exastro-suite/it-automation#1998]
パラメータシートに対する参照RestAPIについて、bodyのFILTER検索にLISTを指定した際に、完全一致条件となるはずの文字が一部無視された形で完全一致検索となってしまっている。

検証①
オペレーションIDに対しての検索
{ "1": { "NORMAL": "0" }, "4": { "LIST": ["1:OP1"] } }
⇒IDが一致すると取得できてしまう。

検証②
オペレーション名に対しての検索
{ "1": { "NORMAL": "0" }, "5": { "LIST": ["OP1"] } }
⇒オペレーション名で取得できなかった。

検証③
オペレーション名に対してオペレーションIDで検索
{ "1": { "NORMAL": "0" }, "5": { "LIST": ["1"] } }
⇒取得できてしまっている。

**Comment by ta-matsuo** [comment]
数値カラムやIDカラムのLIST検索の場合、数値以外の値で検索されたらエラーになるように修正する。
