### ISSUE TITLE
作業実行の定期設定

### ISSUE THREAD

**Issue by m-takahashi-if** [exastro-suite/it-automation#20]
作業実行を定期的に実行できるように設定したい。月一回キャパデータ取得とか。

**Comment by sinatommy** [comment]
テーブル設計着手

**Comment by HibikiNanri** [comment]
①テーブル/処理の設計 90%
②ページ/登録処理の作成 20%　←進行中
③backyard処理の作成 0%
④試験 0%

**Comment by HibikiNanri** [comment]
カレンダー（定期パターンを設定する）素材を探す。

**Comment by HibikiNanri** [comment]
メモ：
定期パターンの素材がなかったので自作します。
・ボタン押すとモーダルでパターン設定メニューをオープン
・パターン選択して決定ボタン押すと「登録」の各欄に値をセット

進捗：
①テーブル/処理の設計 90%
②ページ/登録処理の作成 40%
③backyard処理の作成 0%

**Comment by HibikiNanri** [comment]
メモ：
パターン設定メニュー作成完了。
→確認と細かい修正を予定。

進捗：
①テーブル/処理の設計 90%
②ページ/登録処理の作成 70%
③backyard処理の作成 0%

**Comment by HibikiNanri** [comment]
メモ：
・基本的にモーダル上でしかパターンを入力できない仕様（更新時も同様）
・作業の停止期間を指定するカラムを作る
・周期で「月末」を専用に作る
・「作業が失敗したときに次回の処理を登録しない機能」については、v1.4では見送り
・backyardの処理としては（v1.4段階では）作業実行予定日前にsymphoney作業一覧に登録するだけ（登録したあとのことは関与しない）

**Comment by HibikiNanri** [comment]
以下を機能として追加/修正
・モーダルで周期を選択したタイミングで間隔や時間などの中身を空にする。
・Symphony作業一覧へジャンプするリンクボタンを設置する
→ジャンプ先でフィルターで対象のシンフォニー/オペレーションのIDを検索してその結果のみを一覧表示したい
・シンフォニー廃止などで登録処理が失敗した場合、それ専用のステータスを用意する。
・上記に伴い（例えば）シンフォニー廃止して失敗したものについて、シンフォニーを復活させたときに再度動き出すようにしたい。
・サーバ停止などで「次回実行日付」のタイミングにSymphony作業一覧に作業を登録できなかった場合、その作業はスキップして次から作業登録するように。

**Comment by HibikiNanri** [comment]
symphony作業一覧に登録する処理を共通化する

**Comment by HibikiNanri** [comment]
・修正したファイルを適用させて、再インストールを実施する。

**Comment by HibikiNanri** [comment]
・backyard処理の間隔は10秒
・Symphony作業一覧への登録は「次回実行日付」の3分前に行う

**Comment by HibikiNanri** [comment]
・登録した時点のステータスを「準備中」に（もともとは空欄）
・symphony作業一覧への登録が失敗したときは「紐付けエラー」とする。
→「紐付けエラー」のレコードも「稼働中」と同様の扱いで次回の処理を登録しに行く。

**Comment by HibikiNanri** [comment]
払戻し完了
