### ISSUE TITLE
【収集機能】Ver1.10.1で収集結果が空(全てNULL)だと対象ホスト割当てが行われない（ITA1.10.0では問題無し）

### ISSUE THREAD

**Issue by dai-kagino** [exastro-suite/it-automation#2003]
掲題の通り、Ver1.10.1 でのデグレードと思われる事象が発生しております。
ご確認お願いいたします。

**Comment by dai-kagino** [comment]
(1) chrony がインストールされていない対象サーバから、chrony に関する情報の収集を実施します。
　　※ 収集実行前は、パラメータ・構築ロールへの対象ホストの紐づけは行われておりません。
![ITA1 10 0_01_収集前_パラメータシート](https://user-images.githubusercontent.com/57690977/194206413-074a913d-3b80-4d62-a552-b8aefe24d58f.png)
![ITA1 10 0_02_収集前_作業対象ホスト](https://user-images.githubusercontent.com/57690977/194206422-bc6e1e7b-7987-4bee-b436-1e959144952c.png)
![ITA1 10 0_03_収集実行](https://user-images.githubusercontent.com/57690977/194206438-0e17c646-a102-4a93-9558-2137f2097562.png)

**Comment by dai-kagino** [comment]
(2) ITA1.10.0 の場合、収集後の状態は以下のようになっています。
　　※ パラメータにはNULLデータが登録され、
　　　 対象ホストで構築ジョブに対するホストの紐付けが行われている状態（赤枠部）
![ITA1 10 0_04_収集後_パラメータシート](https://user-images.githubusercontent.com/57690977/194206802-b990e817-08fa-43ff-83c0-5d22f9295284.png)
![ITA1 10 0_05_収集後_作業対象ホスト](https://user-images.githubusercontent.com/57690977/194206813-1a2ea990-47ae-40c3-91a9-ffd758ec1e4e.png)

**Comment by dai-kagino** [comment]
(3) しかし、同じ操作を ITA1.10.1 で実施した場合、収集後の状態は以下のようになっています。
　　※ パラメータにはNULLデータが登録されているが、
　　　 構築ジョブに対するホストの紐付けは行われていない。
![ITA1 10 1_06_収集後_パラメータシート](https://user-images.githubusercontent.com/57690977/194207126-127c7e60-bec1-4ba6-9d56-e85ea19b51ee.png)
![ITA1 10 1_07_収集後_作業対象ホスト](https://user-images.githubusercontent.com/57690977/194207134-3618caa3-3534-4ede-9f66-63d656d8849f.png)

**Comment by dai-kagino** [comment]
発生環境は維持しておりますので、情報採取等必要であればご連絡ください。

**Comment by sinatommy** [comment]
v1.10.1で機能追加した下記issueのため、このような動作になっております。
[【メニュー作成】縦型メニューをNULL連携有効で代入値自動登録した場合の動作の見直し #1941](https://github.com/exastro-suite/it-automation/issues/1941)

動作についてはマニュアルをご確認ください。
[Exastro-ITA_利用手順マニュアル_Ansible-driver](https://exastro-suite.github.io/it-automation-docs/asset/Documents_ja/Exastro-ITA_%E5%88%A9%E7%94%A8%E6%89%8B%E9%A0%86%E3%83%9E%E3%83%8B%E3%83%A5%E3%82%A2%E3%83%AB_Ansible-driver.pdf)
P70
5.3.9　代入値自動登録設定
(7)パラメーターシート（縦メニュー）

**Comment by dai-kagino** [comment]
ご確認ありがとうございます。

ただ、実際にNULLが代入されているのは事実ですので、それに伴って「対象ホストの紐付け」についても行われるのが妥当ではないでしょうか？
（すみません、#1941 の具体的な仕様変更内容がうまく呑み込めていないので的外れかもしれません。）

ちなみに本件が仕様変更で有った場合、利用者による「収集→構築」の流れに以下のような影響が懸念されます。
（すみません、まだ実機確認できていませんので、確認後結果記載させていただきます。）

・ITA1.10.0
　　収集用Symphony実行後に、一部パラメータを修正し、構築用Symphonyを実行
　　→ Symphonyが正常終了し、修正したパラメータがターゲットマシンに反映される
・ITA1.10.1
　　収集用Symphony実行後に、一部パラメータを修正し、構築用Symphonyを実行
　　→ 収集データがNULLのMovementについて、ホストの紐づけが行われないため、
　　　構築用Symphonyが当該Movementでエラー停止。

もし想定通りの挙動となった場合回避策の提示が必要と思われますが、どのように
対応するのが妥当でしょうか

（収集後に全ての収集データをチェックしNULLのものがあれば、該当するMovementに
　ついて手動で対象ホスト紐付けを行う、で回避はできると思いますが、あまり現実的で
　ない気がします・・・。）

**Comment by dai-kagino** [comment]
本件ですが、収集後にNULLデータを設定する際以外では顕在化しない可能性が高いとのことで、
以下注意事項を記載することで回避を行う方針とさせていただきます。
------
ITA 1.10.1 以降ご利用の場合は、ITA仕様の変更によりこういったエラーが起きる可能性がある。
その場合、ｘｘｘｘという手動操作で紐づけを行ってください」
------

**Comment by sinatommy** [comment]
承知致しました。よろしくお願い致します。クローズさせて頂きます。
