### ISSUE TITLE
【Ansible-Driver】暗号化項目対応

### ISSUE THREAD

**Issue by ta-matsuo** [exastro-suite/it-automation#202]

**Comment by enoman** [comment]
紐付対象メニュー・カラムの刈取
代入値自動登録設定
作業実行

**Comment by enoman** [comment]
以下の順で作業着手
1.紐付対象メニュー・カラム刈取のホストなしメニュー・PasswordColumnの対応
2.代入値自動登録のPasswordColumnの対応
3.作業実行のPasswordColumnの対応
4.pioneerモジュールのPasswordColumnの対応

懸念実行
ansible-vaultでの暗号化が遅い
1ワード暗号化するのに、1~2秒位かかる。
高速化する手段がないか、サポートに問い合わせ。

**Comment by enoman** [comment]
完了

**Comment by enoman** [comment]
サポートにansible-vaultの暗号化の高速化手段を確認したところ
高速化の手段はないとの回答

大変恐縮なのですが、現在のところご案内できる高速化の手段はありません。
暗号化の処理はCPUを多く消費しますので、性能に支障がある場合には高速なものをお使いになることをご検討ください。

また、復号化の高速化の手段として
ansible(Tower)のインストール時に cryptography（python package）がデフォルトでインストールされている。

**Comment by a-koizumi** [comment]
【Ansible-Driver】暗号化項目対応 #202 
ansibleで高速化する手段がないので
【復号化の能力を時間計測結果(暗号化している変数数を0,50,100位)】
（各変数の具体値が同じにしない）

　変数数を0・・  6秒
　変数数を1・・  1分半
　変数数を50・・ 2分半
　変数数を100・・5分
