### ISSUE TITLE
【インストーラ】インストールの親ディレクトリに実行権限がついていない場合は警告終了する

### ISSUE THREAD

**Issue by j-kumamoto** [exastro-suite/it-automation#204]
インストールディレクトリの改修を行う。
インストール対象の親ディレクトリに実行権限がついていない場合は警告終了する。

Apacheユーザで実行権限が必要、以下のようなディレクトリ配下が警告対象となる。
dr-xr-x---. ~ /root
drwx------. ~ /home/ec2-user

**Comment by h-matsuhashi** [comment]
仕様
1．ITAインストールディレクトリの存在を確認する。
　※ITAインストールディレクトリがない場合はWARNINGを表示。（要確認）
2．アンサーファイルのita_directory:から、ITAディレクトリの親ディレクトリのパスを取得して、チェック用変数に代入。
3．取得した親ディレクトリの権限を確認する。
　※Othersの権限の中に実行権限"x"がなければ異常終了。
4．3.でチェックしたディレクトリの親ディレクトリのパスを取得して、チェック用変数に代入。
5．チェック用変数のパスが"/"になるまで、3～4を繰り返す。
6．ルートディレクトリの権限を確認する。
　※Othersの権限の中に実行権限"x"がなければ異常終了。

**Comment by h-matsuhashi** [comment]
マージ済。
