### ISSUE TITLE
【インストーラー】Gather_Libraryでphpのパッケージが正しくダウンロードされない

### ISSUE THREAD

**Issue by HibikiNanri** [exastro-suite/it-automation#2044]
OS: CentOS8
Gather_Libraryを実行した際、ダウンロードディレクトリにphp:7.4のrpmがダウンロードされておらず、php:7.2のrpmが格納されている。

ita_gather.logには以下のエラーが出力されています。
`dnf module: error: unrecognized arguments: --resolve php:7.4`

**Comment by ta-matsuo** [comment]
CentOS8は動作要件にはいっていないため、RHEL8とCentOS8 streamに対して対応を行う。
RHEL8とCentOS8 streamの場合、Gather_Libraryで収集されるPHPのRPMが7.2のバージョンになっていたため、7.4が収集されるように修正する。
RHEL7とCentOS7の場合は問題なし。
