### ISSUE TITLE
Ansible・Terraformドライバ別配置しプル型でジョブを実行取得・実行できるようにしてほしい

### ISSUE THREAD

**Issue by takeo-e** [exastro-suite/it-automation#2066]
## 背景

別のネットワーク上にITAと作業対象が配置されている場合、Ansible や Terraform ドライバから作業対象のノードにアクセスすることが通信要件上難しい事が多々ある。

## 解決策

ITA→エージェント(ドライバ) の通信方向ではなく、
エージェント(ドライバ)→ITAへの通信方向となるようなプル型でジョブ情報を取得する構成にして欲しい。

**Comment by sinatommy** [comment]
2系にて対応する。
