### ISSUE TITLE
【インストーラ】MariaDB v11.0.2での警告文でバージョンアップ処理が途中停止する。

### ISSUE THREAD

**Issue by sinatommy** [exastro-suite/it-automation#2083]
MariaDBのv11.0.2において、「mysql」コマンドが非推奨となり、下記警告が表示されるようになった。

> mysql: Deprecated program name. It will be removed in a future release, use '/usr/bin/mariadb' instead

ITAのバージョンアップを実施した際に、警告文がエラーログに出力され、処理が途中で停止してしまう。

**Comment by ta-matsuo** [comment]
mysqlコマンドを使用している箇所をすべてmariadbコマンドに変更する。
mysqldumpコマンドを使用している箇所をすべてmariadb-dumpコマンドに変更する。
