### ISSUE TITLE
【Conductor】作業詳細画面からの画面遷移方法の改善

### ISSUE THREAD

**Issue by y-yonekura** [exastro-suite/it-automation#209]
Movement,Conductor callノードを選択→Operation status :のリンク押下で別タブで画面遷移するのと
同様に、「ダブルクリック」、「ステータス表示の〇部分の押下」等の操作した際に、別タブで開くようにする。

**Comment by sinatommy** [comment]
「ステータス表示の〇部分の押下」で別タブにて画面遷移可能。（「ダブルクリック」は無し）
