### ISSUE TITLE
【インストーラ】マニュアルインストール手順

### ISSUE THREAD

**Issue by m-takahashi-if** [exastro-suite/it-automation#21]
ver1.3のインストーラでansibleをインストールするとPython3になるので注意。
マニュアルインストール手順が欲しい。

**Comment by sinatommy** [comment]
簡易手順は来週作成完了予定

**Comment by sinatommy** [comment]
簡易手順書は完成。
整形する。

**Comment by h-matsuhashi** [comment]
5/25
初版完成。加藤さんにコミュニティサイト、Learnページへの公開作業依頼中（松尾さんより）。

名子さんによるHA環境構築手順検証作業中（5/28～）
