### ISSUE TITLE
【メニュー作成】ホストなしパラメータシートの値をホストありパラメータシートで引用できる機能

### ISSUE THREAD

**Issue by ta-matsuo** [exastro-suite/it-automation#211]
メニュー作成時に、ホストありパラメータシートからホストなしパラメータシートの値を引用する設定を追加する。
値を引用するときは、同一オペレーションの値を取得する。

**Comment by HibikiNanri** [comment]
マージ済み。
要ドキュメント修正。

**Comment by HibikiNanri** [comment]
## 機能
- メニュー作成の「入力方式」に「パラメータシート参照」を追加

「パラメータシート参照」は「作成対象」を「パラメータシート（オペレーションあり）」で作ったメニューの項目を選択し、データを登録した際に指定したオペレーションと一致する項目のレコードを参照する機能です。


以下のような「パラメータシート（オペレーションあり）」で作成したメニューがある場合
![211-1](https://user-images.githubusercontent.com/51319083/134299918-7966cdc4-61b7-4f10-ab5a-b45ae0c719e5.png)

「パラメータシート参照」でメニュー/項目を指定できるようになります。以下は例として「項目 1」を指定します。
![211-2](https://user-images.githubusercontent.com/51319083/134300055-df953d97-c2d2-4963-826a-e2e0993308da.png)

「パラメータシート参照」で指定したメニュー/項目の値を参照する形で項目が作成されます。
参照する値は、登録したデータと同一のオペレーションのものが採用されます。
![211-3](https://user-images.githubusercontent.com/51319083/134300559-a7911649-304d-4152-b9ec-6d8811a52d6f.png)

## 仕様
- 「パラメータシート参照」項目は「作成対象」が「データシート」の場合は利用できません。
- 「パラメータシート参照」項目で選択できる参照元の項目の種類（入力方式）は以下となります。
「文字列(単一行)」「文字列(複数行)」「整数」「小数」「日時」「日付」「パスワード」「ファイルアップロード」「リンク」
ただし、「ファイルアップロード」を参照した場合はアップロードしたファイルの「ファイル名」のみの参照となります。（アップロードしたファイルのデータ自体は参照されません。）
- 「パラメータシート参照」項目のデータは、クリックすることで参照元のメニュー（代入値自動登録用のメニュー）へ遷移できます。

- 「パラメータシート参照」項目を利用したメニューで登録したデータについて、指定したオペレーションが参照元のメニューのデータに無い場合は『ID変換失敗(オペレーションID)』という表示になります。
