### ISSUE TITLE
【メニュー作成】メニューの更新をした場合にデータを残す

### ISSUE THREAD

**Issue by sinatommy** [exastro-suite/it-automation#212]

**Comment by HibikiNanri** [comment]
■画面構成
[メニュー定義一覧]から[メニュー定義/作成]へ遷移したとき、「編集」「流用新規」とは別にもう一つ「編集（データ引継ぎ）」ボタンを追加する。（名前は要検討）
上記ボタンからメニュー定義の編集を行う際、以下の項目を変更不可とする。
・既存/新規追加カラムでの「必須」項目
・既存/新規追加カラムでの最大バイト数、最小値/最大値
・作成対象
・ホストグループ利用のチェックボックス
・縦メニュー利用のチェックボックス
※入力必須のカラムやデータのバイト上限などを変更した状態でデータを引き継ぐと不整合が起こってしまうため。

また、「編集」か「編集（データ引継ぎ）」かは[メニュー作成履歴]ページを管理するテーブルにカラムを追加して、どちらのモードでメニューを編集しているかを管理する。

**Comment by HibikiNanri** [comment]
■修正案
既存の「編集」を「初期化」として、
「編集(データ引継ぎ)」を「編集」とボタンを変える。

**Comment by HibikiNanri** [comment]
「メニュー作成実行」ページでは、
「メニュー作成開始(新規作成)」と「メニュー作成開始(編集)」のボタンでメニュー作成の種類を選択できるように。
・「メニュー作成開始(新規作成)」時、すでにメニューがある場合はメニュー作成タイプを「初期化」に、無い場合は「新規作成」に
・「メニュー作成開始(編集)」時、すでにメニューがある場合はメニュー作成タイプを「編集」に、無い場合は「新規作成」に

**Comment by HibikiNanri** [comment]
マージ済み。
要ドキュメント修正。
