### ISSUE TITLE
【インストーラ】sh ita_builder_online.shで失敗した際の戻り値が0

### ISSUE THREAD

**Issue by hseiyo** [exastro-suite/it-automation#217]
yum installなどで失敗した場合にfunc_exitが呼ばれますが、戻り値が設定されていないために常に戻り値が0となってしまいます。
Exastro ITAのインストールをスクリプト化する際に、正常にインストールできたか判定できません。
異常終了した場合に0以外の戻り値を設定して頂きたいです。

**Comment by sinatommy** [comment]
ご指摘ありがとうございます。v1.6にて対応致します。

**Comment by h-matsuhashi** [comment]
仕様
・ita_installer.shにエラーフラグを追加。（初期値:true）
・インストーラーの処理中に異常終了となる場合は、エラーフラグをfalseにする。
・インストーラーでのシェルの終了時に終了用関数に飛ぶように統一。
・終了用関数に飛んだ時にエラーフラグの値によって終了ステータスを変更する。
　true：0（正常終了）
　false：1（異常終了）

**Comment by h-matsuhashi** [comment]
実装作業は完了。動作確認中。
