### ISSUE TITLE
【基本コンソール】機器一覧のAnsible利用情報の追加オプションにCiscoIOS特権モードのパスワードを暗号化して登録したい。

### ISSUE THREAD

**Issue by j-kumamoto** [exastro-suite/it-automation#227]
●課題
AnsibleでCiscoIOS機器への特権モードに入る際、ITAのAnsible利用情報の追加オプションにパスワードを平文で書き込む必要がある。

例：
ansible_connection: network_cli
ansible_network_os: ios
ansible_become: yes
ansible_become_method: enable
ansible_become_password: password

●改善要望
Ansible利用情報の追加オプションにもパスワードカラム等の暗号化の対応が可能にして欲しい。

●補足（回避方法について）
playbook に直接特権モードに入る許可とパスワードを書き込むことでも実行できる。
ITA1.6.0のメニューのパスワードカラム対応が完成すれば、パラメータシートを作成することで、
平文で書き込むことを回避できると思われる。
ただ、playbook に書き込む方法は Ansible2.5 以降では非推奨となっているので注意。

**Comment by enoman** [comment]
インベントリオプションの記述例
ansible_connection: network_cli
ansible_network_os: ios
ansible_become: yes
ansible_become_method: enable
ansible_become_password: '{{ VAR_password }}'

変更点
変数刈り取り/作業実行
Legacy:  
　・刈り取った変数は key-value型の変数として扱う
　・作業実行士時、代入値管理に代入値の登録がない場合、代入値登録がないメッセージを表示
　　※他変数の代入値未登録と同じ扱い

Role:
　・刈り取った変数は key-value型の変数として扱う
　・変数型の優先順位
　　他ファイルの変数型　＞ インベントオプション
　　　他ファイルで key-value型以外の変数定義があった場合
　　　他ファイルの変数型を採用
　　　作業実行時、変数型がkey-value型以外の場合、変数型に問題があるメッセージを表示
　・代入値管理の登録有無は判定しない。
　　※Roleは代入値管理の登録有無は判定していないので、同じ扱い。
Pioneer:
　・インベントリオプションは使用していないので今まで通り。変更なし

**Comment by enoman** [comment]
完了
