### ISSUE TITLE
【Ansible-Driver】「進行状況(実行ログ)」「進行状況(エラーログ)」のタイトルバーを押下するとログが消えます。

### ISSUE THREAD

**Issue by a-koizumi** [exastro-suite/it-automation#228]
[手順]
１．各処理の作業実行を行う。
２．正常時は進行状況(実行ログ)、エラー時は進行状況(エラーログ)にログ表示されていることを確認する。
３．「進行状況(実行ログ)」「進行状況(エラーログ)」のタイトルバーを押下する。
４．タイトルバー押下時、ログが消えます。
（再表示すると復活し表示されます。）
Terraformは消えません

**Comment by enoman** [comment]
完了
