### ISSUE TITLE
メニュー管理と代入値自動登録のステータスが非同期問題

### ISSUE THREAD

**Issue by sinatommy** [exastro-suite/it-automation#24]
メニュー管理から廃止を行っても、代入値自動登録設定のプルダウンに表示されてしまう。

**Comment by sinatommy** [comment]
【対処方針】

・「メニュー管理」からメニューを「廃止」した場合、「紐付対象メニュー」に対象メニューIDがあり、「廃止」ではない場合は廃止する。

・「メニュー管理」からメニューを「復活」した場合、「紐付対象メニュー」に対象メニューIDがあり、「廃止」の場合は復活する。

**Comment by ta-matsuo** [comment]
#57と同件のためクローズ。
