### ISSUE TITLE
【Ansible-Driver】ホスト名を「localhost」にするとPioneerがUnreachableでエラーになる

### ISSUE THREAD

**Issue by ta-matsuo** [exastro-suite/it-automation#245]

**Comment by enoman** [comment]
インベントリファイルに
ansible_connection: local
を追加することでエラーは解決するが
ITAのサーバーにpexpectモジュールのインストールが必要

**Comment by enoman** [comment]
いろいろ調査した結果、下記の5案の何れかで対応したい。
①サーバとしてのPyhonをPython3にかえる（RHEL7系ではyumが使えなくなる）
②RHEL7系の場合、Python2にpexpectをインストールするようにする。
③Pioneerではホスト名にlocalhostを使えない。localhost利用時はサーバのPythonをPython3に変更する旨をQ&Aに書く。
④対話ファイルでpythonのバージョン指定「/usr/bin/python3」を追記する。
　固定にするのも・・ /usr/bin/python3を何処かに記録
⑤機器一覧のインベントリ追加オプションに下記を追加することでソフト改修なしで対応可能。オプション追加の旨をQ&Aに書く。
   ansible_connection: local
   ansible_python_interpreter: /usr/bin/python3

**Comment by sinatommy** [comment]
Pioneerの場合、「ansible_connection: local」を追加するように改修する。
FAQに⑤の「ansible_python_interpreter: /usr/bin/python3」追加対応を記載する。

**Comment by enoman** [comment]
完了
