### ISSUE TITLE
【Conductor】Conductor作業一覧からのInput/Resultデータ取得機能追加

### ISSUE THREAD

**Issue by a-koizumi** [exastro-suite/it-automation#252]
Conductor作業一覧から実行したMovementのInputdataとResultdataを取得できるようにする。

**Comment by Satoshi-asano** [comment]
Symphony同様に、ボタンを押したら作成する。→DL処理後、作成したZIPファイルを削除

ZIPファイルディレクトリ構成

inデータ
zipファイル名
InputData__Conductor_ConductorインスタンスID(10桁).zip

ディレクトリ構成
Conductor内通番(10桁)/InputData_作業番号(10桁).zip
InputData_作業番号(10桁).zip:各Movement(ansible作業実行)で作成している zipファイル名

outデータ
zipファイル名
ResultData_Conductor_ConductorインスタンスID(10桁).zip
ディレクトリ構成
Conductor内通番(10桁)/ResultData_作業番号(10桁).zip
ResultData_作業番号(10桁).zip:各Movement(ansible作業実行)で作成している zipファイル名

<<例>>
Symphonyクラス ID:1
Movementが2個あった場合
1.legacy 作業番号100
2.Legacy-Role　　作業番号200

InputData_Conductor_0000000001.zip
0000000001/InputData_0000000100.zip
0000000002/InputData_0000000200.zip

ResultData_Conductor_0000000001.zip
0000000001/ResultData_0000000100.zip
0000000002/ResultData_0000000200.zip

**Comment by Satoshi-asano** [comment]
任意のConductorに関連する全てのConductorまたはSymphonyを探索し、そのConductor(Symphony)にMovementが存在した場合にInput/Resultデータを収集する。

ZIPファイル例
ConductorクラスID;3
・Movementが2個
-1.Legacy 作業番号100
-2.Legacy-Role作業番号200
・ConductorクラスID:2
-Movementが2個
--1.Pioneer 作業番号300
--2.Trraform作業番号400
-ConductorクラスID:1
--SymphonyクラスID:1
----Movementが2個
------1.Pioneer 作業番号500
------2.Trraform作業番号600

InputData_Conductor_0000000001.zip
0000000001/InputData_0000000100.zip
0000000002/InputData_0000000200.zip
InputData_Conductor_0000000002/0000000001/InputData_0000000300.zip
InputData_Conductor_0000000002/0000000002/InputData_0000000400.zip
InputData_Symphony_0000000001/0000000001/InputData_0000000500.zip
InputData_Symphony_0000000001/0000000002/InputData_0000000600.zip


ResultData_Conductor_0000000001.zip
0000000001/ResultData_0000000100.zip
0000000002/ResultData_0000000200.zip
ResultData_Conductor_0000000002/0000000001/ResultData_0000000300.zip
ResultData_Conductor_0000000002/0000000002/ResultData_0000000400.zip
ResultData_Symphony_0000000001/0000000001/ResultData_0000000500.zip
ResultData_Symphony_0000000001/0000000002/ResultData_0000000600.zip

**Comment by Satoshi-asano** [comment]
↑収集アルゴリズム
[親ノードにぶら下がった子ノード(Conductor)の探索]
①選択された親ノード（C1=ConductorクラスID:1）のConductorインスタンスIDを配列A先頭に格納、セレクターを設定
　Array_A[C1], select=C1
②親ノードに呼ばれた子ノード（C2,C3）のConductorインスタンスIDを発見順に配列Aに順次格納、セレクターをずらす
  Array_A[C1,C2,C3] select=C2
③selectノードに呼ばれたその子ノード(C4)のConductorインスタンスIDを順に配列Aに順次格納、セレクターをずらす
  Array_A[C1,C2,C3,C4] select=C3
④selectノードに呼ばれたその子ノード(なし)のConductorインスタンスIDを順に配列Aに順次格納、セレクターをずらす
  Array_A[C1,C2,C3,C4] select=C4
⑤selectノードに呼ばれたその子ノード(なし)のConductorインスタンスIDを順に配列Aに順次格納、セレクターをずらす
  Array_A[C1,C2,C3,C4] select=NULL
⑥selectがNULLになった時点でノード探索終了、セレクターを初期化
  Array_A[C1,C2,C3,C4] select=C1

[Conductor内のMovementの収集とSymphonyノードの探索]
①selectノードにMovementが存在すればそのInput/Resultファイルを収集
　(親ノードIDとselectが同値でなければzipを格納するディレクトリを新規作成し、新規ディレクトリ上にファイルを格納)
②selectノードにSymphonyが存在すればそのSymphonyインスタンスIDを配列Bに格納
③セレクターをずらす
①～③を配列A要素数分繰り返し

[Symphony内のMovementの収集]
①配列Bに格納されたSymphonyインスタンスIDに関連づいたMovementを収集

**Comment by Satoshi-asano** [comment]
zipファイルが作成されない場合、空白タブ上にアラートを出力、その後タブを消す
