### ISSUE TITLE
【Ansible-Driver】機器一覧のPioneer利用情報が、Legacy/LegacyRoleのファイルに反映される問題

### ISSUE THREAD

**Issue by sinatommy** [exastro-suite/it-automation#26]
基本コンソール＞機器一覧　のPionner利用情報の「プロトコル」の情報が、
Ansible-Legacy、Ansible-LegacyRoleを実行時に作成されるhost_vars配下のファイルに、
不要に記載されてしまう。
Movement実行に影響はない。

[「telnet」入力の場合]
__loginprotocol__: telnet

[空白の場合]
__loginprotocol__: __undefinesymbol__

**Comment by enoman** [comment]
Legacy/Roleは、機器一覧の「プロトコル」が未登録の場合、ホスト変数に__loginprotocol__を記載しないようにします。

**Comment by enoman** [comment]
Legacy/Roleは、機器一覧の「プロトコル」が未登録の場合、ホスト変数に__loginprotocol__を記載しないようにします。

**Comment by enoman** [comment]
完了
