### ISSUE TITLE
【資材管理】管理のインターフェース情報で初期同期する際、空のリポジトリの場合にエラーとなる

### ISSUE THREAD

**Issue by hseiyo** [exastro-suite/it-automation#269]
資材管理 管理のインターフェース情報で初期同期する際、同期先にファイルがコミットされていない空のリポジトリの場合に以下のエラーとなって登録に失敗します。
リポジトリにファイルを追加（commit & push）した後に初期同期すると設定を変えなくても成功します。
エラーメッセージの内容はリポジトリの設定に不備があるように見えますので、メッセージを修正するか、空のリポジトリでも初期同期できるように修正頂くのが良いかと思います。
バージョンは1.5.0です。

リモートリポジトリには以下の設定が必要です。
core.bare=ture
core.sharedrepository=1
push.default=simple

**Comment by ta-matsuo** [comment]
初期同期の中でリモートリポジトリにダミーファイルをPushしてエラーになった場合に上記メッセージを出力しているので、以下のメッセージに変更します。

～～～～～～～～～～～
リモートリポジトリへのPushが失敗しました。
リモートリポジトリにはPush可能なリポジトリを指定してください。
～～～～～～～～～～～

ちなみに、空のリポジトリでも設定次第で初期同期は可能です。
例えば、ITAサーバ上の/workにhoge.gitリポジトリを作成して初期同期する手順は以下となります。

①リモートリポジトリを作成する。
mkdir /work
cd /work
git init --bare hoge.git

②gitの設定を変更する。
git config --global push.default simple

③「インターフェース情報」メニューに以下を設定する。
リモートリポジトリ：/work/hoge.git
クローンリポジトリ：/work/git

④「初期同期」ボタンを押下する。
