### ISSUE TITLE
【Ansible-Driver】AnsibleTower経由のSSH以外の接続対応

### ISSUE THREAD

**Issue by sinatommy** [exastro-suite/it-automation#27]
AnsibleTowerを利用して作業対象サーバに接続する場合、SSH接続以外の接続ができないので、対応する。
例えば、ネットワーク機器にlocal connectionで接続する等。

**Comment by enoman** [comment]
6/15週の定例前後で対応方法を相談したいです。

**Comment by enoman** [comment]
機器一覧にTower認証情報の接続タイプを設定するプルダウンカラムを追加し
以下の2タイプに対応する。
・マシン
・ネットワーク
デフォルトをマシンとする。

**Comment by enoman** [comment]
完了
ansible_connectionをlocalで接続する場合(network_cliも同様)、機器一覧の「インベントリファイル　追加オプション」
に下記のパラメータを設定する必要がある。
ansible_connection: local
ansible_network_os: ios
ansible_become: yes
ansible_become_method: enable

**Comment by enoman** [comment]
完了
ansible_connectionをlocalで接続する場合(network_cliも同様)、機器一覧の「インベントリファイル　追加オプション」
に下記のパラメータを設定する必要がある。
ansible_connection: local
ansible_network_os: ios
ansible_become: yes
ansible_become_method: enable

**Comment by enoman** [comment]
完了
ansible_connectionをlocalで接続する場合(network_cliも同様)、機器一覧の「インベントリファイル　追加オプション」
に下記のパラメータを設定する必要がある。
ansible_connection: local
ansible_network_os: ios
ansible_become: yes
ansible_become_method: enable
