### ISSUE TITLE
【エクスポート/インポート】複数のkymファイルを一つのITA環境に同居できるようにしたい

### ISSUE THREAD

**Issue by UemuraMasumi** [exastro-suite/it-automation#270]
[現状の仕様]
kymファイルをインポートすると共通したメニューのテーブルは
すべてkymファイルのテーブルの値で上書きされる。

インポートの際、対象メニューのテーブルに対して
DROP -> CREATE -> INSERT
を実行している。

[要望]
kymファイルインポート時に、メニューの上書きではなく追加できるようにしたい。
ただし、現状のメニューの内容を上書きする機能も残したいので、
インポート実行画面で、「上書き」or「追加」が選択できるようにしたい。
例)「上書きモード」「追加モード」

[補足]
「追加モード」実行時に、シーケンス番号が重複した際の動作は検討が必要。

**Comment by UemuraMasumi** [comment]
[追記]
案１：
エクスポート実行時に「上書きモード」または「追加モード」を選択してkymファイルを作成する。

案２：
エクスポート実行時に「上書きモード」「追加モード」両方のDBダンプファイルを作成し、
インポート実行時にモードを選択してインポートを実行。

案2のデメリットはエクスポート処理時間とkymファイルの容量の増加。
インポート処理時間はほぼ影響がない。

[案２の影響]
現在のとあるkymファイルでは
解凍後のサイズが22.4MB、ファイル総数が1310個のkymファイルの場合、
そのうちDBダンプファイルはサイズが5.16MBでファイル数は704個。

「追加モード」「追加モード(廃止を除く)」用のDBダンプファイルをkymファイルに格納する場合、
解凍後のサイズが27.56MB、ファイル総数が2014個となる。
(「追加モード」のDBダンプファイルは「上書きモード」のファイルと同サイズと仮定)
サイズは43%、ファイル数は54%の増加となる。

**Comment by hseiyo** [comment]
メニュー以外にもオペレーションも上書きされました。
ほかの項目（movementなど）も同様と思います。

kymファイルのインポートで作成したもの以外が上書きされるのは困ることが多いと思うので、「上書きモード」の場合でも、kymファイルのインポートによって作成されたもののみ上書きするような仕様にしてもらいたいです。

**Comment by ta-matsuo** [comment]
> メニュー以外にもオペレーションも上書きされました。
> ほかの項目（movementなど）も同様と思います。
> 
> kymファイルのインポートで作成したもの以外が上書きされるのは困ることが多いと思うので、「上書きモード」の場合でも、kymファイルのインポートによって作成されたもののみ上書きするような仕様にしてもらいたいです。

現在の仕様（上書きモード）では、インポート時に選択していないメニューに関してはデータは上書きされません。
オペレーションやMovementもメニューで管理されており、「投入オペレーション一覧」や「Movement一覧」メニューがインポートされたため上書きされたと思われます。

**Comment by hseiyo** [comment]
基本的にすべてのデータはメニューに紐づいて管理されているということですね。
理解できました。

**Comment by ayaka-shinomiya** [comment]
[修正点]
・案１で決定
・現状Import時に廃止の有無を選択するようにしているが、追記/上書きモードの追加と合わせてExport時に選択するように統一
・主キーが被った際は、上書き => 後勝ち / 追加 => 先勝ち
・テーブルの構造が違った場合はエラーで終了
・テーブルがなかった場合は構造のみ追加

**Comment by sinatommy** [comment]
REST-APIも対応する。
