### ISSUE TITLE
【Ansible Driver】Roleパッケージを資材紐付け管理（Ansible）で登録した後に、資材の払戻で更新しても、追加したRole名がAnsible-LegacyRoleに自動で反映されない

### ISSUE THREAD

**Issue by hseiyo** [exastro-suite/it-automation#272]
Roleパッケージ（zipファイル）を資材管理の対象として、資材紐付け管理（Ansible）でRoleとして登録した状態で、資材管理の払戻で内容を更新しても、追加したRole名がAnsible-LegacyRoleに自動で反映されません。

Ansible-LegacyRoleのロールパッケージ管理メニューで対象のロールパッケージの更新ボタンを押して、内容を変更せずに更新すると変更した内容が反映されます。
反映されたのを確認したのは、Roleの追加がMovement詳細メニューで選択肢として表示されるという点です。
ロールパッケージの更新をしないと追加したRoleは選択肢として表示されませんでした。
バージョン1.5.0です。

**Comment by ta-matsuo** [comment]
事象確認しました。
修正します。
