### ISSUE TITLE
【Ansible-Driver】機器一覧のパスワードをAnsible-vaultで暗号化処理する際に、対応できない文字がある。

### ISSUE THREAD

**Issue by ojima-nobuya** [exastro-suite/it-automation#289]
機器一覧のログインパスワードに記号「&」を含む文字列を登録し、Symphony実行をしたところ、
ログに『"msg": "input is not vault encrypted data"』と出力され、異常完了する。
（上記の記号を含まない文字列にパスワードを変更し、再登録したところ正常終了した。）

Ansibleの投入データを確認するとhost_varsファイルの「ansible_ssh_pass」指定に
不要な文字列が混入しているため、Ansible-vaultを利用した暗号化処理に問題があると思われる。
パスワードに利用可能な各記号をAnsible-vault暗号化対応できるように対応する必要がある。

●問題のバージョン
ITAv1.4.0～v1.5.0

**Comment by enoman** [comment]
完了
