### ISSUE TITLE
【共通】IDColumnに履歴追跡の処理を入れると履歴検索にアスタリスクのマークがつく

### ISSUE THREAD

**Issue by ta-matsuo** [exastro-suite/it-automation#296]
履歴検索に、文字列、日付、数値など他の必須項目はアスタリスクつかない。
IDComumnかつ必須項目かつ履歴追跡が入ってる場合だけ履歴検索にアスタリスクがつく。

**Comment by a-ikegame** [comment]
**■事象詳細**
①管理コンソールより新規にメニューグループ作成
②メニュー作成より、①のメニューグループに紐づいたメニューを作成する。
　※以下項目を登録する。
　・プルダウン形式かつ、必須項目
③上記の項目の変更履歴を表示する。
⇒変更履歴の項目名に「*」が表示される。

**■修正後の動作**
③の変更履歴にて、項目名に「*」が表示されない。
