### ISSUE TITLE
【Conductor】実行結果の通知機能

### ISSUE THREAD

**Issue by sudodaisuke-jp** [exastro-suite/it-automation#312]
【要望】
ITAの機能として実行結果を通知する機能がないため
Conductorなどでメール通知などの処理を実行しなければならないため
処理が完了しないと通知が飛ばなく通知がされない状況が発生する可能性があるため
ITAの機能として具備していただきたい。

**Comment by kubo-1** [comment]
メールのみではなく、RedmineやSlackといった外部ツールへの連携も希望。
上記以外にも連携先は複数あると思うので、段階的でよいので連携しやすいような機能から徐々に具備されることを希望。

**Comment by ta-matsuo** [comment]
#52 と同件のためクローズ。

**Comment by y-yonekura** [comment]
7/28 打ち合わせ内容
ステータス変更時に通知を行う機能とする
HTTPリクエストでの通知（Webhookを利用）

・通知管理メニューの新規作成
　　※説明に設定例記載
　　入力項目：
　　　　通知名称
　　　　curl オプション
　　　　抑止期間（開始～終了）
　　　　※設定中は、通知実行しない。

・Conductorクラス編集に通知設定欄追加
　　通知の選択（Roleと同様の選択形式、複数選択可）
　　通知対象ステータスの選択（Roleと同様の選択形式、複数選択可）

・通知実行処理（バックヤード）
　　対象ステータス時、通知実行処理
　　
・curl オプション内で使用できる定数
　　対象：
　　　　ConductorインスタンスID
　　　　Conductor名称
　　　　オペレーション名
　　　　ステータス
　　　　実行ユーザ
　　　　予約日時
　　　　開始日時
　　　　終了日時

**Comment by y-yonekura** [comment]
確認事項：
・予約変数の作業確認URLのFQDN（ドメイン、IP）部分について
　（※バックヤードでの実行の為、WEBの接続方法が判別できない）
　　例）
　　-通知一覧にて、入力させ、指定させる。
　　-実行サーバー上の情報取得（構築環境依存になる可能性あり。）
　　-FQDN（ドメイン、IP）部分は出力しない

	1. ip a コマンドから抽出。
	http://XXX.XXX.XXX.XXX/default/menu/01_browse.php?no=2100180005&conductor_instance_id=1
	2. vhosts_exastro-it-automation.confから抽出
	https://exastro-it-automation.local/default/menu/01_browse.php?no=2100180005&conductor_instance_id=1
	3. FQDN（ドメイン、IP）部分無し
	/default/menu/01_browse.php?no=2100180005&conductor_instance_id=1
