### ISSUE TITLE
phpspreadsheet v1.15.0 で出力したExcelに不具合

### ISSUE THREAD

**Issue by sinatommy** [exastro-suite/it-automation#329]
10月9日にリリースされたphpspreadsheetの1.15.0版を使用すると、ITAのメニューから出力したExcelのプルダウン項目がずれてしまう。

今後の対応を検討する。
・1.15.0に追従するよう、アプリで対処するか
・インストール時にバージョンを指定するか
・phpspreadsheet以外で、ITAがインストールしているツールも同様の対応をするか

**Comment by h-matsuhashi** [comment]
v1.6.0時点では、インストール時のバージョンを1.14.1に指定。

**Comment by a-ikegame** [comment]
phpspreadsheetの最新バージョンで正常に動作するよう対応する。

**Comment by a-ikegame** [comment]
マージ済み
