### ISSUE TITLE
性能改善④DBIndex追加

### ISSUE THREAD

**Issue by sinatommy** [exastro-suite/it-automation#33]
DBIndexを貼って、実行処理性能を向上させる。

**Comment by enoman** [comment]
下記indexを追加
CREATE INDEX IND_B_ANSIBLE_LNS_VARS_ASSIGN_03  ON B_ANSIBLE_LNS_VARS_ASSIGN     (OPERATION_NO_UAPK,PATTERN_ID,SYSTEM_ID,VARS_LINK_ID,DISUSE_FLAG);
CREATE INDEX IND_B_ANSIBLE_LNS_VARS_ASSIGN_04  ON B_ANSIBLE_LNS_VARS_ASSIGN     (OPERATION_NO_UAPK,PATTERN_ID,DISUSE_FLAG);
CREATE INDEX IND_B_ANSIBLE_LNS_PHO_LINK_02     ON B_ANSIBLE_LNS_PHO_LINK        (OPERATION_NO_UAPK,PATTERN_ID,SYSTEM_ID,DISUSE_FLAG);
--Legacy-Role
CREATE INDEX IND_B_ANSIBLE_LRL_CHILD_VARS_02   ON B_ANSIBLE_LRL_CHILD_VARS      (ARRAY_MEMBER_ID,DISUSE_FLAG);
CREATE INDEX IND_B_ANSIBLE_LRL_PATTERN_LINK_02 ON B_ANSIBLE_LRL_PATTERN_LINK    (PATTERN_ID,DISUSE_FLAG);
CREATE INDEX IND_B_ANS_TEMPLATE_FILE_02        ON B_ANS_TEMPLATE_FILE           (ANS_TEMPLATE_VARS_NAME,DISUSE_FLAG);
CREATE INDEX IND_B_ANS_CONTENTS_FILE_02        ON B_ANS_CONTENTS_FILE           (CONTENTS_FILE_VARS_NAME,DISUSE_FLAG);
CREATE INDEX IND_B_ANSIBLE_LRL_VARS_ASSIGN_03  ON B_ANSIBLE_LRL_VARS_ASSIGN     (OPERATION_NO_UAPK,PATTERN_ID,SYSTEM_ID,VARS_LINK_ID,DISUSE_FLAG);
CREATE INDEX IND_B_ANSIBLE_LRL_VARS_ASSIGN_04  ON B_ANSIBLE_LRL_VARS_ASSIGN     (OPERATION_NO_UAPK,PATTERN_ID,DISUSE_FLAG);
--Pioneer
CREATE INDEX IND_B_ANSIBLE_PNS_VARS_ASSIGN_03 ON B_ANSIBLE_PNS_VARS_ASSIGN      (OPERATION_NO_UAPK,PATTERN_ID,SYSTEM_ID,VARS_LINK_ID,DISUSE_FLAG);
CREATE INDEX IND_B_ANSIBLE_PNS_VARS_ASSIGN_04 ON B_ANSIBLE_PNS_VARS_ASSIGN      (OPERATION_NO_UAPK,PATTERN_ID,DISUSE_FLAG);
CREATE INDEX IND_B_ANSIBLE_PNS_PHO_LINK_02    ON B_ANSIBLE_PNS_PHO_LINK         (OPERATION_NO_UAPK,PATTERN_ID,SYSTEM_ID,DISUSE_FLAG);
