### ISSUE TITLE
【共通】セッション切れの状態で事前アップロードすると「アップロード処理中」のまま固まる

### ISSUE THREAD

**Issue by kawaro** [exastro-suite/it-automation#331]
ユーザセッションが切れた状態（デフォルトでログイン後3時間経過、または無操作で1時間経過）でファイルを事前アップロードしようとすると、アップロード状況が「アップロード処理中」のままアップロードが完了しない状態になります。
再ログイン後、アップロードを改めて行うと正常にアップロードが完了します。

**Comment by ayaka-shinomiya** [comment]
[仕様]
・ボタン押下時にセッション切れの場合、アラートを表示しログイン画面に遷移させる
