### ISSUE TITLE
【Conductor】movementの処理が実際には終了しているのにConductor作業確認画面で実行中のままとなる

### ISSUE THREAD

**Issue by hseiyo** [exastro-suite/it-automation#332]
Conductor作業確認画面上で、該当のmovementを選択すると右のステータス表示ではEnd timeに時刻が表示されているが、Statusは実行中のままとなり、完了しない。
該当のmovementはAnsible-Legacyであるが、Ansible-Legacyの作業状態確認画面でもステータスは完了となっていて、ログからも処理は完了していることを確認している。
Conductor作業一覧画面でも実行中となっている。

ところで、この状態で23時間程度経っていますが、状態が変わっていません。タイムアウトは無いのでしょうか。

![conductor_not_finished](https://user-images.githubusercontent.com/13925348/96674656-3930dd00-13a4-11eb-9d48-04f649aade5c.png)

**Comment by y-yonekura** [comment]
#199　#28　の修正に含まれておりますので、
バージョン1.6にて、改修済みとなります。
また、タイムアウトの件につきまして、検討させていただきます。

**Comment by sinatommy** [comment]
@hseiyo 
こちらのissueはCLOSEしてよろしいでしょうか？

**Comment by hseiyo** [comment]
原因が特定出来ていて修正完了しているということであればクローズで構いません。
