### ISSUE TITLE
Symphony分岐

### ISSUE THREAD

**Issue by sinatommy** [exastro-suite/it-automation#34]
Symphonyを条件分岐させる機能追加

①条件分岐
②並列実行
③SymphonyがSymphonyを呼び出す。サブジョブネット。
　GUI上で設定できる。

Symphonyの根本設計が変わるので、移行ツールなどがないと、既存ユーザのデータ移行が難しい。

**Comment by sinatommy** [comment]
@ta-matsuo  担当者割り当てお願いします。

**Comment by katokeita** [comment]
フロント部分がある程度出来てきましたので一度確認お願いします。

**Comment by sinatommy** [comment]
右側に各機能のMovementが表示されるが、ソートされていない。
MovemrntID順でソートされるようにしたい。

**Comment by ta-matsuo** [comment]
Symphony系のメニューは新しいメニューグループを作成して「基本コンソール」から移動する。
Symphony1（既存のSymphony）とSymphony2（今回作成するSymphony）は別のメニューグループとする。

「基本コンソール」⇒「機器一覧」「オペレーション一覧」「Movement一覧」
  「Symphony1」⇒「Symphony1インタフェース情報」～「Symphony1定期作業実行」
  「Symphony2」⇒「Symphony2インタフェース情報」～「Symphony2定期作業実行」

**Comment by y-yonekura** [comment]
タスク整理

▼Symphony2.0クラス一覧	：90%
▼Symphony2.0クラス編集	：50%		
- 登録系処理
- 更新系処理
- バリデーション
- デザイン組み込み
- ↑関連処理	
	
▼Symphony2.0作業実行	:40%
- インスタンス登録系処理
- デザイン組み込み
- ↑関連処理

▼backyards	
- 定期監視
- 実行

▼Symphony2.0作業確認	
- 実行系処理(停止解除,強制停止,予約取消)
- デザイン組み込み
- ↑関連処理

▼Symphony2.0作業一覧	
▼Symphony2.0定期実行	

▼Symphony2.0インターフェース情報
▼Symphony2.0-nodeクラス一覧
▼Symphony2.0-terminalクラス一覧
▼Symphony2.0-Nodeインスタンス一覧

**Comment by sinatommy** [comment]
Symphony2の名称を考える

**Comment by ta-matsuo** [comment]
正式名はConductorで決定。

**Comment by y-yonekura** [comment]
残タスク

▼Conductorクラス編集	
- デザイン組み込み関連処理	
	
▼Conductor作業実行
- デザイン組み込み関連処理

▼Conductor作業確認	
- デザイン組み込み関連処理

▼backyards
▼インストーラ対応
backyards起動関連
データリレイストレージパス

**Comment by y-yonekura** [comment]
払戻済
