### ISSUE TITLE
英語版ITAーWebUIの表記修正

### ISSUE THREAD

**Issue by sinatommy** [exastro-suite/it-automation#35]
①カラム名とメニュー名の差異1
メニューグループ：File control management
メニュー：File link list(Ansible)
対象サブメニュー：Display filter　/　Register
★カラム: File list

メニューグループ：Ansible common
★メニュー： Contents list

⇒File listに統一する。

②カラム名とメニュー名の差異2
メニューグループ：File control management
メニュー：File link list(Ansible)
対象サブメニュー：Display filter　/　Register
★カラム:Dialog file materials

メニューグループ：Ansible Pioneer
★メニュー：Dialog files

⇒Dialog filesに統一する。

③カラム名差分
メニューグループ：File control management
メニュー：File link list(OpenStack)
対象サブメニュー：Display filter　/　Register
★カラム : Environment Configuration file

メニューグループ：OpenStack
メニュー：Movement list
対象サブメニュー：Display filter　/　Register
★カラム : Environment setting file

⇒Environment Configuration fileに統一する。

**Comment by t-yaocheng** [comment]
払戻し完了。
