### ISSUE TITLE
【OpenStack】代入値管理ページでレコードを更新する際のオペレーション変更時に実行される関数について

### ISSUE THREAD

**Issue by HibikiNanri** [exastro-suite/it-automation#363]
レコードを「更新」するとき、オペレーションを変更する際に実行される「proxy.Mix1_1_pattern_upd」の処理が存在しないため、コンソールにエラーが表示される。

■その他
・[編集]→具体値入力で、分類を選ぶとコンソールログにエラー出る。（選択自体はできる）
・ITAホストを一度選ぶと、そこからほかの分類にしたときに入力値がITAホスト選択のまま（入力欄に戻らない）

**Comment by sinatommy** [comment]
Openstack-Driverは次バージョンで廃止予定。
対処なし。
