### ISSUE TITLE
【共通】(v1.4.1以下) https通信時の事前アップロード処理でデータサイズが128KBを超えた場合に処理中で固まる。

### ISSUE THREAD

**Issue by kawaro** [exastro-suite/it-automation#368]
【事象】
https(SSL)通信時に、各メニューの事前アップロード処理でデータサイズが128KByteを超えた場合に処理中のまま固まる。

【考えられる原因】
Apacheのvhosts_exastro-it-automation.conf のSSLCipherSuiteを設定かつSSLRenegBufferSizeが未設定の場合に本事象が発生することを確認。
上記設定時は、Apacche mod_sslのデフォルト値(128kByte)が適用されていると思われる。

1.5.0リリース時に vhosts_exastro-it-automation.conf 内の不要な設定は削除しており、
それに合わせて SSLCipherSuite は削除済み(ssl.confのデフォルト値を採用)のため、1.5.0では事象は発生しなく、
それ以降のバージョンも発生しない想定。

【回避策】
vhosts設定ファイルの「<VirtualHost *:443 >」設定において、
下記2点のいづれかの対応によりアップロードサイズを変更できます。

①SSLRenegBufferSize 設定する（例：SSLRenegBufferSize 4000000000）
②SSLCipherSuite を削除する（SSLCipherSuite HIGH:MEDIUM:!aNULL:!MD5:!SEED:!IDEA）

対象ファイル：/etc/httpd/conf.d/vhosts_exastro-it-automation.conf

【関連issue】
https://github.com/exastro-suite/it-automation/issues/331
issue#331でも同様に処理中のまま固まる事象が発生する、
問題があった際にエラーメッセージを表示して欲しい、
本改善はissue#331での対応を希望。

本issueはコミュニティサイトのFAQにも回避方法を記載してクローズ予定。

**Comment by sinatommy** [comment]
FAQに記載する。
