### ISSUE TITLE
閲覧権限のないメニューグループにログイン後遷移すると、問い合わせメッセージのみが表示されてログアウトもできない

### ISSUE THREAD

**Issue by hseiyo** [exastro-suite/it-automation#370]
ユーザAとユーザBがあり、それぞれロールAとロールBに割り当てられている場合に、
ロールBに閲覧権限がないメニューグループAをユーザAで表示した状態からログアウトした後で、
ユーザBでログインすると認証成功後にメニューグループAを表示しようとするが、権限がない。
この画面にはログアウトメニューもなく、別のメニューグループへの遷移ボタンもないため、何もできなくなる。

該当の画面では以下のメッセージが表示される。

許可されていない操作です。アクセス権限の確認をしてください。
管理者に問い合わせてください。

**Comment by sinatommy** [comment]
こちらのissueにて対応中です。
[【全般】ログイン後画面の制御](https://github.com/exastro-suite/it-automation/issues/146)

v1.6.0にてリリースされます。
