### ISSUE TITLE
【Ansible-Driver,Terraform-Driver】「登録」と「更新」両方で編集を行うとプルダウンがおかしくなる。

### ISSUE THREAD

**Issue by a-koizumi** [exastro-suite/it-automation#383]
【手順】
①「登録」ボタン押下でオペレションを選択する。
②「一覧/更新」から「更新」ボタン押下しオペレーションを選択する。
　⇒Movement、ホスト、変数名のプルダウンが変な感じになる。

**Comment by HibikiNanri** [comment]
プルダウン生成系箇所全般の事象
2100020109(Ansible-Legacy 代入値管理)
2100020115(Ansible-Legacy 代入値自動登録)
2100020210(Ansible-Pioneer 代入値管理)
2100020214(Ansible-Pioneer 代入値自動登録)
2100020307(Ansible-LegacyRole Movement詳細)
2100020311(Ansible-LegacyRole 代入値管理)
2100020316(Ansible-LegacyRole 代入値自動登録)
2100040710(Ansible共通 収集項目管理)
2100070003(Openstack 代入値管理)
2100080008(Terraform 代入値管理)
2100080015(Terraform 代入値自動登録)
2100150006(資材管理 資材紐付け管理Ansible)
2100150007(資材管理 資材紐付け管理Openstack)
2100150008(資材管理 資材紐付け管理Terraform)

**Comment by HibikiNanri** [comment]
マージ済み
