### ISSUE TITLE
【Ansible-Driver】ロールパッケージ内のロールを削除しても「Movement詳細」にロール名が表示されてしまう

### ISSUE THREAD

**Issue by ta-matsuo** [exastro-suite/it-automation#384]
1. ロールパッケージにパッケージ「X」を登録する、中身のロールを「AAA」とする
2. あるMovementのMovement詳細で、このパッケージのロール「AAA」を指定する
3. ロール「AAA」が解析され、変数などが使えるようになる
4. ここでロールパッケージ管理でパッケージ「X」を更新する、その際に中身にロール「AAA」がない状態とする

この結果、ロール「AAA」は使えなくなっているのですが、Movement詳細の表示としては普通に表示されています。
更新しようとするとロールの選択肢が無いため使えないということはわかるのですが、表示のみでは気づけません。
また内部的にはロールが存在しないため、変数は使えなくなっておりID変換エラーがでています。
これらはすべて正常な挙動のためログに出力は何もありません。

**Comment by enoman** [comment]
RBACの対応で、Movement詳細のロールに紐づけているVIEWの不備を修正しています。
1.6.1で対応済みです。
