### ISSUE TITLE
比較機能の強化

### ISSUE THREAD

**Issue by mtakahashiif** [exastro-suite/it-automation#4]
収集＋比較

**Comment by sinatommy** [comment]
PlaybookCollection　収集ロール＋パラメータ生成ロール実施（Linux）
パラメータ生成ロールpython2系ansibleにて動作確認
※python3系ではエラーで動作せず

**Comment by y-yonekura** [comment]
収集機能部分の簡易なデモ作成中（例：sshd）
- OS設定変更
- OS設収集
- パラメータ生成
- 実機情報の登録

**Comment by y-yonekura** [comment]
仕様検討中案
	・比較機能
		データソースはyaml形式のファイル（playbookCollection以外も許容する)
		→汎用性確保の為、対応するyamlファイルの内容の構造の検討＋PlabookCollectionとの連携（依頼）検討
		オペレーション-ホストの単位での比較、表示、項目等の絞り込み等

	・実機情報収集＋パラメータ生成機能
		実行の為のドキュメント整備
		前提条件はyaml形式出力（yaml形式のみ登録機能の対象とする)
		参考例：）OS収集ロール＋パラメータ生成ロール（playbbokCollection）

	・実機情報登録機能
	 	起動タイミング検討（Symphony,cron,backyards)
		指定フォルダ（~/data_relay_storage/）配下のyamlファイル有で処理
		一意判別の手段（OP-ホストの組み合わせ？個別で通番採用？ファイル名で）
　　　　
	・紐づけ管理機能
		対象のデータシートとソースとなるyamlファイルのファイル名で紐づけ（代入値管理の逆のイメージ）

	・他
		パラメータシート、メニュー定義、メニュー登録手順（Learn）作成
			-将来的にPlaybookに含める等で自動化を目標

**Comment by y-yonekura** [comment]
・比較機能の仕様打ち合わせ（4/7）

・比較機能前提条件
　-比較機能対象：メニュー作成機能で作成した、パラメータシート
　-比較定義の設定：対象のメニュー、項目の、の紐づけ設定
　-比較実行時のパラメータ：比較定義＋日時（オペレーション）＋ホスト名

・作成画面
　-比較定義　　　：比較対象メニューの紐づけ
　-比較定義詳細　：比較定義で定義したメニューの項目の紐づけ
　-比較　　　　　：比較定義で設定した、情報と、オペレーションの日時を条件として、比較実施
　-参照用メニュー管理　：参照用メニューIDの管理（※隠しメニュー予定）

**Comment by y-yonekura** [comment]
収集機能は　#207

**Comment by sinatommy** [comment]
比較して差分があった場合、ログに出力して欲しい。
（ログ監視で差分発生を検知するため）

**Comment by y-yonekura** [comment]
・比較機能の仕様打ち合わせ（1/20）

・機能要件
　-比較機能対象：メニュー作成機能で作成した、パラメータシート（ホスト/オペレーションあり）
　-比較対象項目：文字列(単一行)、文字列(複数行)、整数、小数、日時、日付、プルダウン選択、リンク、ファイルアップロード
　　　　　　　　　※ファイルアップロード：ファイルの内容で比較
　-比較定義の設定：対象のメニュー、項目の紐づけ設定
　-比較実行時のパラメータ：比較定義＋基準日＋ホスト名

・作成画面
　-比較定義　　　：比較対象メニューの紐づけ
　-比較定義詳細　：比較定義で定義したメニューの項目の紐づけ
　-比較　　　　　：比較定義で設定した情報と、基準日、ホスト名を条件として、比較実施
　　　　　　　　 ：出力内容（ホスト単位で出力）
　　　　　　　　 　　ホスト名、メニュー1、No（メニューの主キー）、オペレーション、比較項目
　　　　　　　　 　　ホスト名、メニュー2、No（メニューの主キー）、オペレーション、比較項目
　　　　　　　　 　　※対象ホスト分出力
　　　　　　　　 ：比較結果のExcel出力

**Comment by y-yonekura** [comment]
備忘：プルダウンを使用した際の出力結果について、注意事項、例をマニュアルへ記載
