### ISSUE TITLE
【インストーラ】MariaDB 10.4以上のインストールの対応（インストールが止まる）

### ISSUE THREAD

**Issue by j-kumamoto** [exastro-suite/it-automation#428]
ITA1.5.0インストーラーにて、MariaDBのバージョン10.4以上のインストール時に、
以下の事象が発生する。
（rhel8 ubiで発生、その他のサーバOSの発生状況は調査中）

①MariaDBパッケージ名の変更(一部の大文字化)によりita_builder_core.shの
　パッケージチェック処理（yum listのチェック）でエラーとなる。

【エラーメッセージ】
"ERROR:Package not installed mariadb-server"

【問題の処理】
yum_package_check mariadb mariadb-server expect

※問題の関数
yum_package_check() {
    if [ $# -gt 0 ];then
        for key in $@; do
            echo "----------Check Installed packages[$key]----------" >> "$ITA_BUILDER_LOG_FILE" 2>&1
            **yum list installed | grep "$key" >> "$ITA_BUILDER_LOG_FILE" 2>&1**
            if [ $? -ne 0 ]; then
                log "ERROR:Package not installed [$key]"
                func_exit
～

【パッケージ名の例】
10.3以下：mariadb-server.x86_64  
10.4以上：MariaDB-server.x86_64  

② mariadbセッティングの対話処理において
「Switch to unix_socket authentication」のメッセージでインストーラーが止まる。

※以下は確認中
10.4.1以降でユーザ認証についての仕様が変更されている。
OS側のユーザー名とDB側のユーザー名が同じであれば、
UnixSocketを使って認証することで、パスワードなしで通す方式（unix_socket authentication）に
変更するかどうかの問い合わせが発生するが、インストーラーが対応できていない可能性がある。

参考URL）https://hp.ofuton.org/61/

③「②」の状態になり、一度インストーラが止まり、
　再度インストーラを実行した場合、以降のセッティング処理（ copy_and_backup() 等）が省略され、
　「server.cnf」の日本語設定(utf-8)が反映されないが、ITAのインストール処理は完了するため、
　ITAの画面においてDBレコードの日本語文字列が文字化けする。

**Comment by h-matsuhashi** [comment]
修正ファイル
・ita_builder_core.sh

仕様
・RHEL8系でITAインストール時に行うmysql_secure_installationで使用するexpectのコードの一部を以下の様に修正。
旧
  expect \"Enter current password for root \\(enter for none\\):\"
  send \"\\r\"
  expect -re \"Set root password\\?.* $\"
  send \"Y\\r\"
  expect \"New password:\"

新
　expect \"Enter current password for root \\(enter for none\\):\"
　send \"\\r\"
　expect { 
      -re \"Switch to unix_socket authentication.* $\" {
          send \"n\\r\"
          expect -re \"Change the root password\\?.* $\"
          send \"Y\\r\"
      }
      -re \"Set root password\\?.* $\" {
          send \"Y\\r\"
      }
  }
  expect \"New password:\"

※"Enter current password for root (enter for none)"のメッセージの次に、"Switch to unix_socket authentication."が来た場合は、すぐ後ろの{}内の処理（send \"n\\r\"～send \"Y\\r\"）を行い、"Set root password?"が来た場合は、send \"Y\\r\" の処理を行う。

mariadb 10.3、10.4、10.5で動作確認済。
