### ISSUE TITLE
メニュー作成後の設定カラムの最大値/最小値の設定(テキスト・数値・日付)

### ISSUE THREAD

**Issue by sinatommy** [exastro-suite/it-automation#43]

**Comment by naoki-kondo** [comment]
### 改修箇所
- 4000byte以上
- マルチカラムにも対応
- 現行のバリデーションを修正

**Comment by ta-matsuo** [comment]
①デフォルト値を4000から8192バイトに修正
②代入値自動登録機能の上限を1024から8192バイトに修正
③代入値管理メニューの具体値の上限を1024から8192バイトに修正
④メニュー作成機能の上限を1024から8192バイトに修正

**Comment by naoki-kondo** [comment]
### 分担
①デフォルト値を4000から8192バイトに修正
⇒松尾
②代入値自動登録機能の上限を1024から8192バイトに修正
⇒榎本
③代入値管理メニューの具体値の上限を1024から8192バイトに修正
⇒榎本
④メニュー作成機能の上限を1024から8192バイトに修正
⇒今藤

**Comment by naoki-kondo** [comment]
追加
テキストのバリデーションを外す。
マニュアルの修正

**Comment by ta-matsuo** [comment]
＞①デフォルト値を4000から8192バイトに修正
⇒払戻完了。

**Comment by naoki-kondo** [comment]
>マルチテキストにも対応
>現行のバリデーションを修正
>④メニュー作成機能の上限を1024から8192バイトに修正
⇒払い戻し完了
