### ISSUE TITLE
メニュー作成後の設定カラムに小数の桁数を設定

### ISSUE THREAD

**Issue by sinatommy** [exastro-suite/it-automation#44]

**Comment by naoki-kondo** [comment]
int上限値
PHP 9223372036854775807
js 9007199254740991
MariaDB 2147483647

float 上限値
PHP 1.8e308(14桁) 
js 16桁
MariaDB 3.402823466E+38

仕様
整数はMariaDBの最大値より低い値
小数は14桁以下を最大値として設定

**Comment by t-yaocheng** [comment]
払戻し完了。
メニュー項目作成情報に整数の最大値、最小値と小数の最大値、最小値、桁数カラムを追加しました。
## 仕様
### 小数カラム：
 - -99999999999999~99999999999999 (14桁)
 - 整数部分＋小数部分最大14桁
 - DBにはDOUBLE(MySQL側)とNUMBER(ORACLE DB側)で記録します。 
### 最大値、最小値、桁数カラム
必須ではありません。
未入力の場合:
 - 整数最大値: 2147483647
 - 整数最小値: -2147483648
 - 小数最大値: -99999999999999 (14桁)
 - 小数最小値: 99999999999999 (14桁)
 - 小数桁数: 14

小数桁数は1~14の半角数字
整数、小数の最大値と最小値は整数、小数の仕様と一緒。
