### ISSUE TITLE
【インストーラ】アンインストール時にMariaDBのキャッシュが残る

### ISSUE THREAD

**Issue by ta-matsuo** [exastro-suite/it-automation#447]
ITAのアンインストール⇒インストールを行うと、アンインストール前のデータが取得される場合がある。
キャッシュにデータが残っているのが原因のため、アンインストール時に以下のコマンドを追加する。
RESET QUERY CACHE;

**Comment by h-matsuhashi** [comment]
修正ファイル
・drop_db_and_user_for_MySQL.sql

仕様
・drop_db_and_user_for_MySQL.sqlにRESET QUERY CACHE;のコマンドを追加。

確認方法
・ITAインストール後にmysqlにログインし、Qcache_queries_in_cache の値が0になっていることを確認。
