### ISSUE TITLE
【Ansible-driver】収集機能で収集したファイルをファイルアップロードカラムに登録する

### ISSUE THREAD

**Issue by wakkysan** [exastro-suite/it-automation#449]

**Comment by y-yonekura** [comment]
■要件
	収集機能の対象へファイルアップロードカラムを追加する

■処理概要
	登録/更新は、RESTAPIで実施。（base64変換したものをRESTAPIのパラメータとして送信）

■対象ディレクトリ
	_parameters　　　※パラメータファイル格納先
	_parameters_file　 ※収集したファイル格納先

■階層構造例
in/out
　 |-  _parameters 
　 |　|-  localhost
　 |　　  |-  Apache_setup.yml 　※ファイルを変数の値として記載（ VAR_XXXX : sample.txt　　）
　 |-  _parameters_file
　　 |-  localhost
　　　  |-sample.txt

**Comment by y-yonekura** [comment]
■タスク

- バックヤード
- メニュー作成
 	ファイルアップロードカラムの対応追加（紐付対象メニューカラム管理の登録）
- VIEWの修正

**Comment by ta-matsuo** [comment]
メニュー作成機能部分の修正完了。

**Comment by y-yonekura** [comment]
■マニュアル、FAQで対応事項
・RESTAPIでのファイルアップロードの上限値の設定変更
	　-php.iniで設定について
