### ISSUE TITLE
【Openstack-Driver】Openstack-Driverの削除

### ISSUE THREAD

**Issue by wakkysan** [exastro-suite/it-automation#450]

**Comment by h-matsuhashi** [comment]
DSC-driver削除の時と同じ方針で対応。
・Openstack-driverでのみ必要なファイルの削除
（backyardのサービスファイル、WebUIのOpenstackメニューグループ関係のファイル、Openstack関係のsql等）
・Openstack-driver以外でも必要になるファイルは、Openstack-driverに関わる処理の部分を修正
（インストーラー関係、一部WebUIのページファイル、一部sqlファイル等）
・過去に連携したドライバ(Openshift、SCRAB等)に関するものがそのまま残っているものは触らない。
（メッセージ関係のファイル等）

**Comment by h-matsuhashi** [comment]
確認点
・バージョンアップ時のOpenstack-driverに関する挙動について（例:Openstack-driver入りv1.5.0→v1.6.1）
　①特に何もしない（Openstack-driverはv1.5.0のまま）
　②連携をしていた最新のバージョン（v1.6.0）までバージョンアップする
　③Openstack-driver関連のファイルを削除する

**Comment by h-matsuhashi** [comment]
仕様
・ITAインストール時にインストールされるドライバの中からOpenstack-driver、material3を削除。
・バージョンアップ時に、Openstack-driver、material3がインストールされている場合、それらをサポートしていた最後のバージョン（1.6.0）までバージョンアップする。
※その他のドライバは1.6.1にバージョンアップされる
・Openstack-driver、material3でのみ必要になるファイルをインストール資材から削除。

修正点
・it-automation/ita_install_package/install_scripts/ita_answers.txt
　Openstackのインストール選択の項目を削除
・it-automation/ita_install_package/install_scripts/bin/install.sh
　Openstackとmaterial3に関する処理を行う部分を削除
・it-automation/ita_install_package/ITA/ita-releasefiles/ita_material3
・it-automation/ita_install_package/ITA/ita-releasefiles/ita_openstack-driver
　リリースファイルのバージョン表記を1.6.0に修正
・it-automation/ky_sql_seeds/en_US_SQL_DATA.xlsm
・it-automation/ky_sql_seeds/ja_JP_SQL_DATA.xlsm
　ソースがita_model-h.sql、ita_model-l3.sqlになっているデータを削除
・以下のファイル・ディレクトリをインストーラー資材より削除
it-automation/ita_install_package/install_scripts/list/material3_service_list.txt
it-automation/ita_install_package/install_scripts/list/material3_table_list.txt
it-automation/ita_install_package/install_scripts/list/openstack_service_list.txt
it-automation/ita_install_package/install_scripts/list/openstack_table_list.txt
it-automation/ita_install_package/ITA/ita-contents/ita-root/backyards/material/ky_material_linkage_openstack.php
it-automation/ita_install_package/ITA/ita-contents/ita-root/backyards/material/ky_material_linkage_openstack.service
it-automation/ita_install_package/ITA/ita-contents/ita-root/backyards/openstack_driver/
it-automation/ita_install_package/ITA/ita-contents/ita-root/libs/backyardlibs/openstack_driver/
it-automation/ita_install_package/ITA/ita-contents/ita-root/libs/messages/en_US_UTF-8_ITAOPENST_ERR.php
it-automation/ita_install_package/ITA/ita-contents/ita-root/libs/messages/en_US_UTF-8_ITAOPENST_MNU.php
it-automation/ita_install_package/ITA/ita-contents/ita-root/libs/messages/en_US_UTF-8_ITAOPENST_STD.php
it-automation/ita_install_package/ITA/ita-contents/ita-root/libs/messages/en_US_UTF-8_ITAOPENSTC_STD_js.php
it-automation/ita_install_package/ITA/ita-contents/ita-root/libs/messages/ja_JP_UTF-8_ITAOPENST_ERR.php
it-automation/ita_install_package/ITA/ita-contents/ita-root/libs/messages/ja_JP_UTF-8_ITAOPENST_MNU.php
it-automation/ita_install_package/ITA/ita-contents/ita-root/libs/messages/ja_JP_UTF-8_ITAOPENST_STD.php
it-automation/ita_install_package/ITA/ita-contents/ita-root/libs/messages/ja_JP_UTF-8_ITAOPENSTC_STD_js.php
it-automation/ita_install_package/ITA/ita-contents/ita-root/libs/orchestrators/openstack_driver/00_shymphonyLinker.php
it-automation/ita_install_package/ITA/ita-contents/ita-root/libs/webindividuallibs/systems/2100070004/
it-automation/ita_install_package/ITA/ita-contents/ita-root/libs/webindividuallibs/systems/2100070005/
it-automation/ita_install_package/ITA/ita-contents/ita-root/webconfs/systems/2100070001_loadTable.php
it-automation/ita_install_package/ITA/ita-contents/ita-root/webconfs/systems/2100070002_loadTable.php
it-automation/ita_install_package/ITA/ita-contents/ita-root/webconfs/systems/2100070003_loadTable.php
it-automation/ita_install_package/ITA/ita-contents/ita-root/webconfs/systems/2100070006_loadTable.php
it-automation/ita_install_package/ITA/ita-contents/ita-root/webconfs/systems/2100070007_loadTable.php
it-automation/ita_install_package/ITA/ita-contents/ita-root/webconfs/systems/2100150007_loadTable.php
it-automation/ita_install_package/ITA/ita-contents/ita-root/webroot/menus/systems/2100000204/symbol/symbol_000111_openstack.svg
it-automation/ita_install_package/ITA/ita-contents/ita-root/webroot/menus/systems/2100070001/
it-automation/ita_install_package/ITA/ita-contents/ita-root/webroot/menus/systems/2100070002/
it-automation/ita_install_package/ITA/ita-contents/ita-root/webroot/menus/systems/2100070003/
it-automation/ita_install_package/ITA/ita-contents/ita-root/webroot/menus/systems/2100070004/
it-automation/ita_install_package/ITA/ita-contents/ita-root/webroot/menus/systems/2100070005/
it-automation/ita_install_package/ITA/ita-contents/ita-root/webroot/menus/systems/2100070006/
it-automation/ita_install_package/ITA/ita-contents/ita-root/webroot/menus/systems/2100070007/
it-automation/ita_install_package/ITA/ita-contents/ita-root/webroot/uploadfiles/2100000204/MENU_GROUP_ICON/2100070001/
it-automation/ita_install_package/ITA/ita-sqlscripts/en_US_mysql_ita_model-h.sql
it-automation/ita_install_package/ITA/ita-sqlscripts/en_US_mysql_ita_model-l3.sql
it-automation/ita_install_package/ITA/ita-sqlscripts/ja_JP_mysql_ita_model-h.sql
it-automation/ita_install_package/ITA/ita-sqlscripts/ja_JP_mysql_ita_model-l3.sql
it-automation/ky_message_seeds/openstack_driver/
it-automation/ky_sql_seeds/TABLE_CONFIG/ita_model-h.sql
it-automation/ky_sql_seeds/TABLE_CONFIG/ita_model-l3.sql
