### ISSUE TITLE
【Ansible-Driver】必須項目なのに必須マーク(*)がついていない項目がある

### ISSUE THREAD

**Issue by ta-matsuo** [exastro-suite/it-automation#459]
AnsibleLgacyの「代入値管理」メニューの「Movement」、「ホスト」、「変数」は必須項目なのに登録・更新時に項目名の右側に必須マーク(*)がついていない。
他のメニューも要確認。

**Comment by HibikiNanri** [comment]
プルダウン生成系箇所全般の事象
2100020109(Ansible-Legacy 代入値管理)
2100020115(Ansible-Legacy 代入値自動登録)
2100020210(Ansible-Pioneer 代入値管理)
2100020214(Ansible-Pioneer 代入値自動登録)
2100020307(Ansible-LegacyRole Movement詳細)
2100020311(Ansible-LegacyRole 代入値管理)
2100020316(Ansible-LegacyRole 代入値自動登録)
2100040710(Ansible共通 収集項目管理)
2100080008(Terraform 代入値管理)
2100080015(Terraform 代入値自動登録)
2100150006(資材管理 資材紐付け管理Ansible)
2100150008(資材管理 資材紐付け管理Terraform)

**Comment by Satoshi-asano** [comment]
$c->setRequired(true);

をそのまま対象につけると、2重にバリデーションチェックをしてしまう（バリデーションチェックはloadTableの別処理で行っているため）

→*を（ダミーとして）つけるだけのクラスを新規作成する。

**Comment by Satoshi-asano** [comment]
追記
・二者択一または選択項目には必須マークをつけない
以下は対象から除外
2100150006(資材管理 資材紐付け管理Ansible)
2100150008(資材管理 資材紐付け管理Terraform)
