### ISSUE TITLE
【Conductor】Movement分岐時の警告／異常終了の実装

### ISSUE THREAD

**Issue by j-kumamoto** [exastro-suite/it-automation#467]
分岐機能「Conditional branch」利用において、異常判断時のMovement実行が正常終了となってしまう。
ひとつの案として機能「Conductor end」に、警告／異常終了コード（フラグ）をセットできる仕様が望ましい。

利用シーン①：
　Movement-Aが異常終了した場合は、通知Movementを実行し異常終了で完了したい。

利用シーン②：
　インストールMovementが正常終了したが、その後の確認Movementが異常になった場合は、
　警告終了で完了したい。

**Comment by y-yonekura** [comment]
7/28 打ち合わせ内容

・Conductorクラス編集、ENDノードにオプション追加（ラジオボタン）
　　正常　　（デフォルト値）
　　警告
　　異常
　　※Conductor作業実行で終了ステータスへの変更時のENDノードが複数ある場合のオプションの優先度（正常＜警告＜異常）

・Conductorのステータスに追加
　　正常終了（警告）
