### ISSUE TITLE
【メニュー作成】プルダウン選択したら、マスタに付随した情報も引っ張れるようにする

### ISSUE THREAD

**Issue by sinatommy** [exastro-suite/it-automation#47]

**Comment by HibikiNanri** [comment]
マスター（データシートやパラメータシートから「必須」「一意制約」のカラム）のデータを元にしたプルダウンを選択したとき、対象のレコードを一覧で表示されるようにする。

[メニュー定義/作成]ページで上記が実現できるカラムを追加する。
→マスターデータのどのレコードを表示するかなど選択できるようにする。

**Comment by HibikiNanri** [comment]
■ページ構成
・「参照項目情報」ページ（隠しメニュー）を用意し、選択できる参照項目を管理する。
→既存メニューの参照項目は、対象のレコードがインストール時に追加される（#782課題）
・「メニュー定義/作成」ページにて、項目を「プルダウン選択」にすると「参照項目を選択」ボタンが表示され、クリックすると対象の参照項目を選択できるモーダルが表示される。
→参照項目はカンマ区切りのIDで管理する。IDは「参照項目情報」の主キー。
・「メニュー項目作成情報」ページでは「参照項目」の欄を追加。このページから参照項目を登録/更新する場合は、カンマ区切りのIDで値を入力する。

■参照項目機能
・メニュー作成で「プルダウン選択」に参照項目を設定すると、入力用ページから「プルダウン選択」で値を登録した際に、その値と同じ行にあるレコードを参照して表示させる。
→この値は代入値自動登録管理ページにも同様に反映される。
・メニュー作成で項目「プルダウン選択」のものは参照項目として指定できない。
・メニュー作成で項目「ファイルアップロード」のものを参照項目とした場合、ファイル名が文字列として表示されるがそこからファイルのダウンロードなどはできない。
・メニュー作成で項目「パスワード」のものを参照項目とした場合、表示上は「******」となる。（代入値自動登録への利用は可能。）
・「プルダウン選択」に参照項目を設定したものをリピート内に入れると、参照項目も同様にリピートされる。
・「プルダウン選択」に参照項目を設定したものをカラムグループ内に入れると、参照項目も同様のグループにはいる。

**Comment by HibikiNanri** [comment]
マージ済み
要ドキュメント修正
