### ISSUE TITLE
機器一覧__Chromeでパスワードマスク解除ボタンが表示されない

### ISSUE THREAD

**Issue by sinatommy** [exastro-suite/it-automation#48]
Chromeで機器一覧のパスワードを入力すると、値はマスクされるが、
マスクを外すボタン（目のマーク）が表示されない。

**Comment by ta-matsuo** [comment]
機器一覧のパスワードだけではなく、パスワード項目すべてに対応する。
ログイン画面、パスワード変更画面も対象。

**Comment by ta-matsuo** [comment]
払戻完了。
