### ISSUE TITLE
【メニュー作成】縦型メニューのカラム数上限を上げたい

### ISSUE THREAD

**Issue by sinatommy** [exastro-suite/it-automation#483]
縦型メニューを作成する場合、カラム数が343を超えるとMariaDBの仕様でエラーになる。
縦型は同時に横型も持つ必要がある仕様を、横型なしにするなどして、カラム数上限を上げて欲しい。

**Comment by ta-matsuo** [comment]
MariaDBの制限値のため対処不可能。
クローズ。
