### ISSUE TITLE
【全般】メインメニューで未実行(予約)のSymphony/Conductorを確認できるようにしたい

### ISSUE THREAD

**Issue by ayaka-shinomiya** [exastro-suite/it-automation#488]
Widgetの種類に次回実行予定のSymphony/Conductorリストを追加したい。

**Comment by a-ikegame** [comment]
・Widgetを1つ新規追加する。
・初期表示時はステータスが未実行(予約)のSymphony/Conductorを全件表示
・編集機能にて日数指定を可能にする。

**Comment by a-koizumi** [comment]
以下、仕様となる。
予約作業確認
期間（日）:1

「日」単位で対応(xx日23時59分まで)

現在日時：6/11 15:00
6/12 23:59 ・・表示される（実行まで残り：1日8時間59分から進んでいく）
6/13 00:00 ・・表示されない
