### ISSUE TITLE
アップロードファイルがあるメニューに対してRestAPIの登録が失敗するとゴミが残る

### ISSUE THREAD

**Issue by ta-matsuo** [exastro-suite/it-automation#49]

**Comment by y-yonekura** [comment]
コミット直前にファイル配置をする処理へ変更。
（1行コミットのオプション残したまま改修。）

動作確認済み。
残りタスク：
・エラー時のtempは配下のゴミ処理機能の追加。

**Comment by y-yonekura** [comment]
エラー時のtemp配下のゴミ処理機能の追加
loadTableへRESTAPIからのアップロード許可設定の追加

**Comment by y-yonekura** [comment]
払戻完了
