### ISSUE TITLE
【全般】アクセス許可ロールを表示フィルタでテキスト検索した際の挙動の改善

### ISSUE THREAD

**Issue by a-koizumi** [exastro-suite/it-automation#494]
1.6.1より以下のように修正します。

ロール管理の登録データ
ID 名前
1　admin_user1
2    admin_user2
3　hoge_user1
4　hoge_user2

とあるデータ
項番・・略・・アクセス許可ロール
1                admin_user1
2                admin_user1,admin_user2
3                hoge_user2,
4                hoge_user1,hoge_user2
5               admin_user1,hoge_user1

表示フィルタ
検索文字列 表示対象(項番)
user 1/2/3/4/5
user1 　 1/2/4/5
user2 2/3/4
admin 1/2/5
hoge 3/4/5
admin_user1 1/2/5
admin_user2 2

検索文字列に入力する文字列はロール管理で廃止(ID変換失敗)されていないロール名（完全一致）または
ロール名に部分一致する文字列を指定する。
↓は完全一致するロール名はあるが、前方一致するロール名があるので、完全一致のロール名として扱わない
admin
user
user1　
user2

↓下記のようにカンマ区切りで部分一致するロール名を並べても表示レコードは0件となる。
admin_user1,hoge
user1,user2
user
　　
また、カンマはロール名を区切る為の文字として扱う。なので
カンマだけの検索はロール名を特定できないので、表示レコードは0件とする。

**Comment by enoman** [comment]
完了
