### ISSUE TITLE
サイジングシートの作成

### ISSUE THREAD

**Issue by m-takahashi-if** [exastro-suite/it-automation#5]
サイジングシートを作成する。

**Comment by sinatommy** [comment]
【完了】
KVMサーバの構築×4、VM作成(OSインストール、初期設定)×4、Jmeterインストール、Ansibleインストール

【予定】
ITAインストール（ver1.3）←1/30実施中
負荷DBデータ投入
試験シナリオ、データ投入←1/31からデータ作成・投入予定
負荷試験実施
試験データ解析

**Comment by sinatommy** [comment]
サイジングの結果はコミュニティサイトに載せる。

**Comment by sinatommy** [comment]
負荷試験実施中。
画面表示がタイムアウトするので、DBサイジングを調整。
負荷サーバのOutofMemoryが発生したので、CPUとメモリを増設する。
作業実行1000多重はほぼクリア。負荷を上げて再試験予定。

**Comment by sinatommy** [comment]
・2CPU 4Gメモリ
　作業実行50多重

・4CPU 8Gメモリ
　作業実行100多重

**Comment by sinatommy** [comment]
サイジングするにあたり、考慮するべきは以下の3点

①1メニューあたりのレコード数
　～10,000		2CPU/4Gmem
　10,000～20,000	4CPU/8Gmem
　20,000～		問い合わせ

②作業同時実行数
　～50		2CPU/4Gmem
　50～100	4CPU/8Gmem
　100～		問い合わせ

③同時ログイン数
　～200		2CPU/4Gmem
　200～300	4CPU/8Gmem
　300～		問い合わせ

**Comment by sinatommy** [comment]
マニュアルに記載する。
FAQに載せる。
