### ISSUE TITLE
【Ansible-Driver】収集機能用のディレクトリ作成と予約変数追加

### ISSUE THREAD

**Issue by ta-matsuo** [exastro-suite/it-automation#512]
XX/YY：Legacyの場合：legacy/ns
       LegacyRoleの場合：legacy/rl
       Pioneerの場合：pioneer/ns
9999999999：作業No.

①以下のITA予約変数を追加する。
・__parameters_dir_for_epc__: /（ITA インストールディレクトリ）/data_relay_storage/ansible_driver/XX/YY/9999999999/in/_parameters
・__parameter_dir__: /（ITA インストールディレクトリ）/data_relay_storage/ansible_driver/XX/YY/9999999999/out/_parameters
・__parameters_file_dir_for_epc__: /（ITA インストールディレクトリ）/data_relay_storage/ansible_driver/XX/YY/9999999999/in/_parameters_file
・__parameters_file_dir__: /（ITA インストールディレクトリ）/data_relay_storage/ansible_driver/XX/YY/9999999999/out/_parameters_file

②以下のディレクトリを作業実行時に作成する
・/（ITA インストールディレクトリ）/data_relay_storage/ansible_driver/XX/YY/9999999999/in/_parameters
・/（ITA インストールディレクトリ）/data_relay_storage/ansible_driver/XX/YY/9999999999/in/_parameters/（作業対象ホストすべて）
・/（ITA インストールディレクトリ）/data_relay_storage/ansible_driver/XX/YY/9999999999/in/_parameters_file
・/（ITA インストールディレクトリ）/data_relay_storage/ansible_driver/XX/YY/9999999999/in/_parameters_file/（作業対象ホストすべて）
・/（ITA インストールディレクトリ）/data_relay_storage/ansible_driver/XX/YY/9999999999/out/_parameters
・/（ITA インストールディレクトリ）/data_relay_storage/ansible_driver/XX/YY/9999999999/out/_parameters/（作業対象ホストすべて）
・/（ITA インストールディレクトリ）/data_relay_storage/ansible_driver/XX/YY/9999999999/out/_parameters_file
・/（ITA インストールディレクトリ）/data_relay_storage/ansible_driver/XX/YY/9999999999/out/_parameters_file/（作業対象ホストすべて）

**Comment by enoman** [comment]
完了
