### ISSUE TITLE
【ホストグループ管理】ホスト紐づけ管理で正規表現など用いて複数ホストを登録できるようしてほしい

### ISSUE THREAD

**Issue by sudodaisuke-jp** [exastro-suite/it-automation#513]
現在、ホスト紐づけ管理でホストグループ名とホスト名を1行1行登録しないといけないが
ホストグループは複数ホストを登録することが多いため
正規表現などを用いて複数ホストを一括で登録できるようなると
メンテナンス性が向上すると思われます。
例えば「AAA＊」と入力して登録すると解析して下記3レコードが登録される
ような機能を実装して頂きたいです。
【例】
ホストグループA　AAAAホスト
ホストグループA　AAABホスト
ホストグループA　AAACホスト

**Comment by ta-matsuo** [comment]
複数ホストの登録はExcelやRestAPIで実施可能であり、本issueは対応しない。
