### ISSUE TITLE
【全般】各メニューのアクセス許可ロール表示において権限がないロールがID変換失敗と表示される。

### ISSUE THREAD

**Issue by j-kumamoto** [exastro-suite/it-automation#514]
各メニューのアクセス許可ロールの表示において、
ログインユーザに権限が付与されてないロールが「ID変換失敗(xx) ※1」と表示されるが、
実際のID変換失敗とエラーの区別がつかないため、
権限がない場合はパスワードカラム同様にマスク表示「********(xx)」が望ましい。
※1　xxは対象IDの整数が表示

●修正前の表示
Aロール、ID変換失敗(2)、Cロール

●修正案の表示
Aロール、********(2)、Cロール

**Comment by ta-matsuo** [comment]
更新時はID変換失敗は削除して********は残すようにする。

【更新前】
ロールA、ID変換失敗、********
【更新後】
ロールA、********

**Comment by enoman** [comment]
ExcelやRestからの登録・更新では、ロール名が********(4)ゃID変換失敗(5)はエラーとする
RestAPIのFilter機能でアクセス許可ロールのロール名に********(4)ゃID変換失敗(5)を設定した場合該当データなしとする。
表示フィルタのアクセス許可ロールのテキスト検索でロール名に********(4)ゃID変換失敗(5)を設定した場合該当データなしとする。
