### ISSUE TITLE
【Conductor】作業履歴のアクセス権にConductorクラス一覧のアクセス権が設定される

### ISSUE THREAD

**Issue by UemuraMasumi** [exastro-suite/it-automation#519]
[ITA 1.6.0の仕様)]
Movement作業管理のアクセス権は、Movement一覧のアクセス権が引き継がれる。
Conductor作業一覧のアクセス権は、Conductorクラス一覧のアクセス権が引き継がれる。

[ITA 1.6.1での要望]
Movement作業管理のアクセス権には、実行したユーザーのロールが設定される。
Conductor作業一覧のアクセス権には、実行したユーザーのロールが設定される。

**Comment by ta-matsuo** [comment]
以下の仕様とする。

以下の2つのアクセス権のANDを取って、作業一覧とインスタンスのアクセス権に設定する。
・オペレーションのアクセス権
・Conductor/Symphony/Movementの最上位のクラスのアクセス権

アクセス権が空の場合、全部選ばれてるという前提でANDをとる。空×空は空（全選択）。
ANDが1件もない場合、作業実行させないように制御する。

以下の機能も同様の修正が必要だが、別issueで管理する。
・Symphony
・Ansible-Driver
・Terraform-Driver
