### ISSUE TITLE
【Ansible-Driver】作業履歴のアクセス権にMovement一覧のアクセス権が設定される

### ISSUE THREAD

**Issue by ta-matsuo** [exastro-suite/it-automation#522]

**Comment by ta-matsuo** [comment]
#519 のAnsible-Dviver対応。以下の仕様とする。

以下の2つのアクセス権のANDを取って、作業一覧とインスタンスのアクセス権に設定する。
・オペレーションのアクセス権
・Movement一覧のアクセス権

アクセス権が空の場合、全部選ばれてるという前提でANDをとる。空×空は空（全選択）。
ANDが1件もない場合、作業実行させないように制御する。

**Comment by enoman** [comment]
ANDをする際に、許可の無いロール(********(x))もAND対象にするが、廃止ロール(ID変換失敗(X))は対象外とする。

**Comment by enoman** [comment]
完了
