### ISSUE TITLE
【Ansible-Driver】アクセス許可ロールを使用している場合、代入値自動登録設定とパラメータシートの組み合わせにより作成するべきではないデータが作成される

### ISSUE THREAD

**Issue by ta-matsuo** [exastro-suite/it-automation#525]

**Comment by ta-matsuo** [comment]
[issue525.pdf](https://github.com/exastro-suite/it-automation/files/5658028/issue525.pdf)

**Comment by ta-matsuo** [comment]
issue525.pdfのような事象が発生する。
以下の対応を行う。

代入値自動登録設定のMomeventとパラメータシートのオペレーションのアクセス許可ロールのANDをとって、
作業対象ホストと代入値管理のアクセス許可ロールに設定する。
空×空は空で設定する。
ANDがないものは作業対象ホスト、代入値管理にデータを作成しない。

**Comment by enoman** [comment]
代入値自動登録設定のMomeventとパラメータシートのオペレーションとホスト(機器一覧)のアクセス許可ロールのANDをとって、
作業対象ホストと代入値管理のアクセス許可ロールに設定する。
空×空×空は空で設定する。
ANDがないものは作業対象ホスト、代入値管理にデータを作成しない。
ANDをする際に、許可の無いロール(********(x))もAND対象にするが、廃止ロール(ID変換失敗(X))は対象外とする。

**Comment by enoman** [comment]
完了
