### ISSUE TITLE
【Terraform-Driver】アクセス許可ロールを使用している場合、代入値自動登録設定とパラメータシートの組み合わせにより作成するべきではないデータが作成される

### ISSUE THREAD

**Issue by ta-matsuo** [exastro-suite/it-automation#526]
[issue525.pdf](https://github.com/exastro-suite/it-automation/files/5658040/issue525.pdf)

**Comment by ta-matsuo** [comment]
#525 のTerraform-Dveriver版。

issue525.pdfのような事象が発生する。
以下の対応を行う。

代入値自動登録設定のMomeventとパラメータシートのオペレーションのアクセス許可ロールのANDをとって、
代入値管理のアクセス許可ロールに設定する。
空×空は空で設定する。
ANDがないものは代入値管理にデータを作成しない。

**Comment by HibikiNanri** [comment]
マージ済み

要ドキュメント反映
