### ISSUE TITLE
【Ansible-Legacy】テンプレート管理の変数定義に対して、Null連携(有効)が機能しない。

### ISSUE THREAD

**Issue by UemuraMasumi** [exastro-suite/it-automation#528]
1. テンプレート管理の変数定義に変数を登録する。
2. 代入値自動登録設定メニューで上記の変数をNull連携(有効)で登録する。
3. 具体値取得元のパラメータシートには値を入力しない。
   代入値管理メニューに上記の変数と具体値が空で登録されることを確認。

上記の変数をテンプレート内で使用したMovementを実行すると、
想定外エラーとなり以下のエラーログが出力される。
「テンプレートファイルで使用している変数の具体値が代入値管理に登録されていません。」

※Playbookで使用している変数に対しては、Null連携(有効)が正常に機能することを確認済み
※Ansible-Roleについては未確認
※担当者へ共有済み

**Comment by enoman** [comment]
Pioneerにも同様の問題あり
完了
