### ISSUE TITLE
【全般】URLを絶対パスでアクセスしている個所を相対パスに変更する

### ISSUE THREAD

**Issue by ta-matsuo** [exastro-suite/it-automation#529]
#116 がv1.5.0で修正されていなかった。

マニュアル等からL7protcol.txtは削除されているが、v1.5.0～v1.6.0まではまだL7protcol.txtは配置すれば有効になる。

**Comment by Saito-Masaru** [comment]
sso認証のリダイレクトが機能しなくなったので要修正。

**Comment by Saito-Masaru** [comment]
直接のHTTPアクセスの場合は問題ないが、リバースproxy経由のHTTPアクセスの場合、リスエスト元のプロトコル(http or https)が確認できないことがある。  
* apacheのmod_proxyを使ったりバースproxyなど

awsのELB(alb,clb)では`X_FORWADED_PROTO`ヘッダーで確認可能。  
https://aws.amazon.com/jp/premiumsupport/knowledge-center/redirect-http-https-elb/  
https://qiita.com/fururun02/items/56475ddad5300201bfbf  

上記より、現在事実上使われなくなった`getRequestProtocol`関数を上記より判定するように修正する。

また、負荷分散等でITAのWEBサーバを複数設置する場合、従来ホスト名取得に使っている`HTTP_HOST`とリクエスト元ホスト名が異なる場合がある。  
この場合、リバースproxy側でITAのWEBサーバにリクエスト元のホスト名を`X_FORWARDED_HOST`として送信している。  
上記より、リクエスト元ホスト名を取得する`getRequestHost`関数を追加する。
(今のところsession名の設定とsso認証で利用となる)

なお、apacheなどのリバースproxy環境で`X_FORWARDED_PROTO`を送信していない場合はその設定方法をドキュメントへの追記でアナウンスしてフォローしたい。
