### ISSUE TITLE
【Ansible共通】機器一覧で機器登録に合わせた疎通確認ボタンが欲しい

### ISSUE THREAD

**Issue by kubo-1** [exastro-suite/it-automation#542]
登録した機器のログイン情報があっているかを確認できるように、Ansibleドライバインストール済みのユーザにだけ「疎通確認ボタン」を出現させてほしい。

**Comment by ta-matsuo** [comment]
疎通確認がどのプロトコルでの疎通であるか、HA構成にした場合にどのサーバからの疎通なのか、など有益な疎通確認を行うのがよいのか決定するのが困難であるため、本issueは対応しない。
