### ISSUE TITLE
【全般】select countの定義があるVIEWのデータに対してアクセス許可ロールによるデータ絞り込みの対応

### ISSUE THREAD

**Issue by enoman** [exastro-suite/it-automation#559]
1.6.1のWebDBCoreでは、select countの定義があるVIEWのデータに対してアクセス許可ロールによるデータ絞り込みが対応出来ていない。
CREATE VIEW xxxxxx AS 
SELECT 
      xxxxx,
      (SELECT  COUNT(*)  FROM  xxxxx  WHERE  xxxxx ) COUNT
FROM xxxxx

該当するメニュー 項目
ansible legacy Movement一覧->変数カウント
ansible legacy-role Movement一覧->変数カウント
ansible pioneer Movement一覧->変数カウント

**Comment by ta-matsuo** [comment]
変数カウント機能を削除する。

**Comment by enoman** [comment]
完了
