### ISSUE TITLE
代入値自動登録設定のプルダウンに廃止されたものが表示される。

### ISSUE THREAD

**Issue by sinatommy** [exastro-suite/it-automation#57]
メニュー管理から廃止しても代入値自動登録設定のプルダウンに表示されたままになっているのを対処する。

**Comment by ta-matsuo** [comment]
入値自動登録設定のプルダウンに使用しているVIEW(D_CMDB_MENU_LIST)に、メニュー管理のテーブル(A_MENU_LIST)が廃止状態ではないというWHERE句を追加する。

**Comment by ta-matsuo** [comment]
払戻完了。
