### ISSUE TITLE
【インストーラ】オンラインインストールのエラーハンドリング

### ISSUE THREAD

**Issue by sinatommy** [exastro-suite/it-automation#58]
オンラインインストール時にpearのインストールに失敗しても処理が続いてしまう。エラーハンドリングが必要。

**Comment by ta-matsuo** [comment]
インストーラの最後に必要なパッケージがそろっているかチェック処理も追加する。

**Comment by h-matsuhashi** [comment]
払戻完了。
ドキュメントの修正あり。
