### ISSUE TITLE
【全般】全体のメニュー名やレコードのカラム名の整理

### ISSUE THREAD

**Issue by sinatommy** [exastro-suite/it-automation#596]
全体の文言の見なおし。
メニュー名や、メニュー内のレコードの項目名など、分かりづらい表記を整理したい。

**Comment by enoman** [comment]
機器一覧
ssh認証鍵ファイル=>ssh公開鍵ファイル
Ansible Towerのホスト一覧
ssh認証鍵ファイル=>ssh公開鍵ファイル

**Comment by a-koizumi** [comment]
【気になること】
１．GUI化されたメニュー(「メニュー定義/作成」/「Conductorクラス編集」)に吹き出しコメントがないのでMAXサイズなどわからないことが多い
２．作成したメニューのメニュグループ入力用のホスト名の吹き出しコメントが「choose host」何でここだけ英語？
３．Terraform Enterprise登録管理の各登録一覧を表示して
table settingで表示内容を消してApplyしたときのエラーメッセージが英語になっている(No columns to display.)何でここだけ英語？
４．(メニューエクスポートでアクセス許可ロールの設定しないので)「エクスポート/インポート管理」のアクセス権・アクセス許可ロールの項目はいらないのでは?

**Comment by yoshi-kooooh** [comment]
お待たせしました。
a-koizumi氏に続き、私からも本issueに関する期待とお願いです。

下記の通りです。

================================================================
(01)「基本コンソール」の「投入オペレーション一覧」
    ⇒"投入"という接頭語はいらない気がする。シンプルに「オペレーション一覧」で良い気が。。。
(02)「Ansible-Legacy」コンソールの「Movement詳細」
    ⇒「Movement-Playbook紐付」という名前にしたほうが分かりやすい
(03)「Ansible-Legacy」コンソールの「プレイブック素材集」
    ⇒カタカナはダサい。。。「Playbook素材集」にすれば。
    ⇒また、項目名(プレイブック素材名、プレイブック素材)も、カタカナは撲滅でヨロ。
(04)「Ansible-Pioneer」コンソールの「Movement詳細」
    ⇒「Movement-対話種別紐付」という名前にしたほうが分かりやすい
(05)「Ansible-LegacyRole」コンソールの「Movement詳細」
    ⇒「Movement-ロール紐付」という名前にしたほうが分かりやすい
(06)「Ansible-LegacyRole」コンソールの「多段変数最大繰返数管理」
    ⇒名前がね・・・
      「変数ネスト管理」という名前はいかが？
(07)「Terraform」コンソールの「Movement詳細」
    ⇒「Movement-Module紐付」という名前にしたほうが分かりやすい
================================================================

**Comment by wakkysan** [comment]
私も気づきがあったので、共有します。

SymphonyやConductorのロール権限付与できる項目名について、
Conductorだと「Permission role」ってなってて、Symphonyだと「Symphonyロール」ってなっているので、
「Permission role」に名称を統一したほうがよいと思います。

**Comment by a-koizumi** [comment]
wakkysanさんの気づきに便乗して以下はいかがでしょうか？
（Symphonyの「Symphonyクラス編集」の文言を、Conductorの「Conductorクラス編集」に合わせてほしい。）

(01)「Symphony」の「Symphonyクラス編集」の「選択」　
　⇒　「Permission role select」
(02)「Symphony」の「Symphonyクラス編集」の説明
　⇒　Note
(03)「Symphony」の「Symphonyクラス編集」の一時停止
　⇒　Default skip
(04)「Symphony」の「Symphonyクラス編集」の並び順「再読込　更新　キャンセル」
　⇒　「更新　再読込　キャンセル」
(05)「Symphony」の「Symphonyクラス編集」のフィルタをクリア
　⇒　Clear filter
(06)「Symphony」の「Symphonyクラス編集」のフィルタ
　⇒　filter
(07)「Symphony」の「Symphonyクラス編集」のオートフィルタ
　⇒　Auto filter
(08)「Symphony」の「Symphonyクラス編集」の表示フィルタ
　⇒　Display filter
(09)「Symphony」の「Symphonyクラス編集」の内容
　⇒　Name Fillter
(10)「Symphony」の「Symphonyクラス編集」の自動採番
　⇒　Auto numbering
(11)「Symphony」の「Symphonyクラス編集」のオペレーションID(個別指定)
 　⇒　Operation(Operation select)

**Comment by ta-matsuo** [comment]
メニュー名称にスラッシュが入っていると「メニュー管理」で更新ができないため、メニュー名を変更する。

エクスポート/インポート管理⇒エクスポート-インポート管理
メニュー定義/作成⇒メニュー定義-作成

**Comment by enoman** [comment]
【ansible共通】ansibleインターフェース情報で代表ホスト未選択時のメッセージ改修
修正前「必須項目」ホスト
修正後「必須項目」代表ホスト
