### ISSUE TITLE
【全般】ジャンプボタンを付けて、メニュー間のつながりを分かりやすくする

### ISSUE THREAD

**Issue by sinatommy** [exastro-suite/it-automation#597]
全体的に、関連するメニュー間にジャンプボタンを付けて、メニューとメニューのつながりを分かりやすくしたい。

**Comment by yoshi-kooooh** [comment]
お待たせしました。
本issueに関する期待とお願いをまとめました！

下記の通りです。

(08)[管理コンソール]の[メニューグループ管理]
    ⇒「メニュー情報」ボタンを押すと「メニュー情報」サブメニューに画面内移動するのはOK。
      「メニュー情報」サブメニュー内の「メニュー情報」リストについて、メニューIDなりメニュー名称をクリックすると「メニュー管理」にジャンプ＆絞り込みが希望
(09)[管理コンソール]の[メニュー管理]
    ⇒メニューグループIDなりメニューグループ名称をクリックすると「メニューグループ管理」にジャンプ＆絞り込みが希望
(10)[管理コンソール]の[メニュー管理]
    ⇒「ロール情報」ボタンを押すと「ロール情報」サブメニューに画面内移動するのはOK。
      「ロール情報」サブメニュー内の「ロール情報」リストについて、ロールIDなりロール名称をクリックすると「ロール管理」にジャンプ＆絞り込みが希望
(11)[管理コンソール]の[ロール管理]
    ⇒「ユーザ情報」ボタンを押すと「ユーザ情報」サブメニューに画面内移動するのはOK。
      「ユーザ情報」サブメニュー内の「ユーザ情報」リストについて、ユーザIDなりユーザ名をクリックすると「ユーザ管理」にジャンプ＆絞り込みが希望
(12)[管理コンソール]の[ロール管理]
    ⇒「メニュー情報」ボタンを押すと「メニュー情報」サブメニューに画面内移動するのはOK。
      「メニュー情報」サブメニュー内の「メニュー情報」リストについて、メニューIDなりメニュー名称をクリックすると「メニュー管理」にジャンプ＆絞り込みが希望
      また、同様に「メニューグループ名称」をクリックすると「メニューグループ管理」にジャンプ＆絞り込みが希望
(13)[管理コンソール]の[ロール・メニュー紐付管理]
    ⇒ロールIDなりロール名称をクリックすると「ロール管理」にジャンプ＆絞り込みが希望
    ⇒同様に、メニューグループIDなりメニューグループ名称をクリックすると「メニューグループ管理」にジャンプ＆絞り込みが希望
    ⇒同様に、メニューIDなりメニュー名称をクリックすると「メニュー管理」にジャンプ＆絞り込みが希望
(14)[管理コンソール]の[ロール・ユーザ紐付管理]
    ⇒ロールIDなりロール名称をクリックすると「ロール管理」にジャンプ＆絞り込みが希望
    ⇒同様に、ユーザIDなりログインIDをクリックすると「ユーザ管理」にジャンプ＆絞り込みが希望
(15)「メニュー作成」コンソールの「メニュー定義一覧」
    ⇒入力用メニューグループをクリックすると「メニューグループ管理」にジャンプ＆絞り込みが希望
    ⇒同様に、代入値自動登録用メニューグループをクリックすると「メニューグループ管理」にジャンプ＆絞り込みが希望
    ⇒同様に、参照用メニューグループをクリックすると「メニューグループ管理」にジャンプ＆絞り込みが希望
(16)「Ansible共通」コンソールの「収集項目値管理」
    ⇒メニューIDなりメニュー名称をクリックすると対象のメニューにジャンプが希望
(17)「Ansible-Legacy」コンソールの「Movement一覧」
    ⇒(「Movement詳細」あらため)「Movement-Playbook紐付」にジャンプ＆絞り込みするボタンが欲しい
(18)「Ansible-Legacy」コンソールの「プレイブック素材集」(あらため「Playbook素材集」)
    ⇒(「Movement詳細」あらため)「Movement-Playbook紐付」にジャンプ＆絞り込みするボタンが欲しい
(19)「Ansible-Legacy」コンソールの「Movement詳細」(あらため「Movement-Playbook紐付」)
    ⇒Movementをクリックすると「Movement一覧」にジャンプ＆絞り込みが希望
    ⇒同様に、プレイブック素材(あらため「Playbook素材名」("名"がついてるほう！)をクリックすると「Playbook素材集」にジャンプ＆絞り込みが希望
(20)「Ansible-Legacy」コンソールの「代入値自動登録設定」
    ⇒メニューIDなりメニュー名称をクリックすると対象のメニューにジャンプが希望
(21)「Ansible-Legacy」コンソールの「作業対象ホスト」
    ⇒Movementをクリックすると「Movement詳細」(あらため「Movement-Playbook紐付」)にジャンプ＆絞り込みが希望
    ⇒また、「代入値管理」にジャンプ＆絞り込みするボタンが欲しい
      (オペ＋Mov＋ホスト、の3キーで絞り込むんだと思う。)
(22)「Ansible-Pioneer」コンソールの「Movement一覧」
    ⇒(「Movement詳細」あらため)「Movement-対話種別紐付」にジャンプ＆絞り込みするボタンが欲しい
(23)「Ansible-Pioneer」コンソールの「対話種別リスト」
    ⇒(「Movement詳細」あらため)「Movement-対話種別紐付」にジャンプ＆絞り込みするボタンが欲しい
    ⇒同じく「対話ファイル素材集」にジャンプ＆絞り込みするボタンが欲しい
(24)「Ansible-Pioneer」コンソールの「OS種別マスタ」
    ⇒「対話ファイル素材集」にジャンプ＆絞り込みするボタンが欲しい
(25)「Ansible-Pioneer」コンソールの「対話ファイル素材集」
    ⇒対話種別をクリックすると「対話種別リスト」にジャンプ＆絞り込みが希望
    ⇒同じく、OS種別をクリックすると「OS種別マスタ」にジャンプ＆絞り込みが希望
(26)「Ansible-Pioneer」コンソールの「Movement詳細」(あらため「Movement-対話種別紐付」)
    ⇒Movementをクリックすると「Movement一覧」にジャンプ＆絞り込みが希望
    ⇒同様に、対話種別をクリックすると「対話種別リスト」にジャンプ＆絞り込みが希望
(27)「Ansible-Pioneer」コンソールの「代入値自動登録設定」
    ⇒メニューIDなりメニュー名称をクリックすると対象のメニューにジャンプが希望
(28)「Ansible-Pioneer」コンソールの「作業対象ホスト」
    ⇒Movementをクリックすると「Movement詳細」(あらため「Movement-対話種別紐付」)にジャンプ＆絞り込みが希望
    ⇒また、「代入値管理」にジャンプ＆絞り込みするボタンが欲しい
      (オペ＋Mov＋ホスト、の3キーで絞り込むんだと思う。)
(29)「Ansible-LegacyRole」コンソールの「Movement一覧」
    ⇒(「Movement詳細」あらため)「Movement-ロール紐付」にジャンプ＆絞り込みするボタンが欲しい
(30)「Ansible-LegacyRole」コンソールの「ロールパッケージ管理」
    ⇒(「Movement詳細」あらため)「Movement-ロール紐付」にジャンプ＆絞り込みするボタンが欲しい
(31)「Ansible-LegacyRole」コンソールの「Movement詳細」(あらため「Movement-ロール紐付」)
    ⇒Movementをクリックすると「Movement一覧」にジャンプ＆絞り込みが希望
    ⇒同様に、ロールパッケージ名をクリックすると「ロールパッケージ管理」にジャンプ＆絞り込みが希望
(32)「Ansible-LegacyRole」コンソールの「代入値自動登録設定」
    ⇒メニューIDなりメニュー名称をクリックすると対象のメニューにジャンプが希望
(33)「Ansible-LegacyRole」コンソールの「作業対象ホスト」
    ⇒Movementをクリックすると「Movement詳細」(あらため「Movement-ロール紐付」)にジャンプ＆絞り込みが希望
    ⇒また、「代入値管理」にジャンプ＆絞り込みするボタンが欲しい
      (オペ＋Mov＋ホスト、の3キーで絞り込むんだと思う。)
(34)「Terraform」コンソールの「Organizations管理」
    ⇒「WorkSpace管理」にジャンプ＆絞り込みするボタンが欲しい
(35)「Terraform」コンソールの「WorkSpace管理」
    ⇒Orgenizationをクリックすると「Organizations管理」にジャンプ＆絞り込みが希望
    ⇒また、「Movement一覧」にジャンプ＆絞り込みするボタンが欲しい
    ⇒また、「PolicySet-WorkSpace紐付管理」にジャンプ＆絞り込みするボタンが欲しい
(36)「Terraform」コンソールの「Movement一覧」
    ⇒(「Movement詳細」あらため)「Movement-Module紐付」にジャンプ＆絞り込みするボタンが欲しい
(37)「Terraform」コンソールの「Module素材集」
    ⇒(「Movement詳細」あらため)「Movement-Module紐付」にジャンプ＆絞り込みするボタンが欲しい
(38)「Terraform」コンソールの「Policies管理」
    ⇒「PolicySet-Policy紐付管理」にジャンプ＆絞り込みするボタンが欲しい
(39)「Terraform」コンソールの「Policy Sets管理」
    ⇒「PolicySet-Policy紐付管理」にジャンプ＆絞り込みするボタンが欲しい
(40)「Terraform」コンソールの「Policy Sets管理」
    ⇒「PolicySet-WorkSpace紐付管理」にジャンプ＆絞り込みするボタンが欲しい
(41)「Terraform」コンソールの「PolicySet-Policy紐付管理」
    ⇒Policy Setをクリックすると「Policy Sets管理」にジャンプ＆絞り込みが希望
    ⇒Policyをクリックすると「Policies管理」にジャンプ＆絞り込みが希望
(42)「Terraform」コンソールの「PolicySet-WorkSpace紐付管理」
    ⇒Policy Setをクリックすると「PolicySet-Policy紐付管理」にジャンプ＆絞り込みが希望
    ⇒Organization:Workspaceをクリックすると「WorkSpace管理」にジャンプ＆絞り込みが希望
(43)「Terraform」コンソールの「Movement詳細」(あらため「Movement-Module紐付」)
    ⇒Movementをクリックすると「Movement一覧」にジャンプ＆絞り込みが希望
    ⇒同様に、Module素材をクリックすると「Module素材集」にジャンプ＆絞り込みが希望
(44)「Terraform」コンソールの「代入値自動登録設定」
    ⇒メニューIDなりメニュー名称をクリックすると対象のメニューにジャンプが希望
(45)ダッシュボードの「Movement」ウィジェット
    ⇒円のところやSUMの数字のところをクリックしたら、Movement一覧にジャンプ＆絞り込みが希望
(46)「Conductor」コンソールの「Conductor定期作業実行」
    ⇒Conductor名称をクリックすると「Conductorクラス編集」にジャンプ＆該当のConductorの構造を見せてあげるのが希望

**Comment by yoshi-kooooh** [comment]
以下の観点については、私のほうではちゃんと考え切れていません。
開発コミュニティーのみなさんで、ご検討をお願いします。
★ブランク(別ウィンドウ or 別タブ)でジャンプしたほうが良いのか、画面遷移なのか？
   ※ジャンプ箇所ごとに色があると思う。
★履歴はどうすればよいのか？
   ※「履歴もジャンプすべき」 or 「履歴はジャンプしなくていいや」を決めねばだと思います。

**Comment by ta-matsuo** [comment]
基本的な方針として
・ブランク(別ウィンドウ or 別タブ)でジャンプ
・履歴はジャンプしなくていいや
で行きます。
問題ありそうなら個別に検討します。

**Comment by ta-matsuo** [comment]
対応内容が多いためissueを分割して管理する。
管理コンソールに関する修正(8)～(14)　⇒　issue #703 
メニュー作成に関する修正(15)　⇒　issue #704 
Ansible-Driverに関する修正(16)～(33)　⇒　issue #705
Terraform-Driverに関する修正(34)～(44)　⇒　issue #706
ダッシュボードに関する修正(45)　⇒　issue #707
Conductorに関する修正(46)　⇒　issue #708
