### ISSUE TITLE
【インストーラ】オフラインインストールパッケージ作成時のアンインストール処理追加

### ISSUE THREAD

**Issue by mtakahashiif** [exastro-suite/it-automation#6]
オフラインインストール用収集スクリプトで、収集サーバに必要なパッケージがすでにインストールされていて収集ができない場合は、パッケージをアンインストールしてから収集を行うようにする。

**Comment by ta-matsuo** [comment]
収集サーバとオフラインインストールするサーバの状態は合わせておく前提なので、対応無し。
