### ISSUE TITLE
【全般】暗号化対応ファイルアップロードカラムの実装

### ISSUE THREAD

**Issue by j-kumamoto** [exastro-suite/it-automation#637]
暗号化対応ファイルアップロードカラムの実装を行う。

機器一覧の認証鍵のファイルアップロードは上記の暗号化対応カラムを
標準で使用する仕様とする。

**Comment by enoman** [comment]
機器一覧のAnsible Towerホスト一覧のssh鍵ファイルを対象とする。
ky_encryptで暗号化したファイルをITAで保管する。
Legacy/Role利用時はansible-vaultで暗号化したファイルをansibleに渡す。
pioneer利用時はky_encryptで暗号化されているファイルをansible(pioneerモジュール)に渡す。

**Comment by enoman** [comment]
ansible-vaultで暗号化した秘密鍵ファイル（パスフレーズなし）を使用しターゲットにssh接続すると
パスフレーズを求めてくるようで、ansible-playbookが異常終了します。
サポートに問い合わせをしたところ
機能改善中との回答が返ってきています。

1.7では以下の対応とします。
ダウンロードしたファイルはky_encryptでスクランブル
ansibleに渡す秘密鍵ファイルはky_decryptで復号化したファイルを渡す。(今まで通り)
Towerの場合も同様とします。

==============================
サポートからの回答
==============================
弊社検証環境でも同様の事象が再現できました。

ansible_ssh_private_key_file に暗号化したファイルを指定したいという要望は機能改善要求として起票はされているのですが、現在のところ修正は取り込まれておりません。

Allow ssh private keys to be used that are encrypted with vault
https://github.com/ansible/ansible/issues/22382

**Comment by enoman** [comment]
1.7では以下の対応しました。
ダウンロードしたファイルはky_encryptでスクランブル
ansibleに渡す秘密鍵ファイルはky_decryptで復号化したファイルを渡す。(今まで通り)
Towerの場合も同様とします。
---------------------------
ky_encryptで暗号化したファイルをITAで保管は
FileUploadColumnクラスに下記メゾットを追加
setFileEncryptFunctionName("ky_file_encrypt");
