### ISSUE TITLE
【Conductor/Symphony】メニューインポートでインストール時のデータに戻した際の作業一覧の表示改善

### ISSUE THREAD

**Issue by ta-matsuo** [exastro-suite/it-automation#648]

**Comment by y-yonekura** [comment]
Symphony作業一覧：Symphony名称　IDColumnからTextColumnに変更
Symphony作業確認：インスタンスのデータ取得処理内で、オペレーションIDでの問い合わせ処理の廃止
　　　　　　　　　  インスタンスのデータ取得処理内で、MovemntIDでの問い合わせ処理の廃止
　　　　　　　　　
Conductor作業確認：インスタンスのデータ取得の際に、オペレーションIDで問い合わせ処理の廃止
　　　　　　　　　  描画用のMovement情報の取得を変更
　　　　　　　　　  描画用のConductor/Symphony Call 用情報の取得を変更
　　　　　　　　　  描画しているCALLノード内の表示を変更 ( [ID]：名称→名称 )
