### ISSUE TITLE
【メニュー作成】Web画面でマルチユニークの設定できるようにする

### ISSUE THREAD

**Issue by sudodaisuke-jp** [exastro-suite/it-automation#653]
マルチユニークの設定はloadTableからはが可能すが、Web画面設定できないためWeb画面からも設定出来るようにすると便利です。

**Comment by HibikiNanri** [comment]
■仕様
メニュー定義・作成ページ操作
・「メニュー定義・作成」ページの右メニューに「一意制約(複数項目)」のエリアを追加。
・「一意制約(複数項目)選択」ボタンをクリックで、設定用モーダルが開く。
![653_1](https://user-images.githubusercontent.com/51319083/122181676-8b3ee980-cec4-11eb-9354-2f40a20f7a6b.png)

以下モーダル操作
・「パターンを追加」ボタンをクリックで、組み合わせのパターンが1つ画面に追加される。
・パターンには現在の項目がすべて表示され、項目をクリックすることで一意制約にしたい項目の組み合わせを設定できる。
・パターンは複数設定可能。
・「削除」ボタンクリックで対処のパターンを削除。
・「決定」ボタンをクリックで「メニュー定義・作成」ページに反映される。
![653_2](https://user-images.githubusercontent.com/51319083/122181748-9abe3280-cec4-11eb-849b-c240b960585e.png)
![653_3](https://user-images.githubusercontent.com/51319083/122181777-a0b41380-cec4-11eb-8d4d-7d02368c4c6c.png)
![653_4](https://user-images.githubusercontent.com/51319083/122181856-b32e4d00-cec4-11eb-8cb4-c6b5e603806f.png)

バリデーションチェック
・1つのパターンに、項目が1つしか選択されていない場合はバリデーションエラー。
・同じ項目の組み合わせのパターンがある場合はバリデーションエラー。

その他
・「一意制約(複数項目)」の設定データは[メニュー作成] > [一意制約(複数項目)作成情報]ページにて管理（デフォルトで非表示メニュー）。
→1パターンで1レコード。項目の組み合わせは、項目のIDをカンマ区切りで管理する（例：1,2,3）。

**Comment by HibikiNanri** [comment]
■[メニュー作成]グループのメニューについて、表示順序(DISP_SEQ)を修正。
メニュー定義・作成　　　　：1→10
メニュー定義一覧　　　　　：2→20
カラムグループ管理　　　　：3→30
メニュー項目作成情報　　　：4→40
メニュー(縦)作成情報　　　 ：5→50
一意制約(複数項目)作成情報 ：　60(新規作成)
メニュー作成実行　　　　　：6→70
メニュー作成履歴　　　　　：7→80
メニュー・テーブル紐付　　：101→210
他メニュー連携　　　　　　：103→220
メニュー縦横変換管理　　　：104→230
参照項目情報　　　　　　　：105→240
選択1　　　　　　　　　　 ：106→250
選択2　　　　　　　　　　 ：107→260

**Comment by HibikiNanri** [comment]
マージ済み。
要ドキュメント修正。
