### ISSUE TITLE
仕様確認：「メニュー作成」コンソールの「メニュー定義一覧」

### ISSUE THREAD

**Issue by yoshi-kooooh** [exastro-suite/it-automation#699]
「更新」をクリックすると、ここだけ何故かテーブルがエメラルドグリーンです。
意図的なのか、念のため確認をお願いします。

**Comment by sinatommy** [comment]
パラメータシートとデータシートを区別するため、パラメータシートはエメラルドグリーン、データシートは紫になります。
ドキュメントに記載します。
