### ISSUE TITLE
【インストーラ】ITA発行の自己署名証明書の廃止

### ISSUE THREAD

**Issue by mtakahashiif** [exastro-suite/it-automation#7]
ITA画面はHTTPS通信を行うため、自己署名証明書を利用しているが、あまり良い仕様ではない。
クライアント側に自己署名証明書のROOT証明書をインポートする必要がある点もよくはない。
　⇒対策案②がいいか？

[対策案①]
通常のOSSのように、インストーラで入れた状態ではHTTP通信とする。
HTTPS通信にしたい場合は、ユーザが設定しなくてはならない。
HTTPS通信にする手順は公開する。

[対策案②]
インストールの際に、ユーザが事前に用意した証明書をanswerファイルにパス指定すれば、HTTPS設定を行う機能を追加する。
HTTP通信かHTTPS通信かをユーザが選択可能とし、
HTTPS通信の場合は、ユーザの用意した証明書の指定を必須とする。
証明書は、認証機関が発行したものでも、自己署名証明書でも問わない。

※参考
Ansible Towerは自己署名証明書を使用しているようだ。
https://docs.ansible.com/ansible-tower/3.4.3/html_ja/installandreference/install_notes_reqs.html

**Comment by sinatommy** [comment]
対策案②で実施する。

SSL/TLS証明書を入れ替える手順をドキュメントに追記する。

**Comment by sinatommy** [comment]
ドメインもインストーラのanswerファイルから変更できるようにする。

**Comment by h-matsuhashi** [comment]
仕様
◆ita_answers.txtに秘密鍵・サーバ証明書・ドメイン名を指定する項目を追加。
・certificate_path（任意）
　初期値:
　ユーザ指定の証明書ファイルが置いてあるファイルパスを入力（絶対パス）
・private_key_path（任意）
　初期値:
　ユーザ指定の秘密鍵ファイルが置いてあるファイルパスを入力（絶対パス）
・ita_domain（必須）
　初期値：exastro-it-automation.local
　ITAのドメイン名を指定。
　未入力の場合、ita_installer.shのita_answers.txt読み込み時に異常終了。
　※ita_domainの値は以下に反映する。
　・自己証明書作成に使う証明書署名要求ファイル作成時のCommon Name
　・自己証明書、秘密鍵、証明書署名要求ファイルのファイル名
　・vhosts_exastro-it-automation.confのServerName
　・/etc/hostsのホスト名

◆certificate_path、private_key_pathへの入力状況によって、ITAインストール時のサーバ証明書・証明書設置を分岐・
・certificate_pathとprivate_key_pathの両方にファイルパスが入力されている場合
　－ それぞれのファイルパスの場所にファイルがあるかを確認。
　－ どちらにもファイルがあることを確認出来たら、指定の証明書ファイルと秘密鍵ファイルを/etc/pki/tls/certs/にコピーする。
　－ どちらか一方でもファイルがない場合は、エラーメッセージを表示して異常終了。

・certificate_pathとprivate_key_pathのどちらにもファイルパスが入力されていない場合
　－ ITAインストーラーで秘密鍵ファイル・証明書署名要求ファイル・自己証明書ファイルをそれぞれ作成。
　　（秘密鍵ファイル:[ita_domainの値].key、証明書署名要求ファイル:[ita_domainの値].csr、自己証明書ファイル:[ita_domainの値].crt）
　　※証明書署名要求ファイル作成時の対話は自動入力。Country NameをJP、Common Nameを[ita_domainの値]に設定し、その他は全てブランク。
　－ 作成した秘密鍵ファイルと自己証明書ファイルを/etc/pki/tls/certs/に移動し、証明書署名要求ファイルは削除。
・certificate_pathとprivate_key_pathのどちらか一方だけファイルパスが入力されている場合
　－ エラーメッセージを表示して異常終了
・最後に/etc/pki/tls/certs/に秘密鍵ファイルとサーバ証明書を設置できたかを確認する。
　－ 設置できていなかったら WARNINGメッセージを表示。

◆vhosts_exastro-it-automation.confの下記の部分にita_domainの値と、秘密鍵ファイル名・証明書ファイル名を反映。
  ServerName   %%%%%ITA_DOMAIN%%%%%
　～
  SSLCertificateFile    /etc/pki/tls/certs/%%%%%CERTIFICATE_FILE%%%%%
  SSLCertificateKeyFile /etc/pki/tls/certs/%%%%%PRIVATE_KEY_FILE%%%%%
　※置換用文字を設置し、それらを置換して反映。

◆/etc/hostsに書き込むホスト名にita_domainの値を追加・
　127.0.0.1     [ita_domainの値] exastro-it-automation

◆Uninstall時に削除するサーバ証明書と秘密鍵は、ITA設置のファイル・ユーザ指定のファイルどちらも対象にする。
　－ vhosts_exastro-it-automation.confからファイル名を取得し、サーバ証明書と秘密鍵のファイルを削除する。
　※マニュアルにユーザ指定の証明書と秘密鍵を使う場合、オリジナルを別で保管するように注意喚起文記載する。

◆ita_installer.sh内、ita_answers.txtの値取り込み部分の仕様を変更。
　－ 任意入力の項目の取り込みに対応。

**Comment by h-matsuhashi** [comment]
10/22 一通り実装完了。動作確認中

**Comment by h-matsuhashi** [comment]
作業完了。マージ済み。
ドキュメントの修正あり。

**Comment by j-kumamoto** [comment]
●中間証明書付き証明書の追加試験について

インストール時のユーザのサーバ証明書の登録において、
中間証明書付き証明書の適用を検証。

手順は以下のようにcatコマンドなどで、
（cat [サーバ証明書] [中間証明書] > [連結済サーバ証明書]）
用意したサーバ証明書と中間証明書を連結し新しいファイルを作成、
通常のサーバ証明書の登録同様、作成ファイルのパスをインストーラーで指定する。

連結コマンド実施例）
cat server.pem inca.pem > serverinca.pem

上記方法で作成した証明書をインストーラーで登録し、
問題なくSSL通信が可能なことを確認。

**Comment by j-kumamoto** [comment]
●自己証明作成の問題点とその対処方法について

信頼できるルート証明書に登録し、ドメイン名を一致させても
最新のChromeやEdgeでは警告がでてしまう。
（ITA1.5.0以下でも発生する）
 
●警告メッセージ
「NET::ERR_CERT_COMMON_NAME_INVALID」
https://tech.torico-corp.com/blog/chrome58-https-ssl-cert-san-error/
https://qiita.com/nis_nagaid_1984/items/b8f87d41ea108d47af61
 
●インストーラにおいての対処案
　chromeは証明書のCN名だけでなく、SAN（代替サブジェクト名）も
チェックする仕様に変更されているため、自己証明書を作成する際に、
SAN要素にも対象ドメイン名を追加する。

●修正イメージ

【修正前】　
openssl x509 -days 3650 -req -signkey /tmp/exastro-it-automation.local.key -extfile /tmp/san.txt < /tmp/exastro-it-automation.local.csr > /tmp/exastro-it-automation.local.crt
 
【修正例】
**echo "subjectAltName = DNS:exastro-it-automation.local" > /tmp/san.txt**
openssl x509 -days 3650 -req -signkey /tmp/exastro-it-automation.local.key **-extfile /tmp/san.txt** < /tmp/exastro-it-automation.local.csr > /tmp/exastro-it-automation.local.crt
