### ISSUE TITLE
「Ansible共通」コンソールの「収集インタフェース情報」にデフォルトユーザが欲しい

### ISSUE THREAD

**Issue by yoshi-kooooh** [exastro-suite/it-automation#700]
RESTユーザ/PWを指定できるのは良いが、利用開始時にはカラッポなので困った。
また、収集が動かなかったので解析しようと思ったが、
「ここが原因で収集できなかったこと」に気づくのが難しく、途方に暮れた。

[解決案]
デフォルトの専用アカウントをインストールとともに敷き込むのはいかがでしょうか？
RESTユーザ/PWを指定できる機能を残してもOK。
(どちらかといえば、「指定しようと思えば指定できる」という機能は悪いことではないと思います。)
 その場合は、指定 or 指定しないをラジオ選択させて、指定する場合は入力させるGUIをイメージしております。

**Comment by ta-matsuo** [comment]
事前にユーザを用意しておくとセキュリティ的に問題があるため、本issueは対応しない。
