### ISSUE TITLE
【全般】ITAインストール時のDBとPHPのリソース設定値を上げる

### ISSUE THREAD

**Issue by sinatommy** [exastro-suite/it-automation#71]
ITAのインストール時のDBとPHPのリソース関係の初期値を上げる。
2CPU/メモリ4Gに最適な値にする。
インストールのドキュメントに、インストール時は2CPU/メモリ4G用の設定値である旨を記載する。

**Comment by sinatommy** [comment]
インストールドキュメントに、設定値はオールインワンではなく、ITA単体の最適値である旨も記載する。

**Comment by sinatommy** [comment]
・DB設定
innodb_buffer_pool_size	256→512
innodb_log_buffer_size	32→64
innodb_log_file_size	128→256
join_buffer_size	64→128
query_cache_size	256→512
max_heap_table_size	32→64
tmp_table_size	32→64
mrr_buffer_size	32→64
max_connections	151→256

・Apache設定
Timeout	300→600

**Comment by HibikiNanri** [comment]
払戻し完了
