### ISSUE TITLE
【全般】メインメニューに作業履歴のグラフ等を掲載

### ISSUE THREAD

**Issue by wakkysan** [exastro-suite/it-automation#72]
作業管理に掲載しているグラフをメインメニューのパネル群の下に掲載し、
Dashboardのように進化させたい。

**Comment by ayaka-shinomiya** [comment]
ロールの有無でメニューグループの表示を出しわける
（グラフも同様）

**Comment by ayaka-shinomiya** [comment]
現在作業履歴に表示されているグラフをメインメニューに引っ越しさせ、デザインをリニューアルする
・パネル下部の数値をクリックするとプレイブック一覧等に飛べるようになると良い

**Comment by ayaka-shinomiya** [comment]
最新のイベントログを表示させる

**Comment by ayaka-shinomiya** [comment]
ウィジェットにURLやAPIを埋め込めるようにする

**Comment by ayaka-shinomiya** [comment]
お気に入りのメニュー一覧を登録できるようにする。

**Comment by ayaka-shinomiya** [comment]
10/15 進捗
・細かいところの修正中
・画面作成中

**Comment by ayaka-shinomiya** [comment]
【備忘】各ドライバの作業管理のグラフの削除：担当者未定

**Comment by ayaka-shinomiya** [comment]
10/22
・自分自身を埋め込むことを禁止にする
