### ISSUE TITLE
【Terraform-driver】複数代入値を持つ変数の扱い

### ISSUE THREAD

**Issue by yoshi-kooooh** [exastro-suite/it-automation#723]
TerraformのHCLで、
security_groups = [var.security_groups]
といった具合に、
複数の値を渡すさいにはリスト型を使うケースがある。
(HCLリスト：[ “foo”, “bar” ] みたいな感じ)

これとパラメータシートを紐づける場合に、
Ansibleドライバと似たような発想で、代入順序といった考え方を設けることはできないだろうか？
そうすることで、リストの要素を可変的にできる気がする。

**Comment by ayaka-shinomiya** [comment]
ドキュメントにメンバー変数の詳細を記載する

**Comment by ayaka-shinomiya** [comment]
${文字列}という書き方を禁止する旨を記載する

**Comment by ta-matsuo** [comment]
インストーラでterraform_driverがyesの場合、pipライブラリpython-hcl2をインストールするように修正。
