### ISSUE TITLE
【全般】パスワード項目の初期表示の統一

### ISSUE THREAD

**Issue by ta-matsuo** [exastro-suite/it-automation#725]
パスワード項目に値が入っていない場合、空白で表示されるメニューと「********」で表示されるメニューが混在しているので統一したほうが良い。

**Comment by sinatommy** [comment]
パスワードが空白でも「********」で表示に統一する。

**Comment by enoman** [comment]
下記メニューのカラムについて対応
機器一覧
・ログインパスワード
・パスフレーズ
Towerホスト一覧
・ログインパスワード
・パスフレーズ

**Comment by enoman** [comment]
完了
