### ISSUE TITLE
【メニュー作成】編集時にメニュー名の変更を不可にする

### ISSUE THREAD

**Issue by ta-matsuo** [exastro-suite/it-automation#727]
メニュー作成の編集時にメニュー名を変更すると、変更前のメニューが残ってしまう。
編集時にはメニュー名の変更を不可とする。

**Comment by HibikiNanri** [comment]
・[メニュー定義一覧]ページに「メニュー作成状態」カラムを追加
→メニューが実際に作られたタイミングで「作成済み」に。それ以外は「未作成」に。

・「作成済み」の場合は[メニュー定義・作成]ページと[メニュー定義一覧]ページから「メニュー名」を変更できなくする。

・古いバージョンからバージョンアップした場合は「作成済み（カラムの値:2）」が挿入されるようにする。（バージョンアップパッチ側で対応）

・[メニュー定義一覧]ページから[メニュー定義・作成]ページに遷移したとき、対象の「メニュー作成状態」が「未作成」だった場合、「編集」ボタンを削除し、「初期化」のボタンの名前を「作成」に変更する

・[ロール・メニュー紐付管理]ページにて[メニュー定義一覧]ページをデフォルトで「閲覧のみ」に変更

**Comment by HibikiNanri** [comment]
マージ済み。
要ドキュメント修正。

**Comment by HibikiNanri** [comment]
[メニュー定義・作成]ページで表示される「最終更新日時」「最終更新者」について、以下の仕様とする。

>[メニュー定義一覧]ページのレコードの「最終更新者」が「メニュー作成機能」（backyardがレコードを更新する際のユーザ）の場合は、履歴テーブルから「最終更新者」が「メニュー作成機能」のレコードを除いた中から最新のデータの「最終更新日時」「最終更新者」を表示する。
