### ISSUE TITLE
メニュー項目作成情報の53,460バイトバリデをはずす

### ISSUE THREAD

**Issue by wakkysan** [exastro-suite/it-automation#73]
標準DBがMariaDBになったため、掲題のバリデーションチェックをはずす。
本格対応としては、MariaDBに即したバリデーションチェックが必要だが、単純式では算出できないので、一旦はずすにとどめ、ver1.4に盛り込んでほしい。

**Comment by naoki-kondo** [comment]
払い戻し完了
