### ISSUE TITLE
【Terraform-driver】conductor_workflowdirへの対応

### ISSUE THREAD

**Issue by yoshi-kooooh** [exastro-suite/it-automation#732]
#722 と関わる話だが、
いわゆる「conductor_workflowdir」に情報を上げられれば、
後続のMovement(Ansible系であることが多いと思う)に情報を連携できると思いました。

**Comment by sinatommy** [comment]
#722の対応後に着手

**Comment by ayaka-shinomiya** [comment]
[仕様]
・Conductor実行時、ResultData_xxxxxxxxxx.zipにあるapply.logからoutputを切り出し、conductor_workflowdirへjsonもしくはymlとして作成する
・ファイル名は『terraform_output_0000000001.[拡張子]』

**Comment by ayaka-shinomiya** [comment]
[バグ]
APIからstate-version-outputsを取得した際、key値が入力通りに返却されないバグがTerraform側で発生中。
修正予定はあるが、具体的な時期は未定。

バグの内容：
・『_』が『-』で返却される
・大文字が小文字になる。

例：
入力値）VAR_HOGE
返却値）var-hoge

[v1.9.0での対応案]
案１．Terraformでの修正が完了するまで大文字→小文字、アンダーバー→ハイフンで運用
案２．Applyログから切り取るロジックを用意する。修正されたらAPIで取得する仕様に戻す

=> 案１＋案２で運用。Terraformのバージョンを見て使い分ける。

**Comment by sinatommy** [comment]
連携できるTerraformのバージョンなどを、ドキュメントに明記する。
