### ISSUE TITLE
【全般】ExastroOASEで利用するユーザを初期敷き込みしてほしい

### ISSUE THREAD

**Issue by wakkysan** [exastro-suite/it-automation#752]

**Comment by ta-matsuo** [comment]
ユーザは作成せずに「ロール管理」と「ロール・メニュー紐付管理」に以下のデータを初期登録しておくようにする。

■ロール管理
ロール名: oaseアクション

■ロール・メニュー紐付管理
以下のメニューを「oaseアクション」ロールに紐づける。

メニューID  メニュー名                  紐付  
------------------------------------------------
2100000205  メニュー管理                                閲覧のみ
2100000303  機器一覧                                       閲覧のみ
2100000304  投入オペレーション一覧             メンテナンス可
2100000305  Movement一覧                             閲覧のみ
2100000308  Symphony作業実行                     メンテナンス可
2100000309  Symphony作業確認                     メンテナンス可
2100000311  Symphony紐付Movement一覧    閲覧のみ
2100020103  Movement一覧                            閲覧のみ
2100020108  作業対象ホスト                           メンテナンス可
2100020109  代入値管理                                  閲覧のみ
2100020203  Movement一覧                           閲覧のみ
2100020209  作業対象ホスト                          メンテナンス可
2100020210  代入値管理                                 閲覧のみ
2100020306  Movement一覧                          閲覧のみ
2100020310  作業対象ホスト                         メンテナンス可
2100020311  代入値管理                                閲覧のみ
2100160001  メニュー定義一覧                     閲覧のみ
2100160002  メニュー項目作成情報              閲覧のみ
2100180004  Conductor作業実行                  メンテナンス可
2100180005  Conductor作業確認                  メンテナンス可
2100180007  Conductor紐付Node一覧         閲覧のみ

**Comment by y-koyama-git** [comment]
追加で以下のメニューもお願い致します。
メニューID メニュー名 紐付
2100000204 メニューグループ管理 閲覧のみ

すみませんが、宜しくお願い致します。
