### ISSUE TITLE
【管理コンソール】バージョン情報をRESTで取得したい

### ISSUE THREAD

**Issue by wakkysan** [exastro-suite/it-automation#758]
「バージョン情報」メニューは特殊な作りとなっているが、サイボーグloadtableにすることでREST過対応できると思われます。

**Comment by a-koizumi** [comment]
【#758の仕様は以下となる】
①v1.9.0より前はバージョン情報メニューはRestAPIに対応していないのでv1.9.0以降のみ取得できる。

②v1.9.0以前のバージョン情報を取得すると以下エラーになる。

　"[loadTable.php] does not exist."
