### ISSUE TITLE
【Ansible-Driver】マルチカラムの代入値自動登録連携

### ISSUE THREAD

**Issue by sinatommy** [exastro-suite/it-automation#76]

**Comment by enoman** [comment]
代入値管理の具体値をマルチラインテキストに変更し複数行具体値の登録を可能にする。
ITAreadmeとdefaultファイルで複数行具体値の変数定義を可能なする。
複数行具体値は、複数行の扱い方を示す記号が必要となりが、
代入値管理で入力された複数行具体値は、固定で「|-」とする。
※各行の改行が有効。最終行の改行は無効。

VAR_sample
具体値    
----------
line1
line2
line3
----------
          
変数定義
--------------
VAR_sample: |-
     line1
     line2	
     line3	
--------------

echo -e '{{ VAR_sample }}'		
実行結果："line1\nline2\nline3"		


YAMLパーサー
PHP拡張モジュールのYAMLパーサーに変更。
ITAreadmeとdefaultファイルで多段変数を定義する際に必要としてたいダミーのデフォルト値の記述が不要になる。
など、パーサー依存の記述制限がいくつか改善。

**Comment by enoman** [comment]
Pioneerの代入値管理の具体値は、これまで通りシングルラインテキストとする。

**Comment by sinatommy** [comment]
完了
