### ISSUE TITLE
【RestAPI】FILTERでメニューのデータを取得する際に見出し行を含まないオプションが欲しい

### ISSUE THREAD

**Issue by yoshi-kooooh** [exastro-suite/it-automation#768]
RestAPIのFILTERでメニューのデータを取得する際、必ず「見出し行」が付いてきます。
しかしながら、大概の場合、外部コードの中からRestAPIがコールされますので、その際、ほとんどのケースで「見出し行」が処理の邪魔になります。
(1要素目、というか0番レコードを省く、といった考慮がいつも必要になります。。。)
現状、INFOという機能で、「見出し行」だけを取得するモードがありますが、その逆に「見出し行」を含まず有効データのみ取得するモードが欲しいです。
現状、多くの方々がRestAPIを使ってらっしゃると思いますので、互換を保ちつつ、新たなモードを追加してほしいです。
(OracleのSet Heading off的な感じです、つまり。)

いったん、ta-matsuo氏をAssigneesに記載させて頂きますが、適宜、ディスパッチ頂ければ幸いです。

**Comment by k-tomita1** [comment]
X-CommandにFILTER_DATAONLYと指定することで見出し行を省略できるように修正。
