### ISSUE TITLE
【メニュー作成】リピートを使った際の連番の仕様について

### ISSUE THREAD

**Issue by HibikiNanri** [exastro-suite/it-automation#776]
■現状
・グループの有無にかかわらず、カラムの項目名の後ろに連番[2][3][4]...がつく

■改修
・リピートの中にグループがあれば、一番親のグループ名の後ろに連番[2][3][4]...がつくようにする。
→グループが無ければカラムの項目名の後ろに連番。

**Comment by ta-matsuo** [comment]
対応なし。
