### ISSUE TITLE
【Terraformドライバ】「WorkSpace管理」で「登録」「更新」「削除」のボタンをEnter押しっぱなしにするとエラーが起きる

### ISSUE THREAD

**Issue by yoshi-kooooh** [exastro-suite/it-automation#781]
「WorkSpace管理」メニューにて、「登録」「更新」「削除」のボタンがあるが、
クリックしたらまずクリックされたボタン自らを非活性にしてから処理をしたほうが良いと思いました。
そうしなければ、Enterボタンを押しっぱなしにするとエラーが起きます。
クリックで動くJavascriptの先頭で、自分自身を非活性にしてから業務処理をするようにすれば、
Enter押しっぱなし等に対応できると思います。
※「WorkSpace管理」以外にもあるかもしれません。
　「Organization管理」とか。

**Comment by HibikiNanri** [comment]
マージ済み
