### ISSUE TITLE
【メニュー作成ツール】プルダウン選択としてデフォルトで選択できる項目の追加整備

### ISSUE THREAD

**Issue by yoshi-kooooh** [exastro-suite/it-automation#782]
現状、メニュー作成ツールにおいて、
プルダウン選択としてデフォルトで選択できるのは以下の4項目だと思います。

[現状、選択可能]
・ 基本コンソール-機器一覧-ホスト名
・ 基本コンソール-機器一覧-IPアドレス
・ Ansible共通-ファイル管理-ファイル埋込変数名
・ Ansible共通-テンプレート管理-テンプレート埋込変数名

これでは不足しており、以下も選択対象にして頂けますようお願いします。

[選択対象にしてほしい]
① 管理コンソール-メニュー管理-[メニューグループ名称＋メニュー名称]
② 管理コンソール-ユーザ管理-ログインID
③ 基本コンソール-投入オペレーション一覧-オペレーション名
④ 基本コンソール-Movement一覧-Mevement名
⑤ Symphony-Symphonyクラス一覧-Symphony名称
⑥ Conductor-Conductorクラス一覧-Conductor名称
⑦ ホストグループ管理-ホストグループ一覧-ホストグループ名
⑧ Ansible共通-グローバル変数管理-グローバル変数名

また、直接の選択対象ではないけれど、参照項目としてラインナップしてほしいのは下記です。
https://github.com/exastro-suite/it-automation/issues/47
に関わる話です。

[参照項目として使えるようにしてほしい]
(1) 管理コンソール-メニュー管理-メニューID ([メニューグループ名称＋メニュー名称]から参照)
(3) 管理コンソール-ユーザ管理-メールアドレス (ログインIDから参照)
(4) 基本コンソール-機器一覧-IPアドレス (ホスト名から参照)
(5) 基本コンソール-機器一覧-ログインユーザID (ホスト名から参照)
(6) 基本コンソール-機器一覧-ログインパスワード (ホスト名から参照、ただし、Sensitive項目！)

お忙しいところ申し訳ございませんが、
本件急ぎ使いたいので、Ver1.7.0でお願いできれば助かります。

※例の如く、一旦、ta-matsuo氏をAssigneesにしていますが、適宜ディスパッチをお願いします。

**Comment by HibikiNanri** [comment]
マージ済み
要ドキュメント修正

**Comment by enoman** [comment]
[選択対象にしてほしい]
⑧ Ansible共通-グローバル変数管理-グローバル変数名
バックヤード側でグローバル変数を代入値管理の具体値として送り込むように修正。
しかし、代入値管理の具体値設定可能な変数はテンプレート変数(TPF)とファイル管理変数(CPF)だけなので
代入値自動登録でグローバル変数を扱うことは出来るが、ホスト変数ファイルにグローバル変数の情報を反映すね処理がないので、作業実行が異常終了してしまう。

**Comment by HibikiNanri** [comment]
>⑧ Ansible共通-グローバル変数管理-グローバル変数名
上記を選択肢から除外しました。
