### ISSUE TITLE
【管理コンソール】ITA画面デザインテーマ選択化

### ISSUE THREAD

**Issue by m-takahashi-if** [exastro-suite/it-automation#8]
ログインユーザごとに、いくつかのデザインテーマからCSSを選択できるようにする。
※この機能の範囲内でフォント変更の暫定対処にはなる。(Excelは対処できないが)

[利用者からの声]
・複数環境でITAを利用しているので、画面の色を変える機能が欲しい。
・WebもExcelもフォントが等幅ではないので、見づらい。

**Comment by sinatommy** [comment]
ログインユーザごとではなく、環境ごとにデザインが変えられるようにする。

**Comment by sinatommy** [comment]
個人で設定できる（キャッシュクリアするまで）パターンは、実装しない。

**Comment by ta-matsuo** [comment]
払戻完了。
