### ISSUE TITLE
【インストーラ】ita_answers.txtの初期値変更

### ISSUE THREAD

**Issue by yoshi-kooooh** [exastro-suite/it-automation#805]
インストーラで下記が気になります。

①「ita_directory」はデフォルトで"/exastro"って書いておいてあげるのが親切だと思いました。

②「terraform_driver」はyesにしておいてもらえたら嬉しいです。(今後、利用者が増えそうな予想なので)

**Comment by yoshi-kooooh** [comment]
>②「terraform_driver」はyesにしておいてもらえたら嬉しいです。

こちらについては、
Dockerイメージ、Podmanイメージも対応をお願いしたいです。
※今回、コンテナ版でTerraform使おうとしてハマりました。

**Comment by ta-matsuo** [comment]
言語設定ita_languageの初期値もen_USからja_JPに変更します。
