### ISSUE TITLE
【Terraformドライバ】「Terraform Enterprise登録管理」というメニュー名について

### ISSUE THREAD

**Issue by yoshi-kooooh** [exastro-suite/it-automation#806]
「Terraform Enterprise登録管理」
というメニューがあると思いますが、
Terraform Enterpriseだけでなく
・Terraform Cloud
・Terraform Cloud for Business
とのインタフェースもできる認識ですので、
名前がEnterprise限定的でない方が良いと思いました。

**Comment by HibikiNanri** [comment]
「連携先Terraform管理」に修正します。
その他「Terraform Enterprise」と表記している箇所は「Terraform」に修正します。

**Comment by HibikiNanri** [comment]
マージ済み。
要ドキュメント修正。
