### ISSUE TITLE
【管理コンソール】パスワードを取得するI/Fが欲しい

### ISSUE THREAD

**Issue by sudodaisuke-jp** [exastro-suite/it-automation#813]
【管理コンソール】パスワードを取得するI/Fが欲しい
ユーザ情報は取得できるが、DB内のパスワードがハッシュ化しているため取得することができない。セキュリティの担保もあると思うのでモードの変更で取得出来る、出来ないが選択でき、REST APIで取得出来るようにして欲しい。

**Comment by ta-matsuo** [comment]
セキュリティ的に許容できないため、クローズ。
