### ISSUE TITLE
【資材管理】本気でIaCのCI/CDに対応する

### ISSUE THREAD

**Issue by yoshi-kooooh** [exastro-suite/it-automation#815]
Ver1.8.0の目玉としてチャレンジしましょう！！！！

**Comment by enomantest** [comment]
Gitとのsshプロトコルはv1.8.0以降の対応とする。

**Comment by enoman** [comment]
RestAPIでPlaybook素材集と対話ファイル素材集の更新を行うので、ファイルアップロードのバリデータ処理を登録更新時のバリデータ処理に移動。
※文字コードUTF-8・BOM付・YAML文法チェック
