### ISSUE TITLE
【収集機能】収集機能のログ出力項目の整理

### ISSUE THREAD

**Issue by y-yonekura** [exastro-suite/it-automation#821]
収集機能のログ出力内容の追加、細分化
例）YAML形式のファイルでない場合等

**Comment by a-koizumi** [comment]
追加で「ステータスの細分化改善」もお願いしたい。

作業状況ステータス：完了以外の収集状況のステータスが空になるのが
エラーなのか何なのか迷う。

**Comment by y-yonekura** [comment]
・収集インターフェース情報のRESTユーザー項目へ未入力時の説明を追加
・収集エラーステータス追加
・収集実行時、正常時以外の状態でログ出力を追加
　　yamlファイルのパース関連（形式不正等）
　　収集項目の設定値関連
・ログ出力時のRest結果の表示形式の変換対応

備忘
インターフェース情報のREST接続情報無（RESTユーザー、パスワード未入力時）のFAQ対応
