### ISSUE TITLE
【全般】未実行ステータスの作業のキャンセル

### ISSUE THREAD

**Issue by sinatommy** [exastro-suite/it-automation#83]
作業実行のステータスが「未実行」の場合、強制停止ができない。

**Comment by a-ikegame** [comment]
ステータスが「未実行」の作業に対し、緊急停止が実施できるよう修正。
尚、開始日時・終了日時に値は登録しない。

【対象メニュー】
・Ansible-Legacy
・Ansible-Pioneer
・Ansible-LegacyRole
・Terraform
・Symphony
・Conductor
