### ISSUE TITLE
【Terraform-driver】結果ファイル(zip)内のステートファイルが平文

### ISSUE THREAD

**Issue by yoshi-kooooh** [exastro-suite/it-automation#849]
結果ファイル(zip)内のステートファイルが平文のままなので、
場合によっては、ssh公開鍵の文字列なのが読めます。

ky_encrypt等かけたほうが良いと思います。
(「通常は使うものではなく、バックアップ用途である。」という考え方で。)

**Comment by HibikiNanri** [comment]
マージ済み。
要ドキュメント修正。
