### ISSUE TITLE
【メニュー作成】正規表現の変更でデータや履歴が初期化されないようにしたい

### ISSUE THREAD

**Issue by sinatommy** [exastro-suite/it-automation#887]
パラメータシートの単一行テキストに対する正規表現規制は、変更する場合には表の定義変更扱いとなり、データ／履歴がクリアされてしまう。
データ初期化せずに、変更ができるようになってほしい。

**Comment by sinatommy** [comment]
正規表現規制を変更した場合、すでに入っているデータが更新後の規制に合わないデータはどうするか、を検討する必要はあります。

**Comment by HibikiNanri** [comment]
・「編集」で既存項目の「正規表現」を変更可能に
・既存項目の「正規表現」を変更すると、『既存データと不整合が発生する可能性がある』旨を、編集実行時の警告ダイアログに記載。

**Comment by HibikiNanri** [comment]
マージ済み。
要ドキュメント修正。
