### ISSUE TITLE
AnsibleTower経由のSSH鍵認証接続不可

### ISSUE THREAD

**Issue by m-takahashi-if** [exastro-suite/it-automation#9]
ssh鍵交換しているターゲットにAnsibleTower経由で鍵認証(ssh鍵ファイル指定なし)で接続が出来ない。

**Comment by enoman** [comment]
各認証(パスワード認証・鍵ファイル認証・鍵ファイル指定なし認証)で、ssh接続オプションが設定されている。
ssh直で鍵ファイル指定なし認証時のssh接続オプションを指定するとsshが接続出来ない。
サポートに確認中。

**Comment by enoman** [comment]
「設定」→「ジョブ」→「分離されたジョブに公開するパス」を設定する必要がありました。
