### ISSUE TITLE
【Ansible共通】オプションパラメータをMovement側の設定が有効となるようにしてほしい

### ISSUE THREAD

**Issue by yoshiyuki-konuma** [exastro-suite/it-automation#911]
Ansible共通のインターフェース情報でのオプションパラメータと
AnsibleDriverのMovement一覧でのオプションパラメータとの両方に値が設定されている場合、

AnsibleEngine → 実行可能
AnsibleTower → バリデーションエラー「オプションパラメータが重複しています。」
という挙動になっている

AnsibleTowerでも動作するようにしてほしい。
同一のオプションが存在する場合、Movementでの設定が勝つ挙動が好ましい。

**Comment by sinatommy** [comment]
AnsibleEngineではどちらが有効になるのかを調査する。

AnsibleEngineとTowerの挙動が違うことをマニュアルに記載する。

AnsibleEngineとTowerの挙動を統一できるか検討する。

**Comment by enoman** [comment]
AnsibleEngineのパラメータの扱いは
下記マニュアルの記載の通り、基本は後書きのパラメータが有効になる。
ITAでは、以下の順番でansible-playbookのオプションパラメータを設定しているので、Movement一覧=>オプションパラメータのパラメータが有効になる。
・Ansible共通=>インターフェース情報=>オプションパラメータ
・Movement一覧=>オプションパラメータ
==========================================
https://docs.ansible.com/ansible/2.9_ja/reference_appendices/general_precedence.html
=======抜粋===========
コマンドラインで、単一の値しか許容できないパラメーターに複数の値を指定すると、
最後に定義した値が優先されます。
==========================================
が、以下の様にパラメータの特性によっていろいろな定義がある模様。
---tagsは複数個のパラメータを許容。--verboseはvの最大値を適用。

**Comment by ide-hirofumi1** [comment]
AnsibleTowerで同一のオプションが存在する場合、Movementでの設定が勝つ挙動以外に以下を対応
・tags、-skip-tagsは複数個のパラメータを許容
・forksは数値以外はエラー
