### ISSUE TITLE
【Conductor】状態監視周期の確認

### ISSUE THREAD

**Issue by wakkysan** [exastro-suite/it-automation#933]

**Comment by y-yonekura** [comment]
１．作業状態の更新周期が、各インターフェース情報の状態監視周期(単位ミリ秒)で動いているかの動作確認

- 各Driverの作業状態確認画面
　-Ansible-Legacy
　-Ansible-Pioneer
　-Ansible-LegacyRole
　-Terraform

-  Symphony作業確認画面

２．Conductor作業確認にて、作業状態の更新周期が、3000ms固定となっているので、インターフェース情報の状態監視周期(単位ミリ秒)を参照するように修正
