### ISSUE TITLE
【メニュー作成】プルダウン選択で入力した値にリンクを付与する

### ISSUE THREAD

**Issue by ta-matsuo** [exastro-suite/it-automation#950]
プルダウンのメニューにジャンプ＆絞り込みする挙動とする。

**Comment by HibikiNanri** [comment]
■初期フィルタを項目名でも指定できるように
階層(グループ)の指定は「\」マークで区切るようにしました。
項目名のみでも検索できるようにしました。（同じ項目がある場合は最初に一致したもの）
inputのID指定も残してあります。
 
対象が二つ以上ある場合は-で区切って指定にしました。
No=1-99

検索優先度は
1: BBB\AAA=*** 階層こみ
2: AAA=*** 項目名のみ
3: inputのID Filter1Tbl_1=***

**Comment by HibikiNanri** [comment]
・「プルダウン選択」の項目はLinkIDColumnで作成（参照元へリンク）。
・「プルダウン選択」でも#178で追加した『「YES/No」、「True/False」、「*/（ブランク）」』の場合はIDColumnで作成（リンク無し）。

**Comment by HibikiNanri** [comment]
マージ済み
要ドキュメント修正

**Comment by HibikiNanri** [comment]
項目名に記号が入っていた際の不具合を修正。

**Comment by HibikiNanri** [comment]
>対象が二つ以上ある場合は-で区切って指定にしました。
>No=1-99

上記について区切り文字を「-」ではなく「~」に変更。
（値に「-」が入るケースを考慮）
