### ISSUE TITLE
【エクスポート/インポート】RESTのエラーの修正

### ISSUE THREAD

**Issue by ayaka-shinomiya** [exastro-suite/it-automation#975]

**Comment by ayaka-shinomiya** [comment]
RESTでエクスポートを行う際、以下のエラーが出る事象を修正

<br />
<b>Fatal error</b>:  Cannot redeclare validateDate() (previously declared in /exastro/ita-root/libs/webindividuallibs/systems/2100000211/web_functions_for_data_export.php:450) in <b>/exastro/ita-root/libs/webindividuallibs/systems/2100000211/80_menu_export_execution.php</b> on line <b>296</b><br />

**Comment by sinatommy** [comment]
v1.7.1ではマージ済み。

**Comment by ayaka-shinomiya** [comment]
v1.8.0マージ済み
