### ISSUE TITLE
【Ansible-Driver】Ansible Towerにすると作業実行に不要なジャンプ＆絞り込みするボタンが表示される

### ISSUE THREAD

**Issue by a-koizumi** [exastro-suite/it-automation#976]
「Ansible共通」インターフェース情報の実行エンジンを「Ansible Tower」に設定すると、
「Ansible-Legacy」コンソールの「作業実行」Movement[一覧]に「Movement-Playbook紐付」ボタンが表示される。
アクセス権、アクセス許可ロールがずれて画面がくずれる。

※「Ansible-Pioneer」「「Ansible-LegacyRole」も同様
https://github.com/exastro-suite/it-automation/issues/705のバグ

**Comment by sinatommy** [comment]
v1.7.1とv1.8.0でマージ済み
