### ISSUE TITLE
【基本コンソール】Symphonyクラス名称が一意になっていない

### ISSUE THREAD

**Issue by a-koizumi** [exastro-suite/it-automation#98]
Symphonyクラス名称が一意になっていないため、
同じ名称でいくつでも登録できてしまう。
【対象画面】
基本コンソール
（Symphonyクラス編集）

**Comment by ta-matsuo** [comment]
「Symphonyクラス名称」の各メニューの項目名が不一致になっている。
「Symphonyクラス名称」に統一する。

「Symphonyクラス一覧」メニュー・・・Symphony名称
「Symphonyクラス編集」メニュー・・・Symphonyクラス名称
「Symphony作業一覧」メニュー・・・Symphonyクラス名
「定期作業実行」メニュー・・・Symphonyクラス名

**Comment by ta-matsuo** [comment]
払戻完了。
