### ISSUE TITLE
【基本コンソール】機器一覧のパスワードをExcel更新したときの挙動

### ISSUE THREAD

**Issue by wakkysan** [exastro-suite/it-automation#983]

**Comment by wakkysan** [comment]
WebUIでパスワードA入力→ExcelでパスワードBを記載しアップロードしてもパスワードBが反映されない。

**Comment by enoman** [comment]
Excel/RestAPIからパスワードを変更した場合、内部で保持しているansivle-vaultしたパスワードがクリアされない為、パスワード変更前に作業実行したときのパスワードをansivle-vaultしたパスワードが使用されてしまいます。
1.7.1以前のバージョンでExcel/RestAPIからパスワードを変更してしまった場合
webからデタラメなパスワード、正しいパスワードの順でパスワードを登録しなおしてください。
内部で保持しているansivle-vaultしたパスワードがクリアされます。

1.4からの不備

**Comment by enoman** [comment]
完了
