### ISSUE TITLE
「作業状態確認」メニューのロール情報を「閲覧のみ」で設定すると表示権限が無いメニューと表示される

### ISSUE THREAD

**Issue by sudodaisuke-jp** [exastro-suite/it-automation#987]
「Ansible-Legacy」-「作業状態確認」メニューのロール情報を「閲覧のみ」に設定すると「表示権限が無いメニュー・・・」のポップアップが表示されてしまい、作業状態が確認できない。
※「Conductor」-「Conductor作業状態確認」の場合はローディングの画面が表示され続けます。

**Comment by ta-matsuo** [comment]
対象メニュー
2100020001:Ansible-Legacy:2100020112:作業状態確認
2100020002:Ansible-Pioneer:2100020212:作業状態確認
2100020003:Ansible-LegacyRole:2100020313:作業状態確認
2100080001:Terraform:2100080010:作業状態確認
2100100001:Symphony:2100000309:Symphony作業確認
2100090001:Conductor:2100180005:Conductor作業確認
