### ISSUE TITLE
【ホストグループ】「ホストグループ名」の廃止不備対応

### ISSUE THREAD

**Issue by a-koizumi** [exastro-suite/it-automation#99]
【操作手順】
①ホスト紐付管理で「廃止」する。（ホストグループ名が廃止される）
②ホストグループ一覧「ホストグループ名」がID変換エラーにならない。廃止もされない。
【対象画面】
ホストグループ管理
（ホストグループ一覧）
（ホスト紐付管理）

**Comment by ta-matsuo** [comment]
仕様通りなので対応なし。
